"""Generated from Smithy shape ``com.amazonaws.iot#CertificateDescription``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_iot.types.aws_account_id
    import capo_iot.types.certificate_arn
    import capo_iot.types.certificate_id
    import capo_iot.types.certificate_mode
    import capo_iot.types.certificate_pem
    import capo_iot.types.certificate_status
    import capo_iot.types.certificate_validity
    import capo_iot.types.customer_version
    import capo_iot.types.date_type
    import capo_iot.types.generation_id
    import capo_iot.types.transfer_data


class CertificateDescription(TypedDict, closed=True):
    certificate_arn: NotRequired["capo_iot.types.certificate_arn.CertificateArn"]
    """<p>The ARN of the certificate.</p>"""
    certificate_id: NotRequired["capo_iot.types.certificate_id.CertificateId"]
    """<p>The ID of the certificate.</p>"""
    ca_certificate_id: NotRequired["capo_iot.types.certificate_id.CertificateId"]
    """<p>The certificate ID of the CA certificate used to sign this certificate.</p>"""
    status: NotRequired["capo_iot.types.certificate_status.CertificateStatus"]
    """<p>The status of the certificate.</p>"""
    certificate_pem: NotRequired["capo_iot.types.certificate_pem.CertificatePem"]
    """<p>The certificate data, in PEM format.</p>"""
    owned_by: NotRequired["capo_iot.types.aws_account_id.AwsAccountId"]
    """<p>The ID of the Amazon Web Services account that owns the certificate.</p>"""
    previous_owned_by: NotRequired["capo_iot.types.aws_account_id.AwsAccountId"]
    """<p>The ID of the Amazon Web Services account of the previous owner of the certificate.</p>"""
    creation_date: NotRequired["capo_iot.types.date_type.DateType"]
    """<p>The date and time the certificate was created.</p>"""
    last_modified_date: NotRequired["capo_iot.types.date_type.DateType"]
    """<p>The date and time the certificate was last modified.</p>"""
    customer_version: NotRequired["capo_iot.types.customer_version.CustomerVersion"]
    """<p>The customer version of the certificate.</p>"""
    transfer_data: NotRequired["capo_iot.types.transfer_data.TransferData"]
    """<p>The transfer data.</p>"""
    generation_id: NotRequired["capo_iot.types.generation_id.GenerationId"]
    """<p>The generation ID of the certificate.</p>"""
    validity: NotRequired["capo_iot.types.certificate_validity.CertificateValidity"]
    """<p>When the certificate is valid.</p>"""
    certificate_mode: NotRequired["capo_iot.types.certificate_mode.CertificateMode"]
    """<p>The mode of the certificate.</p> <p> <code>DEFAULT</code>: A certificate in <code>DEFAULT</code> mode is either generated by Amazon Web Services IoT Core or registered with an issuer certificate authority (CA) in <code>DEFAULT</code> mode. Devices with certificates in <code>DEFAULT</code> mode aren't required to send the Server Name Indication (SNI) extension when connecting to Amazon Web Services IoT Core. However, to use features such as custom domains and VPC endpoints, we recommend that you use the SNI extension when connecting to Amazon Web Services IoT Core.</p> <p> <code>SNI_ONLY</code>: A certificate in <code>SNI_ONLY</code> mode is registered without an issuer CA. Devices with certificates in <code>SNI_ONLY</code> mode must send the SNI extension when connecting to Amazon Web Services IoT Core. </p> <p>For more information about the value for SNI extension, see <a href="https://docs.aws.amazon.com/iot/latest/developerguide/transport-security.html">Transport security in IoT</a>.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CertificateDescription) -> dict:
    out: dict = {}
    if "certificate_arn" in value:
        out["certificateArn"] = value["certificate_arn"]
    if "certificate_id" in value:
        out["certificateId"] = value["certificate_id"]
    if "ca_certificate_id" in value:
        out["caCertificateId"] = value["ca_certificate_id"]
    if "status" in value:
        import capo_iot.types.certificate_status

        out["status"] = capo_iot.types.certificate_status.serialize_json(
            value["status"]
        )
    if "certificate_pem" in value:
        out["certificatePem"] = value["certificate_pem"]
    if "owned_by" in value:
        out["ownedBy"] = value["owned_by"]
    if "previous_owned_by" in value:
        out["previousOwnedBy"] = value["previous_owned_by"]
    if "creation_date" in value:
        import capo_iot.types.date_type

        out["creationDate"] = capo_iot.types.date_type.serialize_json(
            value["creation_date"]
        )
    if "last_modified_date" in value:
        import capo_iot.types.date_type

        out["lastModifiedDate"] = capo_iot.types.date_type.serialize_json(
            value["last_modified_date"]
        )
    if "customer_version" in value:
        out["customerVersion"] = value["customer_version"]
    if "transfer_data" in value:
        import capo_iot.types.transfer_data

        out["transferData"] = capo_iot.types.transfer_data.serialize_json(
            value["transfer_data"]
        )
    if "generation_id" in value:
        out["generationId"] = value["generation_id"]
    if "validity" in value:
        import capo_iot.types.certificate_validity

        out["validity"] = capo_iot.types.certificate_validity.serialize_json(
            value["validity"]
        )
    if "certificate_mode" in value:
        import capo_iot.types.certificate_mode

        out["certificateMode"] = capo_iot.types.certificate_mode.serialize_json(
            value["certificate_mode"]
        )
    return out


def deserialize_json(data: dict) -> CertificateDescription:
    out: CertificateDescription = {}  # type: ignore[typeddict-item]
    if data.get("certificateArn") is not None:
        out["certificate_arn"] = data["certificateArn"]
    if data.get("certificateId") is not None:
        out["certificate_id"] = data["certificateId"]
    if data.get("caCertificateId") is not None:
        out["ca_certificate_id"] = data["caCertificateId"]
    if data.get("status") is not None:
        import capo_iot.types.certificate_status

        out["status"] = capo_iot.types.certificate_status.deserialize_json(
            data["status"]
        )
    if data.get("certificatePem") is not None:
        out["certificate_pem"] = data["certificatePem"]
    if data.get("ownedBy") is not None:
        out["owned_by"] = data["ownedBy"]
    if data.get("previousOwnedBy") is not None:
        out["previous_owned_by"] = data["previousOwnedBy"]
    if data.get("creationDate") is not None:
        import capo_iot.types.date_type

        out["creation_date"] = capo_iot.types.date_type.deserialize_json(
            data["creationDate"]
        )
    if data.get("lastModifiedDate") is not None:
        import capo_iot.types.date_type

        out["last_modified_date"] = capo_iot.types.date_type.deserialize_json(
            data["lastModifiedDate"]
        )
    if data.get("customerVersion") is not None:
        out["customer_version"] = data["customerVersion"]
    if data.get("transferData") is not None:
        import capo_iot.types.transfer_data

        out["transfer_data"] = capo_iot.types.transfer_data.deserialize_json(
            data["transferData"]
        )
    if data.get("generationId") is not None:
        out["generation_id"] = data["generationId"]
    if data.get("validity") is not None:
        import capo_iot.types.certificate_validity

        out["validity"] = capo_iot.types.certificate_validity.deserialize_json(
            data["validity"]
        )
    if data.get("certificateMode") is not None:
        import capo_iot.types.certificate_mode

        out["certificate_mode"] = capo_iot.types.certificate_mode.deserialize_json(
            data["certificateMode"]
        )
    return out
