"""Generated from Smithy shape ``com.amazonaws.sts#AssumedRoleUser``."""

from typing import TYPE_CHECKING

from typing_extensions import TypedDict

from capo_sts._protocol.xml import Element
from capo_sts.errors import DeserializationError

if TYPE_CHECKING:
    import capo_sts.types.arn_type
    import capo_sts.types.assumed_role_id_type


class AssumedRoleUser(TypedDict, closed=True):
    assumed_role_id: "capo_sts.types.assumed_role_id_type.assumedRoleIdType"
    """<p>A unique identifier that contains the role ID and the role session name of the role that is being assumed. The role ID is generated by Amazon Web Services when the role is created.</p>"""
    arn: "capo_sts.types.arn_type.arnType"
    """<p>The ARN of the temporary security credentials that are returned from the <a>AssumeRole</a> action. For more information about ARNs and how to use them in policies, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html">IAM Identifiers</a> in the <i>IAM User Guide</i>.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: AssumedRoleUser, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    pairs.append((f"{key_prefix}AssumedRoleId", str(value["assumed_role_id"])))
    pairs.append((f"{key_prefix}Arn", str(value["arn"])))


def deserialize_query(el: Element) -> AssumedRoleUser:
    out: AssumedRoleUser = {}  # type: ignore[typeddict-item]
    child_assumed_role_id = el.find("AssumedRoleId")
    if child_assumed_role_id is not None:
        out["assumed_role_id"] = str(child_assumed_role_id.text or "")
    else:
        raise DeserializationError("AssumedRoleUser.assumed_role_id required")
    child_arn = el.find("Arn")
    if child_arn is not None:
        out["arn"] = str(child_arn.text or "")
    else:
        raise DeserializationError("AssumedRoleUser.arn required")
    return out
