"""Generated from Smithy shape ``com.amazonaws.personalizeevents#PutEventsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_personalize_events.errors import DeserializationError

if TYPE_CHECKING:
    import capo_personalize_events.types.event_list
    import capo_personalize_events.types.string_type
    import capo_personalize_events.types.user_id


class PutEventsRequest(TypedDict, closed=True):
    tracking_id: "capo_personalize_events.types.string_type.StringType"
    """<p>The tracking ID for the event. The ID is generated by a call to the <a href="https://docs.aws.amazon.com/personalize/latest/dg/API_CreateEventTracker.html">CreateEventTracker</a> API.</p>"""
    user_id: NotRequired["capo_personalize_events.types.user_id.UserId"]
    """<p>The user associated with the event.</p>"""
    session_id: "capo_personalize_events.types.string_type.StringType"
    """<p>The session ID associated with the user's visit. Your application generates the sessionId when a user first visits your website or uses your application. Amazon Personalize uses the sessionId to associate events with the user before they log in. For more information, see <a href="https://docs.aws.amazon.com/personalize/latest/dg/recording-item-interaction-events.html">Recording item interaction events</a>.</p>"""
    event_list: "capo_personalize_events.types.event_list.EventList"
    """<p>A list of event data from the session.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: PutEventsRequest) -> dict:
    out: dict = {}
    out["trackingId"] = value["tracking_id"]
    if "user_id" in value:
        out["userId"] = value["user_id"]
    out["sessionId"] = value["session_id"]
    import capo_personalize_events.types.event_list

    out["eventList"] = capo_personalize_events.types.event_list.serialize_json(
        value["event_list"]
    )
    return out


def deserialize_json(data: dict) -> PutEventsRequest:
    out: PutEventsRequest = {}  # type: ignore[typeddict-item]
    if data.get("trackingId") is not None:
        out["tracking_id"] = data["trackingId"]
    else:
        raise DeserializationError("PutEventsRequest.tracking_id required")
    if data.get("userId") is not None:
        out["user_id"] = data["userId"]
    if data.get("sessionId") is not None:
        out["session_id"] = data["sessionId"]
    else:
        raise DeserializationError("PutEventsRequest.session_id required")
    if data.get("eventList") is not None:
        import capo_personalize_events.types.event_list

        out["event_list"] = capo_personalize_events.types.event_list.deserialize_json(
            data["eventList"]
        )
    else:
        raise DeserializationError("PutEventsRequest.event_list required")
    return out
