"""Generated from Smithy shape ``com.amazonaws.codepipeline#ThirdPartyJobData``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_codepipeline.types.action_configuration
    import capo_codepipeline.types.action_type_id
    import capo_codepipeline.types.artifact_list
    import capo_codepipeline.types.aws_session_credentials
    import capo_codepipeline.types.continuation_token
    import capo_codepipeline.types.encryption_key
    import capo_codepipeline.types.pipeline_context


class ThirdPartyJobData(TypedDict, closed=True):
    action_type_id: NotRequired["capo_codepipeline.types.action_type_id.ActionTypeId"]
    """<p>Represents information about an action type.</p>"""
    action_configuration: NotRequired[
        "capo_codepipeline.types.action_configuration.ActionConfiguration"
    ]
    """<p>Represents information about an action configuration.</p>"""
    pipeline_context: NotRequired[
        "capo_codepipeline.types.pipeline_context.PipelineContext"
    ]
    """<p>Represents information about a pipeline to a job worker.</p> <note> <p>Does not include <code>pipelineArn</code> and <code>pipelineExecutionId</code> for ThirdParty jobs.</p> </note>"""
    input_artifacts: NotRequired["capo_codepipeline.types.artifact_list.ArtifactList"]
    """<p>The name of the artifact that is worked on by the action, if any. This name might be system-generated, such as "MyApp", or it might be defined by the user when the action is created. The input artifact name must match the name of an output artifact generated by an action in an earlier action or stage of the pipeline.</p>"""
    output_artifacts: NotRequired["capo_codepipeline.types.artifact_list.ArtifactList"]
    """<p>The name of the artifact that is the result of the action, if any. This name might be system-generated, such as "MyBuiltApp", or it might be defined by the user when the action is created.</p>"""
    artifact_credentials: NotRequired[
        "capo_codepipeline.types.aws_session_credentials.AWSSessionCredentials"
    ]
    """<p>Represents an Amazon Web Services session credentials object. These credentials are temporary credentials that are issued by Amazon Web Services Secure Token Service (STS). They can be used to access input and output artifacts in the S3 bucket used to store artifact for the pipeline in CodePipeline. </p>"""
    continuation_token: NotRequired[
        "capo_codepipeline.types.continuation_token.ContinuationToken"
    ]
    """<p>A system-generated token, such as a CodeDeploy deployment ID, that a job requires to continue the job asynchronously.</p>"""
    encryption_key: NotRequired["capo_codepipeline.types.encryption_key.EncryptionKey"]
    """<p>The encryption key used to encrypt and decrypt data in the artifact store for the pipeline, such as an Amazon Web Services Key Management Service (Amazon Web Services KMS) key. This is optional and might not be present.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ThirdPartyJobData) -> dict:
    out: dict = {}
    if "action_type_id" in value:
        import capo_codepipeline.types.action_type_id

        out["actionTypeId"] = (
            capo_codepipeline.types.action_type_id.serialize_aws_json_1_1(
                value["action_type_id"]
            )
        )
    if "action_configuration" in value:
        import capo_codepipeline.types.action_configuration

        out["actionConfiguration"] = (
            capo_codepipeline.types.action_configuration.serialize_aws_json_1_1(
                value["action_configuration"]
            )
        )
    if "pipeline_context" in value:
        import capo_codepipeline.types.pipeline_context

        out["pipelineContext"] = (
            capo_codepipeline.types.pipeline_context.serialize_aws_json_1_1(
                value["pipeline_context"]
            )
        )
    if "input_artifacts" in value:
        import capo_codepipeline.types.artifact_list

        out["inputArtifacts"] = (
            capo_codepipeline.types.artifact_list.serialize_aws_json_1_1(
                value["input_artifacts"]
            )
        )
    if "output_artifacts" in value:
        import capo_codepipeline.types.artifact_list

        out["outputArtifacts"] = (
            capo_codepipeline.types.artifact_list.serialize_aws_json_1_1(
                value["output_artifacts"]
            )
        )
    if "artifact_credentials" in value:
        import capo_codepipeline.types.aws_session_credentials

        out["artifactCredentials"] = (
            capo_codepipeline.types.aws_session_credentials.serialize_aws_json_1_1(
                value["artifact_credentials"]
            )
        )
    if "continuation_token" in value:
        out["continuationToken"] = value["continuation_token"]
    if "encryption_key" in value:
        import capo_codepipeline.types.encryption_key

        out["encryptionKey"] = (
            capo_codepipeline.types.encryption_key.serialize_aws_json_1_1(
                value["encryption_key"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ThirdPartyJobData:
    out: ThirdPartyJobData = {}  # type: ignore[typeddict-item]
    if data.get("actionTypeId") is not None:
        import capo_codepipeline.types.action_type_id

        out["action_type_id"] = (
            capo_codepipeline.types.action_type_id.deserialize_aws_json_1_1(
                data["actionTypeId"]
            )
        )
    if data.get("actionConfiguration") is not None:
        import capo_codepipeline.types.action_configuration

        out["action_configuration"] = (
            capo_codepipeline.types.action_configuration.deserialize_aws_json_1_1(
                data["actionConfiguration"]
            )
        )
    if data.get("pipelineContext") is not None:
        import capo_codepipeline.types.pipeline_context

        out["pipeline_context"] = (
            capo_codepipeline.types.pipeline_context.deserialize_aws_json_1_1(
                data["pipelineContext"]
            )
        )
    if data.get("inputArtifacts") is not None:
        import capo_codepipeline.types.artifact_list

        out["input_artifacts"] = (
            capo_codepipeline.types.artifact_list.deserialize_aws_json_1_1(
                data["inputArtifacts"]
            )
        )
    if data.get("outputArtifacts") is not None:
        import capo_codepipeline.types.artifact_list

        out["output_artifacts"] = (
            capo_codepipeline.types.artifact_list.deserialize_aws_json_1_1(
                data["outputArtifacts"]
            )
        )
    if data.get("artifactCredentials") is not None:
        import capo_codepipeline.types.aws_session_credentials

        out["artifact_credentials"] = (
            capo_codepipeline.types.aws_session_credentials.deserialize_aws_json_1_1(
                data["artifactCredentials"]
            )
        )
    if data.get("continuationToken") is not None:
        out["continuation_token"] = data["continuationToken"]
    if data.get("encryptionKey") is not None:
        import capo_codepipeline.types.encryption_key

        out["encryption_key"] = (
            capo_codepipeline.types.encryption_key.deserialize_aws_json_1_1(
                data["encryptionKey"]
            )
        )
    return out
