"""Generated from Smithy shape ``com.amazonaws.personalize#CreateBatchSegmentJobRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_personalize.errors import DeserializationError

if TYPE_CHECKING:
    import capo_personalize.types.arn
    import capo_personalize.types.batch_segment_job_input
    import capo_personalize.types.batch_segment_job_output
    import capo_personalize.types.name
    import capo_personalize.types.num_batch_results
    import capo_personalize.types.role_arn
    import capo_personalize.types.tags


class CreateBatchSegmentJobRequest(TypedDict, closed=True):
    job_name: "capo_personalize.types.name.Name"
    """<p>The name of the batch segment job to create.</p>"""
    solution_version_arn: "capo_personalize.types.arn.Arn"
    """<p>The Amazon Resource Name (ARN) of the solution version you want the batch segment job to use to generate batch segments.</p>"""
    filter_arn: NotRequired["capo_personalize.types.arn.Arn"]
    """<p>The ARN of the filter to apply to the batch segment job. For more information on using filters, see <a href="https://docs.aws.amazon.com/personalize/latest/dg/filter-batch.html">Filtering batch recommendations</a>.</p>"""
    num_results: NotRequired["capo_personalize.types.num_batch_results.NumBatchResults"]
    """<p>The number of predicted users generated by the batch segment job for each line of input data. The maximum number of users per segment is 5 million.</p>"""
    job_input: "capo_personalize.types.batch_segment_job_input.BatchSegmentJobInput"
    """<p>The Amazon S3 path for the input data used to generate the batch segment job.</p>"""
    job_output: "capo_personalize.types.batch_segment_job_output.BatchSegmentJobOutput"
    """<p>The Amazon S3 path for the bucket where the job's output will be stored.</p>"""
    role_arn: "capo_personalize.types.role_arn.RoleArn"
    """<p>The ARN of the Amazon Identity and Access Management role that has permissions to read and write to your input and output Amazon S3 buckets respectively.</p>"""
    tags: NotRequired["capo_personalize.types.tags.Tags"]
    """<p>A list of <a href="https://docs.aws.amazon.com/personalize/latest/dg/tagging-resources.html">tags</a> to apply to the batch segment job.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: CreateBatchSegmentJobRequest) -> dict:
    out: dict = {}
    out["jobName"] = value["job_name"]
    out["solutionVersionArn"] = value["solution_version_arn"]
    if "filter_arn" in value:
        out["filterArn"] = value["filter_arn"]
    if "num_results" in value:
        out["numResults"] = value["num_results"]
    import capo_personalize.types.batch_segment_job_input

    out["jobInput"] = (
        capo_personalize.types.batch_segment_job_input.serialize_aws_json_1_1(
            value["job_input"]
        )
    )
    import capo_personalize.types.batch_segment_job_output

    out["jobOutput"] = (
        capo_personalize.types.batch_segment_job_output.serialize_aws_json_1_1(
            value["job_output"]
        )
    )
    out["roleArn"] = value["role_arn"]
    if "tags" in value:
        import capo_personalize.types.tags

        out["tags"] = capo_personalize.types.tags.serialize_aws_json_1_1(value["tags"])
    return out


def deserialize_aws_json_1_1(data: dict) -> CreateBatchSegmentJobRequest:
    out: CreateBatchSegmentJobRequest = {}  # type: ignore[typeddict-item]
    if data.get("jobName") is not None:
        out["job_name"] = data["jobName"]
    else:
        raise DeserializationError("CreateBatchSegmentJobRequest.job_name required")
    if data.get("solutionVersionArn") is not None:
        out["solution_version_arn"] = data["solutionVersionArn"]
    else:
        raise DeserializationError(
            "CreateBatchSegmentJobRequest.solution_version_arn required"
        )
    if data.get("filterArn") is not None:
        out["filter_arn"] = data["filterArn"]
    if data.get("numResults") is not None:
        out["num_results"] = data["numResults"]
    if data.get("jobInput") is not None:
        import capo_personalize.types.batch_segment_job_input

        out["job_input"] = (
            capo_personalize.types.batch_segment_job_input.deserialize_aws_json_1_1(
                data["jobInput"]
            )
        )
    else:
        raise DeserializationError("CreateBatchSegmentJobRequest.job_input required")
    if data.get("jobOutput") is not None:
        import capo_personalize.types.batch_segment_job_output

        out["job_output"] = (
            capo_personalize.types.batch_segment_job_output.deserialize_aws_json_1_1(
                data["jobOutput"]
            )
        )
    else:
        raise DeserializationError("CreateBatchSegmentJobRequest.job_output required")
    if data.get("roleArn") is not None:
        out["role_arn"] = data["roleArn"]
    else:
        raise DeserializationError("CreateBatchSegmentJobRequest.role_arn required")
    if data.get("tags") is not None:
        import capo_personalize.types.tags

        out["tags"] = capo_personalize.types.tags.deserialize_aws_json_1_1(data["tags"])
    return out
