"""Generated from Smithy shape ``com.amazonaws.ivschat#RoomSummary``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_ivschat.types.logging_configuration_identifier_list
    import capo_ivschat.types.message_review_handler
    import capo_ivschat.types.room_arn
    import capo_ivschat.types.room_id
    import capo_ivschat.types.room_name
    import capo_ivschat.types.tags
    import capo_ivschat.types.time


class RoomSummary(TypedDict, closed=True):
    arn: NotRequired["capo_ivschat.types.room_arn.RoomArn"]
    """<p>Room ARN.</p>"""
    id: NotRequired["capo_ivschat.types.room_id.RoomID"]
    """<p>Room ID, generated by the system. This is a relative identifier, the part of the ARN that uniquely identifies the room.</p>"""
    name: NotRequired["capo_ivschat.types.room_name.RoomName"]
    """<p>Room name. The value does not need to be unique.</p>"""
    message_review_handler: NotRequired[
        "capo_ivschat.types.message_review_handler.MessageReviewHandler"
    ]
    """<p>Configuration information for optional review of messages.</p>"""
    create_time: NotRequired["capo_ivschat.types.time.Time"]
    """<p>Time when the room was created. This is an ISO 8601 timestamp; <i>note that this is returned as a string</i>. </p>"""
    update_time: NotRequired["capo_ivschat.types.time.Time"]
    """<p>Time of the room’s last update. This is an ISO 8601 timestamp; <i>note that this is returned as a string</i>. </p>"""
    tags: NotRequired["capo_ivschat.types.tags.Tags"]
    """<p>Tags attached to the resource. Array of maps, each of the form <code>string:string (key:value)</code>. See <a href="https://docs.aws.amazon.com/tag-editor/latest/userguide/best-practices-and-strats.html">Best practices and strategies</a> in <i>Tagging Amazon Web Services Resources and Tag Editor</i> for details, including restrictions that apply to tags and "Tag naming limits and requirements"; Amazon IVS Chat has no constraints beyond what is documented there.</p>"""
    logging_configuration_identifiers: NotRequired[
        "capo_ivschat.types.logging_configuration_identifier_list.LoggingConfigurationIdentifierList"
    ]
    """<p>List of logging-configuration identifiers attached to the room.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: RoomSummary) -> dict:
    out: dict = {}
    if "arn" in value:
        out["arn"] = value["arn"]
    if "id" in value:
        out["id"] = value["id"]
    if "name" in value:
        out["name"] = value["name"]
    if "message_review_handler" in value:
        import capo_ivschat.types.message_review_handler

        out["messageReviewHandler"] = (
            capo_ivschat.types.message_review_handler.serialize_json(
                value["message_review_handler"]
            )
        )
    if "create_time" in value:
        import capo_ivschat.types.time

        out["createTime"] = capo_ivschat.types.time.serialize_json(value["create_time"])
    if "update_time" in value:
        import capo_ivschat.types.time

        out["updateTime"] = capo_ivschat.types.time.serialize_json(value["update_time"])
    if "tags" in value:
        import capo_ivschat.types.tags

        out["tags"] = capo_ivschat.types.tags.serialize_json(value["tags"])
    if "logging_configuration_identifiers" in value:
        import capo_ivschat.types.logging_configuration_identifier_list

        out["loggingConfigurationIdentifiers"] = (
            capo_ivschat.types.logging_configuration_identifier_list.serialize_json(
                value["logging_configuration_identifiers"]
            )
        )
    return out


def deserialize_json(data: dict) -> RoomSummary:
    out: RoomSummary = {}  # type: ignore[typeddict-item]
    if data.get("arn") is not None:
        out["arn"] = data["arn"]
    if data.get("id") is not None:
        out["id"] = data["id"]
    if data.get("name") is not None:
        out["name"] = data["name"]
    if data.get("messageReviewHandler") is not None:
        import capo_ivschat.types.message_review_handler

        out["message_review_handler"] = (
            capo_ivschat.types.message_review_handler.deserialize_json(
                data["messageReviewHandler"]
            )
        )
    if data.get("createTime") is not None:
        import capo_ivschat.types.time

        out["create_time"] = capo_ivschat.types.time.deserialize_json(
            data["createTime"]
        )
    if data.get("updateTime") is not None:
        import capo_ivschat.types.time

        out["update_time"] = capo_ivschat.types.time.deserialize_json(
            data["updateTime"]
        )
    if data.get("tags") is not None:
        import capo_ivschat.types.tags

        out["tags"] = capo_ivschat.types.tags.deserialize_json(data["tags"])
    if data.get("loggingConfigurationIdentifiers") is not None:
        import capo_ivschat.types.logging_configuration_identifier_list

        out["logging_configuration_identifiers"] = (
            capo_ivschat.types.logging_configuration_identifier_list.deserialize_json(
                data["loggingConfigurationIdentifiers"]
            )
        )
    return out
