"""Shared fixtures for the integration tests.

Every test here talks to a real endpoint. Cost tiers, selected by marker
(see pyproject.toml):

* ``third_party_services`` - free; the local S3-compatible servers from
  ``docker compose -f tests/docker-compose.yml up -d``. The ``s3`` fixtures are
  parametrized over every backend in ``S3_BACKENDS``; a backend whose server
  is not listening is skipped.
Async tests run under both anyio backends (asyncio and trio); the sync twins
are generated by ``ry`` (see ry.yml).

* ``paid``  - costs money on the AWS account (S3 data, Transcribe minutes,
  EC2 time, ...). Skipped unless ``CAPO_PAID=1``. Free AWS operations such as
  IAM carry no marker and run every time; AWS credentials come from the
  default chain (``AWS_PROFILE``).
"""

from __future__ import annotations

import os
import socket
import uuid
from collections.abc import AsyncIterator, Callable, Coroutine, Iterator
from concurrent.futures import ThreadPoolExecutor
from typing import Any, TypeVar
from urllib.parse import urlparse

import anyio
import pytest
from capo_s3 import AsyncS3Client, Credentials, S3Client

# Third-party S3-compatible backends. Endpoint and credentials can be overridden
# with CAPO_<BACKEND>_ENDPOINT / _ACCESS_KEY / _SECRET_KEY.
S3_BACKENDS = {
    "minio": ("http://localhost:9000", "minioadmin", "minioadmin"),
    "rustfs": ("http://localhost:9010", "rustfsadmin", "rustfsadmin"),
}
AWS_REGION = os.environ.get("CAPO_AWS_REGION", "eu-central-1")

T = TypeVar("T")


def _reachable(url: str) -> bool:
    parsed = urlparse(url)
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    try:
        with socket.create_connection((parsed.hostname or "localhost", port), timeout=0.5):
            return True
    except OSError:
        return False


def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    paid = os.environ.get("CAPO_PAID") == "1"
    for item in items:
        if "paid" in item.keywords and not paid:
            item.add_marker(pytest.mark.skip(reason="set CAPO_PAID=1 to run tests that cost money"))


@pytest.fixture(params=["asyncio", "trio"])
def anyio_backend(request: pytest.FixtureRequest) -> str:
    return request.param


async def agather(fn: Callable[[], Coroutine[Any, Any, T]], n: int) -> list[T]:
    """Run ``fn`` ``n`` times concurrently in a task group; results in call order."""
    results: list[T] = []
    slots: dict[int, T] = {}

    async def one(i: int) -> None:
        slots[i] = await fn()

    async with anyio.create_task_group() as tg:
        for i in range(n):
            tg.start_soon(one, i)
    results = [slots[i] for i in range(n)]
    return results


def gather(fn: Callable[[], T], n: int) -> list[T]:
    """Sync twin of :func:`agather`: ``n`` calls on ``n`` threads."""
    with ThreadPoolExecutor(max_workers=n) as pool:
        return list(pool.map(lambda _: fn(), range(n)))


# ---------------------------------------------------------------------------
# local S3-compatible server
# ---------------------------------------------------------------------------


def local_s3_kwargs(backend: str) -> dict:
    endpoint, access_key, secret_key = S3_BACKENDS[backend]
    env = backend.upper()
    return dict(
        endpoint=os.environ.get(f"CAPO_{env}_ENDPOINT", endpoint),
        region="us-east-1",
        force_path_style=True,
        credentials=Credentials(
            access_key=os.environ.get(f"CAPO_{env}_ACCESS_KEY", access_key),
            secret_key=os.environ.get(f"CAPO_{env}_SECRET_KEY", secret_key),
        ),
    )


@pytest.fixture(scope="session", params=list(S3_BACKENDS))
def s3_backend(request: pytest.FixtureRequest) -> str:
    """Name of the local S3-compatible backend; skips when its server is down."""
    name = request.param
    endpoint = local_s3_kwargs(name)["endpoint"]
    if not _reachable(endpoint):
        pytest.skip(f"{name} is not listening at {endpoint} (docker compose -f tests/docker-compose.yml up -d)")
    return name


def unique_name(prefix: str = "capotest") -> str:
    return f"{prefix}-{uuid.uuid4().hex[:10]}"


def purge_bucket(s3: S3Client, name: str) -> None:
    """Remove every upload, version and delete marker, then the bucket."""
    for upload in s3.list_multipart_uploads(name).get("uploads", []):
        s3.abort_multipart_upload(name, upload["key"], upload_id=upload["upload_id"])
    while True:
        out = s3.list_object_versions(name)
        versions = out.get("versions", []) + out.get("delete_markers", [])
        if not versions:
            break
        for v in versions:
            s3.delete_object(name, v["key"], version_id=v["version_id"])
    s3.delete_bucket(name)


@pytest.fixture(scope="session")
def s3(s3_backend: str) -> Iterator[S3Client]:
    with S3Client(**local_s3_kwargs(s3_backend)) as client:
        yield client


@pytest.fixture
async def async_s3(s3_backend: str) -> AsyncIterator[AsyncS3Client]:
    async with AsyncS3Client(**local_s3_kwargs(s3_backend)) as client:
        yield client


@pytest.fixture
def bucket(s3: S3Client) -> Iterator[str]:
    """A fresh bucket on the local server, purged after the test."""
    name = unique_name()
    s3.create_bucket(name)
    try:
        yield name
    finally:
        purge_bucket(s3, name)
