"""Shared fixtures for the integration tests.

Every test here talks to a real endpoint. Cost tiers, selected by marker
(see pyproject.toml):

* ``third_party_services`` - free; the local S3-compatible servers from
  ``docker compose -f tests/docker-compose.yml up -d``. A backend whose server
  is not listening is skipped.

The ``s3`` / ``async_s3`` fixtures are parametrized over the backends in
``S3_BACKENDS`` plus real AWS, and every test using them inherits the backend's
marker, so a test class needs no marker of its own.
Async tests run under both anyio backends (asyncio and trio); the sync twins
are generated by ``ry`` (see ry.yml).

* ``paid``  - costs money on the AWS account (S3 data, Transcribe minutes,
  EC2 time, ...). Skipped unless ``CAPO_PAID=1``. Free AWS operations such as
  IAM carry no marker and run every time; AWS credentials come from the
  default chain (``AWS_PROFILE``).
"""

from __future__ import annotations

import base64
import inspect
import os
import socket
import sys
import uuid
import zlib
from collections.abc import AsyncIterator, Callable, Coroutine, Iterator
from concurrent.futures import ThreadPoolExecutor
from typing import Any, TypeVar
from urllib.parse import urlparse

import anyio
import pytest
from capo_s3 import AsyncS3Client, Credentials, S3Client
from zapros import AsyncBaseHandler, BaseHandler

# Third-party S3-compatible backends. Endpoint and credentials can be overridden
# with CAPO_<BACKEND>_ENDPOINT / _ACCESS_KEY / _SECRET_KEY.
S3_BACKENDS = {
    "rustfs": ("http://localhost:9010", "rustfsadmin", "rustfsadmin"),
}
AWS_REGION = os.environ.get("CAPO_AWS_REGION", "eu-central-1")

T = TypeVar("T")

# Body.async_from_path reads files on a worker thread (anyio.open_file); Pyodide has no threads.
needs_threads = pytest.mark.skipif(sys.platform == "emscripten", reason="Pyodide has no threads")

if sys.platform == "emscripten":
    # Pyodide's event loop is the JS one and always reports itself as running, which
    # trips anyio's re-entrancy guard on every async fixture (it exists to catch
    # request.getfixturevalue() on an async fixture from inside a running test).
    from anyio._backends._asyncio import TestRunner as _AsyncioTestRunner

    _AsyncioTestRunner.is_running = lambda self: False  # type: ignore[method-assign]


def _reachable(url: str) -> bool:
    if sys.platform == "emscripten":
        # Pyodide has no sockets; the clients reach the server through JS fetch instead.
        from js import fetch  # ty: ignore[unresolved-import]
        from pyodide.ffi import run_sync  # ty: ignore[unresolved-import]

        try:
            run_sync(fetch(url))
            return True
        except Exception:
            return False
    parsed = urlparse(url)
    port = parsed.port or (443 if parsed.scheme == "https" else 80)
    try:
        with socket.create_connection((parsed.hostname or "localhost", port), timeout=0.5):
            return True
    except OSError:
        return False


def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    paid = os.environ.get("CAPO_PAID") == "1"
    for item in items:
        if "paid" in item.keywords and not paid:
            item.add_marker(pytest.mark.skip(reason="set CAPO_PAID=1 to run tests that cost money"))
    if sys.platform == "emscripten":
        # Pyodide (scripts/test-pyodide.sh) has no threads, so only the async tests run there.
        keep = [item for item in items if inspect.iscoroutinefunction(getattr(item, "function", None))]
        deselected = [item for item in items if item not in keep]
        if deselected:
            config.hook.pytest_deselected(items=deselected)
        items[:] = keep


# trio does not run on Pyodide
@pytest.fixture(params=["asyncio"] if sys.platform == "emscripten" else ["asyncio", "trio"])
def anyio_backend(request: pytest.FixtureRequest) -> str:
    return request.param


async def agather(fn: Callable[[], Coroutine[Any, Any, T]], n: int) -> list[T]:
    """Run ``fn`` ``n`` times concurrently in a task group; results in call order."""
    results: list[T] = []
    slots: dict[int, T] = {}

    async def one(i: int) -> None:
        slots[i] = await fn()

    async with anyio.create_task_group() as tg:
        for i in range(n):
            tg.start_soon(one, i)
    results = [slots[i] for i in range(n)]
    return results


def gather(fn: Callable[[], T], n: int) -> list[T]:
    """Sync twin of :func:`agather`: ``n`` calls on ``n`` threads."""
    with ThreadPoolExecutor(max_workers=n) as pool:
        return list(pool.map(lambda _: fn(), range(n)))


async def aread_body(get_object_ctx) -> bytes:
    """Drain the body of a ``get_object`` call: ``await aread_body(client.get_object(b, k))``."""
    async with get_object_ctx as obj:
        return b"".join([chunk async for chunk in obj["body"]])


def read_body(get_object_ctx) -> bytes:
    """Sync twin of :func:`aread_body`."""
    with get_object_ctx as obj:
        return b"".join(obj["body"])


def parts_of(data: bytes, size: int = 64 * 1024) -> list[bytes]:
    return [data[i : i + size] for i in range(0, len(data), size)]


async def astream(parts: list[bytes]) -> AsyncIterator[bytes]:
    """An async one-shot body; ``stream`` is the sync twin."""
    for part in parts:
        yield part


def stream(parts: list[bytes]) -> Iterator[bytes]:
    for part in parts:
        yield part


def crc32_b64(data: bytes) -> str:
    """CRC32 the way S3 reports it: big-endian, base64."""
    return base64.b64encode(zlib.crc32(data).to_bytes(4, "big")).decode()


# ---------------------------------------------------------------------------
# local S3-compatible server
# ---------------------------------------------------------------------------


def local_s3_settings(backend: str) -> tuple[str, str, str]:
    """(endpoint, access key, secret key) of a local backend, with env overrides."""
    endpoint, access_key, secret_key = S3_BACKENDS[backend]
    env = backend.upper()
    return (
        os.environ.get(f"CAPO_{env}_ENDPOINT", endpoint),
        os.environ.get(f"CAPO_{env}_ACCESS_KEY", access_key),
        os.environ.get(f"CAPO_{env}_SECRET_KEY", secret_key),
    )


def make_s3_client(
    backend: str, credentials: Credentials | None = None, http_handler: BaseHandler | None = None
) -> S3Client:
    """A client for ``backend``; AWS uses the default credentials chain unless given some."""
    if backend == "aws":
        return S3Client(region=AWS_REGION, credentials=credentials, http_handler=http_handler)
    endpoint, access_key, secret_key = local_s3_settings(backend)
    if credentials is None:
        credentials = Credentials(access_key=access_key, secret_key=secret_key)
    return S3Client(
        endpoint=endpoint,
        region="us-east-1",
        force_path_style=True,
        credentials=credentials,
        http_handler=http_handler,
    )


def make_async_s3_client(
    backend: str, credentials: Credentials | None = None, http_handler: AsyncBaseHandler | None = None
) -> AsyncS3Client:
    """Async twin of :func:`make_s3_client`."""
    if backend == "aws":
        return AsyncS3Client(region=AWS_REGION, credentials=credentials, http_handler=http_handler)
    endpoint, access_key, secret_key = local_s3_settings(backend)
    if credentials is None:
        credentials = Credentials(access_key=access_key, secret_key=secret_key)
    return AsyncS3Client(
        endpoint=endpoint,
        region="us-east-1",
        force_path_style=True,
        credentials=credentials,
        http_handler=http_handler,
    )


@pytest.fixture(
    scope="session",
    params=[pytest.param(name, marks=pytest.mark.third_party_services) for name in S3_BACKENDS]
    + [pytest.param("aws", marks=pytest.mark.paid)],
)
def s3_backend(request: pytest.FixtureRequest) -> str:
    """Backend name; a local backend skips when its server is down."""
    name = request.param
    if name != "aws":
        endpoint = local_s3_settings(name)[0]
        if not _reachable(endpoint):
            pytest.skip(f"{name} is not listening at {endpoint} (docker compose -f tests/docker-compose.yml up -d)")
    return name


def create_bucket_kwargs(backend: str) -> dict:
    """AWS needs a LocationConstraint outside us-east-1; the local servers ignore it."""
    if backend == "aws":
        return dict(create_bucket_configuration={"location_constraint": AWS_REGION})
    return {}


def unique_name(prefix: str = "capotest") -> str:
    return f"{prefix}-{uuid.uuid4().hex[:10]}"


def purge_bucket(s3: S3Client, name: str) -> None:
    """Remove every upload, version and delete marker, then the bucket."""
    for upload in s3.list_multipart_uploads(name).get("uploads", []):
        s3.abort_multipart_upload(name, upload["key"], upload_id=upload["upload_id"])
    while True:
        out = s3.list_object_versions(name)
        versions = out.get("versions", []) + out.get("delete_markers", [])
        if not versions:
            break
        for v in versions:
            s3.delete_object(name, v["key"], version_id=v["version_id"])
    s3.delete_bucket(name)


class _SyncView:
    """Sync calls on an async client, for the setup fixtures on Pyodide (see ``s3``)."""

    def __init__(self, client: AsyncS3Client) -> None:
        self._client = client

    def __getattr__(self, name: str) -> Callable[..., Any]:
        from pyodide.ffi import run_sync  # ty: ignore[unresolved-import]

        method = getattr(self._client, name)
        return lambda *args, **kwargs: run_sync(method(*args, **kwargs))


@pytest.fixture(scope="session")
def s3(s3_backend: str) -> Iterator[S3Client]:
    if sys.platform == "emscripten":
        # The sync client cannot run on Pyodide (no sync HTTP), so the sync setup
        # fixtures (bucket, ...) drive the async client through pyodide.ffi.run_sync.
        from pyodide.ffi import run_sync  # ty: ignore[unresolved-import]

        aclient = make_async_s3_client(s3_backend)
        run_sync(aclient.__aenter__())
        try:
            yield _SyncView(aclient)  # type: ignore[misc]
        finally:
            run_sync(aclient.__aexit__(None, None, None))
    else:
        with make_s3_client(s3_backend) as client:
            yield client


@pytest.fixture
async def async_s3(s3_backend: str) -> AsyncIterator[AsyncS3Client]:
    async with make_async_s3_client(s3_backend) as client:
        yield client


@pytest.fixture
def bucket(s3: S3Client, s3_backend: str) -> Iterator[str]:
    """A fresh bucket on the current backend, purged after the test."""
    name = unique_name()
    s3.create_bucket(name, **create_bucket_kwargs(s3_backend))
    try:
        yield name
    finally:
        purge_bucket(s3, name)
