"""Generated from Smithy shape ``com.amazonaws.sagemaker#ModelPackage``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_sagemaker.types.additional_inference_specifications
    import capo_sagemaker.types.approval_description
    import capo_sagemaker.types.certify_for_marketplace
    import capo_sagemaker.types.creation_time
    import capo_sagemaker.types.customer_metadata_map
    import capo_sagemaker.types.drift_check_baselines
    import capo_sagemaker.types.entity_description
    import capo_sagemaker.types.entity_name
    import capo_sagemaker.types.inference_specification
    import capo_sagemaker.types.metadata_properties
    import capo_sagemaker.types.model_approval_status
    import capo_sagemaker.types.model_life_cycle
    import capo_sagemaker.types.model_metrics
    import capo_sagemaker.types.model_package_arn
    import capo_sagemaker.types.model_package_model_card
    import capo_sagemaker.types.model_package_registration_type
    import capo_sagemaker.types.model_package_security_config
    import capo_sagemaker.types.model_package_source_uri
    import capo_sagemaker.types.model_package_status
    import capo_sagemaker.types.model_package_status_details
    import capo_sagemaker.types.model_package_validation_specification
    import capo_sagemaker.types.model_package_version
    import capo_sagemaker.types.skip_model_validation
    import capo_sagemaker.types.source_algorithm_specification
    import capo_sagemaker.types.string
    import capo_sagemaker.types.tag_list
    import capo_sagemaker.types.timestamp
    import capo_sagemaker.types.user_context


class ModelPackage(TypedDict, closed=True):
    model_package_name: NotRequired["capo_sagemaker.types.entity_name.EntityName"]
    """<p>The name of the model package. The name can be as follows:</p> <ul> <li> <p>For a versioned model, the name is automatically generated by SageMaker Model Registry and follows the format '<code>ModelPackageGroupName/ModelPackageVersion</code>'.</p> </li> <li> <p>For an unversioned model, you must provide the name.</p> </li> </ul>"""
    model_package_group_name: NotRequired["capo_sagemaker.types.entity_name.EntityName"]
    """<p>The model group to which the model belongs.</p>"""
    model_package_version: NotRequired[
        "capo_sagemaker.types.model_package_version.ModelPackageVersion"
    ]
    """<p>The version number of a versioned model.</p>"""
    model_package_registration_type: NotRequired[
        "capo_sagemaker.types.model_package_registration_type.ModelPackageRegistrationType"
    ]
    """<p> The package registration type of the model package. </p>"""
    model_package_arn: NotRequired[
        "capo_sagemaker.types.model_package_arn.ModelPackageArn"
    ]
    """<p>The Amazon Resource Name (ARN) of the model package.</p>"""
    model_package_description: NotRequired[
        "capo_sagemaker.types.entity_description.EntityDescription"
    ]
    """<p>The description of the model package.</p>"""
    creation_time: NotRequired["capo_sagemaker.types.creation_time.CreationTime"]
    """<p>The time that the model package was created.</p>"""
    inference_specification: NotRequired[
        "capo_sagemaker.types.inference_specification.InferenceSpecification"
    ]
    """<p>Defines how to perform inference generation after a training job is run.</p>"""
    source_algorithm_specification: NotRequired[
        "capo_sagemaker.types.source_algorithm_specification.SourceAlgorithmSpecification"
    ]
    """<p>A list of algorithms that were used to create a model package.</p>"""
    validation_specification: NotRequired[
        "capo_sagemaker.types.model_package_validation_specification.ModelPackageValidationSpecification"
    ]
    """<p>Specifies batch transform jobs that SageMaker runs to validate your model package.</p>"""
    model_package_status: NotRequired[
        "capo_sagemaker.types.model_package_status.ModelPackageStatus"
    ]
    """<p>The status of the model package. This can be one of the following values.</p> <ul> <li> <p> <code>PENDING</code> - The model package is pending being created.</p> </li> <li> <p> <code>IN_PROGRESS</code> - The model package is in the process of being created.</p> </li> <li> <p> <code>COMPLETED</code> - The model package was successfully created.</p> </li> <li> <p> <code>FAILED</code> - The model package failed.</p> </li> <li> <p> <code>DELETING</code> - The model package is in the process of being deleted.</p> </li> </ul>"""
    model_package_status_details: NotRequired[
        "capo_sagemaker.types.model_package_status_details.ModelPackageStatusDetails"
    ]
    """<p>Specifies the validation and image scan statuses of the model package.</p>"""
    certify_for_marketplace: NotRequired[
        "capo_sagemaker.types.certify_for_marketplace.CertifyForMarketplace"
    ]
    """<p>Whether the model package is to be certified to be listed on Amazon Web Services Marketplace. For information about listing model packages on Amazon Web Services Marketplace, see <a href="https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-mkt-list.html">List Your Algorithm or Model Package on Amazon Web Services Marketplace</a>.</p>"""
    model_approval_status: NotRequired[
        "capo_sagemaker.types.model_approval_status.ModelApprovalStatus"
    ]
    """<p>The approval status of the model. This can be one of the following values.</p> <ul> <li> <p> <code>APPROVED</code> - The model is approved</p> </li> <li> <p> <code>REJECTED</code> - The model is rejected.</p> </li> <li> <p> <code>PENDING_MANUAL_APPROVAL</code> - The model is waiting for manual approval.</p> </li> </ul>"""
    created_by: NotRequired["capo_sagemaker.types.user_context.UserContext"]
    """<p>Information about the user who created or modified an experiment, trial, trial component, lineage group, or project.</p>"""
    metadata_properties: NotRequired[
        "capo_sagemaker.types.metadata_properties.MetadataProperties"
    ]
    """<p>Metadata properties of the tracking entity, trial, or trial component.</p>"""
    model_metrics: NotRequired["capo_sagemaker.types.model_metrics.ModelMetrics"]
    """<p>Metrics for the model.</p>"""
    last_modified_time: NotRequired["capo_sagemaker.types.timestamp.Timestamp"]
    """<p>The last time the model package was modified.</p>"""
    last_modified_by: NotRequired["capo_sagemaker.types.user_context.UserContext"]
    """<p>Information about the user who created or modified an experiment, trial, trial component, lineage group, or project.</p>"""
    approval_description: NotRequired[
        "capo_sagemaker.types.approval_description.ApprovalDescription"
    ]
    """<p>A description provided when the model approval is set.</p>"""
    domain: NotRequired["capo_sagemaker.types.string.String"]
    """<p>The machine learning domain of your model package and its components. Common machine learning domains include computer vision and natural language processing.</p>"""
    task: NotRequired["capo_sagemaker.types.string.String"]
    """<p>The machine learning task your model package accomplishes. Common machine learning tasks include object detection and image classification.</p>"""
    sample_payload_url: NotRequired["capo_sagemaker.types.string.String"]
    """<p>The Amazon Simple Storage Service path where the sample payload are stored. This path must point to a single gzip compressed tar archive (.tar.gz suffix).</p>"""
    additional_inference_specifications: NotRequired[
        "capo_sagemaker.types.additional_inference_specifications.AdditionalInferenceSpecifications"
    ]
    """<p>An array of additional Inference Specification objects.</p>"""
    source_uri: NotRequired[
        "capo_sagemaker.types.model_package_source_uri.ModelPackageSourceUri"
    ]
    """<p>The URI of the source for the model package.</p>"""
    security_config: NotRequired[
        "capo_sagemaker.types.model_package_security_config.ModelPackageSecurityConfig"
    ]
    model_card: NotRequired[
        "capo_sagemaker.types.model_package_model_card.ModelPackageModelCard"
    ]
    model_life_cycle: NotRequired[
        "capo_sagemaker.types.model_life_cycle.ModelLifeCycle"
    ]
    """<p> A structure describing the current state of the model in its life cycle. </p>"""
    tags: NotRequired["capo_sagemaker.types.tag_list.TagList"]
    """<p>A list of the tags associated with the model package. For more information, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html">Tagging Amazon Web Services resources</a> in the <i>Amazon Web Services General Reference Guide</i>.</p>"""
    customer_metadata_properties: NotRequired[
        "capo_sagemaker.types.customer_metadata_map.CustomerMetadataMap"
    ]
    """<p>The metadata properties for the model package. </p>"""
    drift_check_baselines: NotRequired[
        "capo_sagemaker.types.drift_check_baselines.DriftCheckBaselines"
    ]
    """<p>Represents the drift check baselines that can be used when the model monitor is set using the model package.</p>"""
    skip_model_validation: NotRequired[
        "capo_sagemaker.types.skip_model_validation.SkipModelValidation"
    ]
    """<p>Indicates if you want to skip model validation.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ModelPackage) -> dict:
    out: dict = {}
    if "model_package_name" in value:
        out["ModelPackageName"] = value["model_package_name"]
    if "model_package_group_name" in value:
        out["ModelPackageGroupName"] = value["model_package_group_name"]
    if "model_package_version" in value:
        out["ModelPackageVersion"] = value["model_package_version"]
    if "model_package_registration_type" in value:
        import capo_sagemaker.types.model_package_registration_type

        out["ModelPackageRegistrationType"] = (
            capo_sagemaker.types.model_package_registration_type.serialize_aws_json_1_1(
                value["model_package_registration_type"]
            )
        )
    if "model_package_arn" in value:
        out["ModelPackageArn"] = value["model_package_arn"]
    if "model_package_description" in value:
        out["ModelPackageDescription"] = value["model_package_description"]
    if "creation_time" in value:
        import capo_sagemaker.types.creation_time

        out["CreationTime"] = capo_sagemaker.types.creation_time.serialize_aws_json_1_1(
            value["creation_time"]
        )
    if "inference_specification" in value:
        import capo_sagemaker.types.inference_specification

        out["InferenceSpecification"] = (
            capo_sagemaker.types.inference_specification.serialize_aws_json_1_1(
                value["inference_specification"]
            )
        )
    if "source_algorithm_specification" in value:
        import capo_sagemaker.types.source_algorithm_specification

        out["SourceAlgorithmSpecification"] = (
            capo_sagemaker.types.source_algorithm_specification.serialize_aws_json_1_1(
                value["source_algorithm_specification"]
            )
        )
    if "validation_specification" in value:
        import capo_sagemaker.types.model_package_validation_specification

        out["ValidationSpecification"] = (
            capo_sagemaker.types.model_package_validation_specification.serialize_aws_json_1_1(
                value["validation_specification"]
            )
        )
    if "model_package_status" in value:
        import capo_sagemaker.types.model_package_status

        out["ModelPackageStatus"] = (
            capo_sagemaker.types.model_package_status.serialize_aws_json_1_1(
                value["model_package_status"]
            )
        )
    if "model_package_status_details" in value:
        import capo_sagemaker.types.model_package_status_details

        out["ModelPackageStatusDetails"] = (
            capo_sagemaker.types.model_package_status_details.serialize_aws_json_1_1(
                value["model_package_status_details"]
            )
        )
    if "certify_for_marketplace" in value:
        out["CertifyForMarketplace"] = value["certify_for_marketplace"]
    if "model_approval_status" in value:
        import capo_sagemaker.types.model_approval_status

        out["ModelApprovalStatus"] = (
            capo_sagemaker.types.model_approval_status.serialize_aws_json_1_1(
                value["model_approval_status"]
            )
        )
    if "created_by" in value:
        import capo_sagemaker.types.user_context

        out["CreatedBy"] = capo_sagemaker.types.user_context.serialize_aws_json_1_1(
            value["created_by"]
        )
    if "metadata_properties" in value:
        import capo_sagemaker.types.metadata_properties

        out["MetadataProperties"] = (
            capo_sagemaker.types.metadata_properties.serialize_aws_json_1_1(
                value["metadata_properties"]
            )
        )
    if "model_metrics" in value:
        import capo_sagemaker.types.model_metrics

        out["ModelMetrics"] = capo_sagemaker.types.model_metrics.serialize_aws_json_1_1(
            value["model_metrics"]
        )
    if "last_modified_time" in value:
        import capo_sagemaker.types.timestamp

        out["LastModifiedTime"] = capo_sagemaker.types.timestamp.serialize_aws_json_1_1(
            value["last_modified_time"]
        )
    if "last_modified_by" in value:
        import capo_sagemaker.types.user_context

        out["LastModifiedBy"] = (
            capo_sagemaker.types.user_context.serialize_aws_json_1_1(
                value["last_modified_by"]
            )
        )
    if "approval_description" in value:
        out["ApprovalDescription"] = value["approval_description"]
    if "domain" in value:
        out["Domain"] = value["domain"]
    if "task" in value:
        out["Task"] = value["task"]
    if "sample_payload_url" in value:
        out["SamplePayloadUrl"] = value["sample_payload_url"]
    if "additional_inference_specifications" in value:
        import capo_sagemaker.types.additional_inference_specifications

        out["AdditionalInferenceSpecifications"] = (
            capo_sagemaker.types.additional_inference_specifications.serialize_aws_json_1_1(
                value["additional_inference_specifications"]
            )
        )
    if "source_uri" in value:
        out["SourceUri"] = value["source_uri"]
    if "security_config" in value:
        import capo_sagemaker.types.model_package_security_config

        out["SecurityConfig"] = (
            capo_sagemaker.types.model_package_security_config.serialize_aws_json_1_1(
                value["security_config"]
            )
        )
    if "model_card" in value:
        import capo_sagemaker.types.model_package_model_card

        out["ModelCard"] = (
            capo_sagemaker.types.model_package_model_card.serialize_aws_json_1_1(
                value["model_card"]
            )
        )
    if "model_life_cycle" in value:
        import capo_sagemaker.types.model_life_cycle

        out["ModelLifeCycle"] = (
            capo_sagemaker.types.model_life_cycle.serialize_aws_json_1_1(
                value["model_life_cycle"]
            )
        )
    if "tags" in value:
        import capo_sagemaker.types.tag_list

        out["Tags"] = capo_sagemaker.types.tag_list.serialize_aws_json_1_1(
            value["tags"]
        )
    if "customer_metadata_properties" in value:
        import capo_sagemaker.types.customer_metadata_map

        out["CustomerMetadataProperties"] = (
            capo_sagemaker.types.customer_metadata_map.serialize_aws_json_1_1(
                value["customer_metadata_properties"]
            )
        )
    if "drift_check_baselines" in value:
        import capo_sagemaker.types.drift_check_baselines

        out["DriftCheckBaselines"] = (
            capo_sagemaker.types.drift_check_baselines.serialize_aws_json_1_1(
                value["drift_check_baselines"]
            )
        )
    if "skip_model_validation" in value:
        import capo_sagemaker.types.skip_model_validation

        out["SkipModelValidation"] = (
            capo_sagemaker.types.skip_model_validation.serialize_aws_json_1_1(
                value["skip_model_validation"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ModelPackage:
    out: ModelPackage = {}  # type: ignore[typeddict-item]
    if data.get("ModelPackageName") is not None:
        out["model_package_name"] = data["ModelPackageName"]
    if data.get("ModelPackageGroupName") is not None:
        out["model_package_group_name"] = data["ModelPackageGroupName"]
    if data.get("ModelPackageVersion") is not None:
        out["model_package_version"] = data["ModelPackageVersion"]
    if data.get("ModelPackageRegistrationType") is not None:
        import capo_sagemaker.types.model_package_registration_type

        out["model_package_registration_type"] = (
            capo_sagemaker.types.model_package_registration_type.deserialize_aws_json_1_1(
                data["ModelPackageRegistrationType"]
            )
        )
    if data.get("ModelPackageArn") is not None:
        out["model_package_arn"] = data["ModelPackageArn"]
    if data.get("ModelPackageDescription") is not None:
        out["model_package_description"] = data["ModelPackageDescription"]
    if data.get("CreationTime") is not None:
        import capo_sagemaker.types.creation_time

        out["creation_time"] = (
            capo_sagemaker.types.creation_time.deserialize_aws_json_1_1(
                data["CreationTime"]
            )
        )
    if data.get("InferenceSpecification") is not None:
        import capo_sagemaker.types.inference_specification

        out["inference_specification"] = (
            capo_sagemaker.types.inference_specification.deserialize_aws_json_1_1(
                data["InferenceSpecification"]
            )
        )
    if data.get("SourceAlgorithmSpecification") is not None:
        import capo_sagemaker.types.source_algorithm_specification

        out["source_algorithm_specification"] = (
            capo_sagemaker.types.source_algorithm_specification.deserialize_aws_json_1_1(
                data["SourceAlgorithmSpecification"]
            )
        )
    if data.get("ValidationSpecification") is not None:
        import capo_sagemaker.types.model_package_validation_specification

        out["validation_specification"] = (
            capo_sagemaker.types.model_package_validation_specification.deserialize_aws_json_1_1(
                data["ValidationSpecification"]
            )
        )
    if data.get("ModelPackageStatus") is not None:
        import capo_sagemaker.types.model_package_status

        out["model_package_status"] = (
            capo_sagemaker.types.model_package_status.deserialize_aws_json_1_1(
                data["ModelPackageStatus"]
            )
        )
    if data.get("ModelPackageStatusDetails") is not None:
        import capo_sagemaker.types.model_package_status_details

        out["model_package_status_details"] = (
            capo_sagemaker.types.model_package_status_details.deserialize_aws_json_1_1(
                data["ModelPackageStatusDetails"]
            )
        )
    if data.get("CertifyForMarketplace") is not None:
        out["certify_for_marketplace"] = data["CertifyForMarketplace"]
    if data.get("ModelApprovalStatus") is not None:
        import capo_sagemaker.types.model_approval_status

        out["model_approval_status"] = (
            capo_sagemaker.types.model_approval_status.deserialize_aws_json_1_1(
                data["ModelApprovalStatus"]
            )
        )
    if data.get("CreatedBy") is not None:
        import capo_sagemaker.types.user_context

        out["created_by"] = capo_sagemaker.types.user_context.deserialize_aws_json_1_1(
            data["CreatedBy"]
        )
    if data.get("MetadataProperties") is not None:
        import capo_sagemaker.types.metadata_properties

        out["metadata_properties"] = (
            capo_sagemaker.types.metadata_properties.deserialize_aws_json_1_1(
                data["MetadataProperties"]
            )
        )
    if data.get("ModelMetrics") is not None:
        import capo_sagemaker.types.model_metrics

        out["model_metrics"] = (
            capo_sagemaker.types.model_metrics.deserialize_aws_json_1_1(
                data["ModelMetrics"]
            )
        )
    if data.get("LastModifiedTime") is not None:
        import capo_sagemaker.types.timestamp

        out["last_modified_time"] = (
            capo_sagemaker.types.timestamp.deserialize_aws_json_1_1(
                data["LastModifiedTime"]
            )
        )
    if data.get("LastModifiedBy") is not None:
        import capo_sagemaker.types.user_context

        out["last_modified_by"] = (
            capo_sagemaker.types.user_context.deserialize_aws_json_1_1(
                data["LastModifiedBy"]
            )
        )
    if data.get("ApprovalDescription") is not None:
        out["approval_description"] = data["ApprovalDescription"]
    if data.get("Domain") is not None:
        out["domain"] = data["Domain"]
    if data.get("Task") is not None:
        out["task"] = data["Task"]
    if data.get("SamplePayloadUrl") is not None:
        out["sample_payload_url"] = data["SamplePayloadUrl"]
    if data.get("AdditionalInferenceSpecifications") is not None:
        import capo_sagemaker.types.additional_inference_specifications

        out["additional_inference_specifications"] = (
            capo_sagemaker.types.additional_inference_specifications.deserialize_aws_json_1_1(
                data["AdditionalInferenceSpecifications"]
            )
        )
    if data.get("SourceUri") is not None:
        out["source_uri"] = data["SourceUri"]
    if data.get("SecurityConfig") is not None:
        import capo_sagemaker.types.model_package_security_config

        out["security_config"] = (
            capo_sagemaker.types.model_package_security_config.deserialize_aws_json_1_1(
                data["SecurityConfig"]
            )
        )
    if data.get("ModelCard") is not None:
        import capo_sagemaker.types.model_package_model_card

        out["model_card"] = (
            capo_sagemaker.types.model_package_model_card.deserialize_aws_json_1_1(
                data["ModelCard"]
            )
        )
    if data.get("ModelLifeCycle") is not None:
        import capo_sagemaker.types.model_life_cycle

        out["model_life_cycle"] = (
            capo_sagemaker.types.model_life_cycle.deserialize_aws_json_1_1(
                data["ModelLifeCycle"]
            )
        )
    if data.get("Tags") is not None:
        import capo_sagemaker.types.tag_list

        out["tags"] = capo_sagemaker.types.tag_list.deserialize_aws_json_1_1(
            data["Tags"]
        )
    if data.get("CustomerMetadataProperties") is not None:
        import capo_sagemaker.types.customer_metadata_map

        out["customer_metadata_properties"] = (
            capo_sagemaker.types.customer_metadata_map.deserialize_aws_json_1_1(
                data["CustomerMetadataProperties"]
            )
        )
    if data.get("DriftCheckBaselines") is not None:
        import capo_sagemaker.types.drift_check_baselines

        out["drift_check_baselines"] = (
            capo_sagemaker.types.drift_check_baselines.deserialize_aws_json_1_1(
                data["DriftCheckBaselines"]
            )
        )
    if data.get("SkipModelValidation") is not None:
        import capo_sagemaker.types.skip_model_validation

        out["skip_model_validation"] = (
            capo_sagemaker.types.skip_model_validation.deserialize_aws_json_1_1(
                data["SkipModelValidation"]
            )
        )
    return out
