"""Generated from Smithy shape ``com.amazonaws.iotmanagedintegrations#SendConnectorEventRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_iot_managed_integrations.errors import DeserializationError

if TYPE_CHECKING:
    import capo_iot_managed_integrations.types.connector_device_id
    import capo_iot_managed_integrations.types.connector_event_message
    import capo_iot_managed_integrations.types.connector_event_operation
    import capo_iot_managed_integrations.types.connector_event_operation_version
    import capo_iot_managed_integrations.types.connector_event_status_code
    import capo_iot_managed_integrations.types.connector_id
    import capo_iot_managed_integrations.types.device_discovery_id
    import capo_iot_managed_integrations.types.devices
    import capo_iot_managed_integrations.types.matter_endpoint
    import capo_iot_managed_integrations.types.third_party_user_id
    import capo_iot_managed_integrations.types.trace_id


class SendConnectorEventRequest(TypedDict, closed=True):
    connector_id: "capo_iot_managed_integrations.types.connector_id.ConnectorId"
    """<p>The id of the connector between the third-party cloud provider and IoT managed integrations.</p>"""
    user_id: NotRequired[
        "capo_iot_managed_integrations.types.third_party_user_id.ThirdPartyUserId"
    ]
    """<p>The id of the third-party cloud provider.</p>"""
    operation: "capo_iot_managed_integrations.types.connector_event_operation.ConnectorEventOperation"
    """<p>The Open Connectivity Foundation (OCF) operation requested to be performed on the managed thing.</p> <note> <p>The field op can have a value of "I" or "U". The field "cn" will contain the capability types.</p> </note>"""
    operation_version: NotRequired[
        "capo_iot_managed_integrations.types.connector_event_operation_version.ConnectorEventOperationVersion"
    ]
    """<p>The Open Connectivity Foundation (OCF) security specification version for the operation being requested on the managed thing. For more information, see <a href="https://openconnectivity.org/specs/OCF_Security_Specification_v1.0.0.pdf">OCF Security Specification</a>.</p>"""
    status_code: NotRequired[
        "capo_iot_managed_integrations.types.connector_event_status_code.ConnectorEventStatusCode"
    ]
    """<p>The status code of the Open Connectivity Foundation (OCF) operation being performed on the managed thing.</p>"""
    message: NotRequired[
        "capo_iot_managed_integrations.types.connector_event_message.ConnectorEventMessage"
    ]
    """<p>The device state change event payload.</p> <p>This parameter will include the following three fields:</p> <ul> <li> <p> <code>uri</code>: <code>schema auc://&lt;PARTNER-DEVICE-ID&gt;/ResourcePath</code> (The <code>Resourcepath</code> corresponds to an OCF resource.)</p> </li> <li> <p> <code>op</code>: For device state changes, this field must populate as <code>n+d</code>.</p> </li> <li> <p> <code>cn</code>: The content depends on the OCF resource referenced in <code>ResourcePath</code>.</p> </li> </ul>"""
    device_discovery_id: NotRequired[
        "capo_iot_managed_integrations.types.device_discovery_id.DeviceDiscoveryId"
    ]
    """<p>The id for the device discovery job.</p>"""
    connector_device_id: NotRequired[
        "capo_iot_managed_integrations.types.connector_device_id.ConnectorDeviceId"
    ]
    """<p>The third-party device id as defined by the connector. This device id must not contain personal identifiable information (PII).</p> <note> <p>This parameter is used for cloud-to-cloud devices only.</p> </note>"""
    trace_id: NotRequired["capo_iot_managed_integrations.types.trace_id.TraceId"]
    """<p>The trace request identifier. This is generated by IoT managed integrations and can be used to trace this command and its related operations in CloudWatch.</p>"""
    devices: NotRequired["capo_iot_managed_integrations.types.devices.Devices"]
    """<p>The list of devices.</p>"""
    matter_endpoint: NotRequired[
        "capo_iot_managed_integrations.types.matter_endpoint.MatterEndpoint"
    ]
    """<p>The device endpoint.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: SendConnectorEventRequest) -> dict:
    out: dict = {}
    if "user_id" in value:
        out["UserId"] = value["user_id"]
    import capo_iot_managed_integrations.types.connector_event_operation

    out["Operation"] = (
        capo_iot_managed_integrations.types.connector_event_operation.serialize_json(
            value["operation"]
        )
    )
    if "operation_version" in value:
        out["OperationVersion"] = value["operation_version"]
    if "status_code" in value:
        out["StatusCode"] = value["status_code"]
    if "message" in value:
        out["Message"] = value["message"]
    if "device_discovery_id" in value:
        out["DeviceDiscoveryId"] = value["device_discovery_id"]
    if "connector_device_id" in value:
        out["ConnectorDeviceId"] = value["connector_device_id"]
    if "trace_id" in value:
        out["TraceId"] = value["trace_id"]
    if "devices" in value:
        import capo_iot_managed_integrations.types.devices

        out["Devices"] = capo_iot_managed_integrations.types.devices.serialize_json(
            value["devices"]
        )
    if "matter_endpoint" in value:
        import capo_iot_managed_integrations.types.matter_endpoint

        out["MatterEndpoint"] = (
            capo_iot_managed_integrations.types.matter_endpoint.serialize_json(
                value["matter_endpoint"]
            )
        )
    return out


def deserialize_json(data: dict) -> SendConnectorEventRequest:
    out: SendConnectorEventRequest = {}  # type: ignore[typeddict-item]
    if data.get("UserId") is not None:
        out["user_id"] = data["UserId"]
    if data.get("Operation") is not None:
        import capo_iot_managed_integrations.types.connector_event_operation

        out["operation"] = (
            capo_iot_managed_integrations.types.connector_event_operation.deserialize_json(
                data["Operation"]
            )
        )
    else:
        raise DeserializationError("SendConnectorEventRequest.operation required")
    if data.get("OperationVersion") is not None:
        out["operation_version"] = data["OperationVersion"]
    if data.get("StatusCode") is not None:
        out["status_code"] = data["StatusCode"]
    if data.get("Message") is not None:
        out["message"] = data["Message"]
    if data.get("DeviceDiscoveryId") is not None:
        out["device_discovery_id"] = data["DeviceDiscoveryId"]
    if data.get("ConnectorDeviceId") is not None:
        out["connector_device_id"] = data["ConnectorDeviceId"]
    if data.get("TraceId") is not None:
        out["trace_id"] = data["TraceId"]
    if data.get("Devices") is not None:
        import capo_iot_managed_integrations.types.devices

        out["devices"] = capo_iot_managed_integrations.types.devices.deserialize_json(
            data["Devices"]
        )
    if data.get("MatterEndpoint") is not None:
        import capo_iot_managed_integrations.types.matter_endpoint

        out["matter_endpoint"] = (
            capo_iot_managed_integrations.types.matter_endpoint.deserialize_json(
                data["MatterEndpoint"]
            )
        )
    return out
