"""Generated from Smithy shape ``com.amazonaws.swf#RecordMarkerFailedEventAttributes``."""

from typing import TYPE_CHECKING

from typing_extensions import TypedDict

from capo_swf.errors import DeserializationError

if TYPE_CHECKING:
    import capo_swf.types.event_id
    import capo_swf.types.marker_name
    import capo_swf.types.record_marker_failed_cause


class RecordMarkerFailedEventAttributes(TypedDict, closed=True):
    marker_name: "capo_swf.types.marker_name.MarkerName"
    """<p>The marker's name.</p>"""
    cause: "capo_swf.types.record_marker_failed_cause.RecordMarkerFailedCause"
    """<p>The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.</p> <note> <p>If <code>cause</code> is set to <code>OPERATION_NOT_PERMITTED</code>, the decision failed because it lacked sufficient permissions. For details and example IAM policies, see <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html">Using IAM to Manage Access to Amazon SWF Workflows</a> in the <i>Amazon SWF Developer Guide</i>.</p> </note>"""
    decision_task_completed_event_id: "capo_swf.types.event_id.EventId"
    """<p>The ID of the <code>DecisionTaskCompleted</code> event corresponding to the decision task that resulted in the <code>RecordMarkerFailed</code> decision for this cancellation request. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: RecordMarkerFailedEventAttributes) -> dict:
    out: dict = {}
    out["markerName"] = value["marker_name"]
    import capo_swf.types.record_marker_failed_cause

    out["cause"] = capo_swf.types.record_marker_failed_cause.serialize_aws_json_1_0(
        value["cause"]
    )
    out["decisionTaskCompletedEventId"] = value.get(
        "decision_task_completed_event_id", 0
    )
    return out


def deserialize_aws_json_1_0(data: dict) -> RecordMarkerFailedEventAttributes:
    out: RecordMarkerFailedEventAttributes = {}  # type: ignore[typeddict-item]
    if data.get("markerName") is not None:
        out["marker_name"] = data["markerName"]
    else:
        raise DeserializationError(
            "RecordMarkerFailedEventAttributes.marker_name required"
        )
    if data.get("cause") is not None:
        import capo_swf.types.record_marker_failed_cause

        out["cause"] = (
            capo_swf.types.record_marker_failed_cause.deserialize_aws_json_1_0(
                data["cause"]
            )
        )
    else:
        raise DeserializationError("RecordMarkerFailedEventAttributes.cause required")
    if data.get("decisionTaskCompletedEventId") is not None:
        out["decision_task_completed_event_id"] = data["decisionTaskCompletedEventId"]
    else:
        out["decision_task_completed_event_id"] = 0
    return out
