"""Generated from Smithy shape ``com.amazonaws.swf#ScheduleActivityTaskFailedEventAttributes``."""

from typing import TYPE_CHECKING

from typing_extensions import TypedDict

from capo_swf.errors import DeserializationError

if TYPE_CHECKING:
    import capo_swf.types.activity_id
    import capo_swf.types.activity_type
    import capo_swf.types.event_id
    import capo_swf.types.schedule_activity_task_failed_cause


class ScheduleActivityTaskFailedEventAttributes(TypedDict, closed=True):
    activity_type: "capo_swf.types.activity_type.ActivityType"
    """<p>The activity type provided in the <code>ScheduleActivityTask</code> decision that failed.</p>"""
    activity_id: "capo_swf.types.activity_id.ActivityId"
    """<p>The activityId provided in the <code>ScheduleActivityTask</code> decision that failed.</p>"""
    cause: "capo_swf.types.schedule_activity_task_failed_cause.ScheduleActivityTaskFailedCause"
    """<p>The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.</p> <note> <p>If <code>cause</code> is set to <code>OPERATION_NOT_PERMITTED</code>, the decision failed because it lacked sufficient permissions. For details and example IAM policies, see <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html">Using IAM to Manage Access to Amazon SWF Workflows</a> in the <i>Amazon SWF Developer Guide</i>.</p> </note>"""
    decision_task_completed_event_id: "capo_swf.types.event_id.EventId"
    """<p>The ID of the <code>DecisionTaskCompleted</code> event corresponding to the decision that resulted in the scheduling of this activity task. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: ScheduleActivityTaskFailedEventAttributes) -> dict:
    out: dict = {}
    import capo_swf.types.activity_type

    out["activityType"] = capo_swf.types.activity_type.serialize_aws_json_1_0(
        value["activity_type"]
    )
    out["activityId"] = value["activity_id"]
    import capo_swf.types.schedule_activity_task_failed_cause

    out["cause"] = (
        capo_swf.types.schedule_activity_task_failed_cause.serialize_aws_json_1_0(
            value["cause"]
        )
    )
    out["decisionTaskCompletedEventId"] = value.get(
        "decision_task_completed_event_id", 0
    )
    return out


def deserialize_aws_json_1_0(data: dict) -> ScheduleActivityTaskFailedEventAttributes:
    out: ScheduleActivityTaskFailedEventAttributes = {}  # type: ignore[typeddict-item]
    if data.get("activityType") is not None:
        import capo_swf.types.activity_type

        out["activity_type"] = capo_swf.types.activity_type.deserialize_aws_json_1_0(
            data["activityType"]
        )
    else:
        raise DeserializationError(
            "ScheduleActivityTaskFailedEventAttributes.activity_type required"
        )
    if data.get("activityId") is not None:
        out["activity_id"] = data["activityId"]
    else:
        raise DeserializationError(
            "ScheduleActivityTaskFailedEventAttributes.activity_id required"
        )
    if data.get("cause") is not None:
        import capo_swf.types.schedule_activity_task_failed_cause

        out["cause"] = (
            capo_swf.types.schedule_activity_task_failed_cause.deserialize_aws_json_1_0(
                data["cause"]
            )
        )
    else:
        raise DeserializationError(
            "ScheduleActivityTaskFailedEventAttributes.cause required"
        )
    if data.get("decisionTaskCompletedEventId") is not None:
        out["decision_task_completed_event_id"] = data["decisionTaskCompletedEventId"]
    else:
        out["decision_task_completed_event_id"] = 0
    return out
