"""Generated from Smithy shape ``com.amazonaws.swf#SignalExternalWorkflowExecutionFailedEventAttributes``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_swf.errors import DeserializationError

if TYPE_CHECKING:
    import capo_swf.types.data
    import capo_swf.types.event_id
    import capo_swf.types.signal_external_workflow_execution_failed_cause
    import capo_swf.types.workflow_id
    import capo_swf.types.workflow_run_id_optional


class SignalExternalWorkflowExecutionFailedEventAttributes(TypedDict, closed=True):
    workflow_id: "capo_swf.types.workflow_id.WorkflowId"
    """<p>The <code>workflowId</code> of the external workflow execution that the signal was being delivered to.</p>"""
    run_id: NotRequired["capo_swf.types.workflow_run_id_optional.WorkflowRunIdOptional"]
    """<p>The <code>runId</code> of the external workflow execution that the signal was being delivered to.</p>"""
    cause: "capo_swf.types.signal_external_workflow_execution_failed_cause.SignalExternalWorkflowExecutionFailedCause"
    """<p>The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.</p> <note> <p>If <code>cause</code> is set to <code>OPERATION_NOT_PERMITTED</code>, the decision failed because it lacked sufficient permissions. For details and example IAM policies, see <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html">Using IAM to Manage Access to Amazon SWF Workflows</a> in the <i>Amazon SWF Developer Guide</i>.</p> </note>"""
    initiated_event_id: "capo_swf.types.event_id.EventId"
    """<p>The ID of the <code>SignalExternalWorkflowExecutionInitiated</code> event corresponding to the <code>SignalExternalWorkflowExecution</code> decision to request this signal. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.</p>"""
    decision_task_completed_event_id: "capo_swf.types.event_id.EventId"
    """<p>The ID of the <code>DecisionTaskCompleted</code> event corresponding to the decision task that resulted in the <code>SignalExternalWorkflowExecution</code> decision for this signal. This information can be useful for diagnosing problems by tracing back the chain of events leading up to this event.</p>"""
    control: NotRequired["capo_swf.types.data.Data"]
    """<p>The data attached to the event that the decider can use in subsequent workflow tasks. This data isn't sent to the workflow execution.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(
    value: SignalExternalWorkflowExecutionFailedEventAttributes,
) -> dict:
    out: dict = {}
    out["workflowId"] = value["workflow_id"]
    if "run_id" in value:
        out["runId"] = value["run_id"]
    import capo_swf.types.signal_external_workflow_execution_failed_cause

    out["cause"] = (
        capo_swf.types.signal_external_workflow_execution_failed_cause.serialize_aws_json_1_0(
            value["cause"]
        )
    )
    out["initiatedEventId"] = value.get("initiated_event_id", 0)
    out["decisionTaskCompletedEventId"] = value.get(
        "decision_task_completed_event_id", 0
    )
    if "control" in value:
        out["control"] = value["control"]
    return out


def deserialize_aws_json_1_0(
    data: dict,
) -> SignalExternalWorkflowExecutionFailedEventAttributes:
    out: SignalExternalWorkflowExecutionFailedEventAttributes = {}  # type: ignore[typeddict-item]
    if data.get("workflowId") is not None:
        out["workflow_id"] = data["workflowId"]
    else:
        raise DeserializationError(
            "SignalExternalWorkflowExecutionFailedEventAttributes.workflow_id required"
        )
    if data.get("runId") is not None:
        out["run_id"] = data["runId"]
    if data.get("cause") is not None:
        import capo_swf.types.signal_external_workflow_execution_failed_cause

        out["cause"] = (
            capo_swf.types.signal_external_workflow_execution_failed_cause.deserialize_aws_json_1_0(
                data["cause"]
            )
        )
    else:
        raise DeserializationError(
            "SignalExternalWorkflowExecutionFailedEventAttributes.cause required"
        )
    if data.get("initiatedEventId") is not None:
        out["initiated_event_id"] = data["initiatedEventId"]
    else:
        out["initiated_event_id"] = 0
    if data.get("decisionTaskCompletedEventId") is not None:
        out["decision_task_completed_event_id"] = data["decisionTaskCompletedEventId"]
    else:
        out["decision_task_completed_event_id"] = 0
    if data.get("control") is not None:
        out["control"] = data["control"]
    return out
