"""Generated from Smithy shape ``com.amazonaws.swf#StartChildWorkflowExecutionFailedEventAttributes``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_swf.errors import DeserializationError

if TYPE_CHECKING:
    import capo_swf.types.data
    import capo_swf.types.event_id
    import capo_swf.types.start_child_workflow_execution_failed_cause
    import capo_swf.types.workflow_id
    import capo_swf.types.workflow_type


class StartChildWorkflowExecutionFailedEventAttributes(TypedDict, closed=True):
    workflow_type: "capo_swf.types.workflow_type.WorkflowType"
    """<p>The workflow type provided in the <code>StartChildWorkflowExecution</code> <a>Decision</a> that failed.</p>"""
    cause: "capo_swf.types.start_child_workflow_execution_failed_cause.StartChildWorkflowExecutionFailedCause"
    """<p>The cause of the failure. This information is generated by the system and can be useful for diagnostic purposes.</p> <note> <p>When <code>cause</code> is set to <code>OPERATION_NOT_PERMITTED</code>, the decision fails because it lacks sufficient permissions. For details and example IAM policies, see <a href="https://docs.aws.amazon.com/amazonswf/latest/developerguide/swf-dev-iam.html"> Using IAM to Manage Access to Amazon SWF Workflows</a> in the <i>Amazon SWF Developer Guide</i>.</p> </note>"""
    workflow_id: "capo_swf.types.workflow_id.WorkflowId"
    """<p>The <code>workflowId</code> of the child workflow execution.</p>"""
    initiated_event_id: "capo_swf.types.event_id.EventId"
    """<p>When the <code>cause</code> is <code>WORKFLOW_ALREADY_RUNNING</code>, <code>initiatedEventId</code> is the ID of the <code>StartChildWorkflowExecutionInitiated</code> event that corresponds to the <code>StartChildWorkflowExecution</code> <a>Decision</a> to start the workflow execution. You can use this information to diagnose problems by tracing back the chain of events leading up to this event.</p> <p>When the <code>cause</code> isn't <code>WORKFLOW_ALREADY_RUNNING</code>, <code>initiatedEventId</code> is set to <code>0</code> because the <code>StartChildWorkflowExecutionInitiated</code> event doesn't exist.</p>"""
    decision_task_completed_event_id: "capo_swf.types.event_id.EventId"
    """<p>The ID of the <code>DecisionTaskCompleted</code> event corresponding to the decision task that resulted in the <code>StartChildWorkflowExecution</code> <a>Decision</a> to request this child workflow execution. This information can be useful for diagnosing problems by tracing back the chain of events.</p>"""
    control: NotRequired["capo_swf.types.data.Data"]
    """<p>The data attached to the event that the decider can use in subsequent workflow tasks. This data isn't sent to the child workflow execution.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(
    value: StartChildWorkflowExecutionFailedEventAttributes,
) -> dict:
    out: dict = {}
    import capo_swf.types.workflow_type

    out["workflowType"] = capo_swf.types.workflow_type.serialize_aws_json_1_0(
        value["workflow_type"]
    )
    import capo_swf.types.start_child_workflow_execution_failed_cause

    out["cause"] = (
        capo_swf.types.start_child_workflow_execution_failed_cause.serialize_aws_json_1_0(
            value["cause"]
        )
    )
    out["workflowId"] = value["workflow_id"]
    out["initiatedEventId"] = value.get("initiated_event_id", 0)
    out["decisionTaskCompletedEventId"] = value.get(
        "decision_task_completed_event_id", 0
    )
    if "control" in value:
        out["control"] = value["control"]
    return out


def deserialize_aws_json_1_0(
    data: dict,
) -> StartChildWorkflowExecutionFailedEventAttributes:
    out: StartChildWorkflowExecutionFailedEventAttributes = {}  # type: ignore[typeddict-item]
    if data.get("workflowType") is not None:
        import capo_swf.types.workflow_type

        out["workflow_type"] = capo_swf.types.workflow_type.deserialize_aws_json_1_0(
            data["workflowType"]
        )
    else:
        raise DeserializationError(
            "StartChildWorkflowExecutionFailedEventAttributes.workflow_type required"
        )
    if data.get("cause") is not None:
        import capo_swf.types.start_child_workflow_execution_failed_cause

        out["cause"] = (
            capo_swf.types.start_child_workflow_execution_failed_cause.deserialize_aws_json_1_0(
                data["cause"]
            )
        )
    else:
        raise DeserializationError(
            "StartChildWorkflowExecutionFailedEventAttributes.cause required"
        )
    if data.get("workflowId") is not None:
        out["workflow_id"] = data["workflowId"]
    else:
        raise DeserializationError(
            "StartChildWorkflowExecutionFailedEventAttributes.workflow_id required"
        )
    if data.get("initiatedEventId") is not None:
        out["initiated_event_id"] = data["initiatedEventId"]
    else:
        out["initiated_event_id"] = 0
    if data.get("decisionTaskCompletedEventId") is not None:
        out["decision_task_completed_event_id"] = data["decisionTaskCompletedEventId"]
    else:
        out["decision_task_completed_event_id"] = 0
    if data.get("control") is not None:
        out["control"] = data["control"]
    return out
