"""Generated from Smithy shape ``com.amazonaws.glue#MLTransform``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_glue.types.description_string
    import capo_glue.types.evaluation_metrics
    import capo_glue.types.glue_tables
    import capo_glue.types.glue_version_string
    import capo_glue.types.hash_string
    import capo_glue.types.label_count
    import capo_glue.types.name_string
    import capo_glue.types.nullable_double
    import capo_glue.types.nullable_integer
    import capo_glue.types.role_string
    import capo_glue.types.timeout
    import capo_glue.types.timestamp
    import capo_glue.types.transform_encryption
    import capo_glue.types.transform_parameters
    import capo_glue.types.transform_schema
    import capo_glue.types.transform_status_type
    import capo_glue.types.worker_type


class MLTransform(TypedDict, closed=True):
    transform_id: NotRequired["capo_glue.types.hash_string.HashString"]
    """<p>The unique transform ID that is generated for the machine learning transform. The ID is guaranteed to be unique and does not change.</p>"""
    name: NotRequired["capo_glue.types.name_string.NameString"]
    """<p>A user-defined name for the machine learning transform. Names are not guaranteed unique and can be changed at any time.</p>"""
    description: NotRequired["capo_glue.types.description_string.DescriptionString"]
    """<p>A user-defined, long-form description text for the machine learning transform. Descriptions are not guaranteed to be unique and can be changed at any time.</p>"""
    status: NotRequired["capo_glue.types.transform_status_type.TransformStatusType"]
    """<p>The current status of the machine learning transform.</p>"""
    created_on: NotRequired["capo_glue.types.timestamp.Timestamp"]
    """<p>A timestamp. The time and date that this machine learning transform was created.</p>"""
    last_modified_on: NotRequired["capo_glue.types.timestamp.Timestamp"]
    """<p>A timestamp. The last point in time when this machine learning transform was modified.</p>"""
    input_record_tables: NotRequired["capo_glue.types.glue_tables.GlueTables"]
    """<p>A list of Glue table definitions used by the transform.</p>"""
    parameters: NotRequired["capo_glue.types.transform_parameters.TransformParameters"]
    """<p>A <code>TransformParameters</code> object. You can use parameters to tune (customize) the behavior of the machine learning transform by specifying what data it learns from and your preference on various tradeoffs (such as precious vs. recall, or accuracy vs. cost).</p>"""
    evaluation_metrics: NotRequired[
        "capo_glue.types.evaluation_metrics.EvaluationMetrics"
    ]
    """<p>An <code>EvaluationMetrics</code> object. Evaluation metrics provide an estimate of the quality of your machine learning transform.</p>"""
    label_count: "capo_glue.types.label_count.LabelCount"
    """<p>A count identifier for the labeling files generated by Glue for this transform. As you create a better transform, you can iteratively download, label, and upload the labeling file.</p>"""
    schema: NotRequired["capo_glue.types.transform_schema.TransformSchema"]
    """<p>A map of key-value pairs representing the columns and data types that this transform can run against. Has an upper bound of 100 columns.</p>"""
    role: NotRequired["capo_glue.types.role_string.RoleString"]
    """<p>The name or Amazon Resource Name (ARN) of the IAM role with the required permissions. The required permissions include both Glue service role permissions to Glue resources, and Amazon S3 permissions required by the transform. </p> <ul> <li> <p>This role needs Glue service role permissions to allow access to resources in Glue. See <a href="https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html">Attach a Policy to IAM Users That Access Glue</a>.</p> </li> <li> <p>This role needs permission to your Amazon Simple Storage Service (Amazon S3) sources, targets, temporary directory, scripts, and any libraries used by the task run for this transform.</p> </li> </ul>"""
    glue_version: NotRequired["capo_glue.types.glue_version_string.GlueVersionString"]
    """<p>This value determines which version of Glue this machine learning transform is compatible with. Glue 1.0 is recommended for most customers. If the value is not set, the Glue compatibility defaults to Glue 0.9. For more information, see <a href="https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions">Glue Versions</a> in the developer guide.</p>"""
    max_capacity: NotRequired["capo_glue.types.nullable_double.NullableDouble"]
    """<p>The number of Glue data processing units (DPUs) that are allocated to task runs for this transform. You can allocate from 2 to 100 DPUs; the default is 10. A DPU is a relative measure of processing power that consists of 4 vCPUs of compute capacity and 16 GB of memory. For more information, see the <a href="http://aws.amazon.com/glue/pricing/">Glue pricing page</a>. </p> <p> <code>MaxCapacity</code> is a mutually exclusive option with <code>NumberOfWorkers</code> and <code>WorkerType</code>.</p> <ul> <li> <p>If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set, then <code>MaxCapacity</code> cannot be set.</p> </li> <li> <p>If <code>MaxCapacity</code> is set then neither <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.</p> </li> <li> <p>If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is required (and vice versa).</p> </li> <li> <p> <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at least 1.</p> </li> </ul> <p>When the <code>WorkerType</code> field is set to a value other than <code>Standard</code>, the <code>MaxCapacity</code> field is set automatically and becomes read-only.</p>"""
    worker_type: NotRequired["capo_glue.types.worker_type.WorkerType"]
    """<p>The type of predefined worker that is allocated when a task of this transform runs. Accepts a value of Standard, G.1X, or G.2X.</p> <ul> <li> <p>For the <code>Standard</code> worker type, each worker provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2 executors per worker.</p> </li> <li> <p>For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB of memory and a 64GB disk, and 1 executor per worker.</p> </li> <li> <p>For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB of memory and a 128GB disk, and 1 executor per worker.</p> </li> </ul> <p> <code>MaxCapacity</code> is a mutually exclusive option with <code>NumberOfWorkers</code> and <code>WorkerType</code>.</p> <ul> <li> <p>If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set, then <code>MaxCapacity</code> cannot be set.</p> </li> <li> <p>If <code>MaxCapacity</code> is set then neither <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.</p> </li> <li> <p>If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is required (and vice versa).</p> </li> <li> <p> <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at least 1.</p> </li> </ul>"""
    number_of_workers: NotRequired["capo_glue.types.nullable_integer.NullableInteger"]
    """<p>The number of workers of a defined <code>workerType</code> that are allocated when a task of the transform runs.</p> <p>If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is required (and vice versa).</p>"""
    timeout: NotRequired["capo_glue.types.timeout.Timeout"]
    """<p>The timeout in minutes of the machine learning transform.</p>"""
    max_retries: NotRequired["capo_glue.types.nullable_integer.NullableInteger"]
    """<p>The maximum number of times to retry after an <code>MLTaskRun</code> of the machine learning transform fails.</p>"""
    transform_encryption: NotRequired[
        "capo_glue.types.transform_encryption.TransformEncryption"
    ]
    """<p>The encryption-at-rest settings of the transform that apply to accessing user data. Machine learning transforms can access user data encrypted in Amazon S3 using KMS.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: MLTransform) -> dict:
    out: dict = {}
    if "transform_id" in value:
        out["TransformId"] = value["transform_id"]
    if "name" in value:
        out["Name"] = value["name"]
    if "description" in value:
        out["Description"] = value["description"]
    if "status" in value:
        import capo_glue.types.transform_status_type

        out["Status"] = capo_glue.types.transform_status_type.serialize_aws_json_1_1(
            value["status"]
        )
    if "created_on" in value:
        import capo_glue.types.timestamp

        out["CreatedOn"] = capo_glue.types.timestamp.serialize_aws_json_1_1(
            value["created_on"]
        )
    if "last_modified_on" in value:
        import capo_glue.types.timestamp

        out["LastModifiedOn"] = capo_glue.types.timestamp.serialize_aws_json_1_1(
            value["last_modified_on"]
        )
    if "input_record_tables" in value:
        import capo_glue.types.glue_tables

        out["InputRecordTables"] = capo_glue.types.glue_tables.serialize_aws_json_1_1(
            value["input_record_tables"]
        )
    if "parameters" in value:
        import capo_glue.types.transform_parameters

        out["Parameters"] = capo_glue.types.transform_parameters.serialize_aws_json_1_1(
            value["parameters"]
        )
    if "evaluation_metrics" in value:
        import capo_glue.types.evaluation_metrics

        out["EvaluationMetrics"] = (
            capo_glue.types.evaluation_metrics.serialize_aws_json_1_1(
                value["evaluation_metrics"]
            )
        )
    out["LabelCount"] = value.get("label_count", 0)
    if "schema" in value:
        import capo_glue.types.transform_schema

        out["Schema"] = capo_glue.types.transform_schema.serialize_aws_json_1_1(
            value["schema"]
        )
    if "role" in value:
        out["Role"] = value["role"]
    if "glue_version" in value:
        out["GlueVersion"] = value["glue_version"]
    if "max_capacity" in value:
        out["MaxCapacity"] = (
            "NaN"
            if value["max_capacity"] != value["max_capacity"]
            else "Infinity"
            if value["max_capacity"] == float("inf")
            else "-Infinity"
            if value["max_capacity"] == float("-inf")
            else value["max_capacity"]
        )
    if "worker_type" in value:
        import capo_glue.types.worker_type

        out["WorkerType"] = capo_glue.types.worker_type.serialize_aws_json_1_1(
            value["worker_type"]
        )
    if "number_of_workers" in value:
        out["NumberOfWorkers"] = value["number_of_workers"]
    if "timeout" in value:
        out["Timeout"] = value["timeout"]
    if "max_retries" in value:
        out["MaxRetries"] = value["max_retries"]
    if "transform_encryption" in value:
        import capo_glue.types.transform_encryption

        out["TransformEncryption"] = (
            capo_glue.types.transform_encryption.serialize_aws_json_1_1(
                value["transform_encryption"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> MLTransform:
    out: MLTransform = {}  # type: ignore[typeddict-item]
    if data.get("TransformId") is not None:
        out["transform_id"] = data["TransformId"]
    if data.get("Name") is not None:
        out["name"] = data["Name"]
    if data.get("Description") is not None:
        out["description"] = data["Description"]
    if data.get("Status") is not None:
        import capo_glue.types.transform_status_type

        out["status"] = capo_glue.types.transform_status_type.deserialize_aws_json_1_1(
            data["Status"]
        )
    if data.get("CreatedOn") is not None:
        import capo_glue.types.timestamp

        out["created_on"] = capo_glue.types.timestamp.deserialize_aws_json_1_1(
            data["CreatedOn"]
        )
    if data.get("LastModifiedOn") is not None:
        import capo_glue.types.timestamp

        out["last_modified_on"] = capo_glue.types.timestamp.deserialize_aws_json_1_1(
            data["LastModifiedOn"]
        )
    if data.get("InputRecordTables") is not None:
        import capo_glue.types.glue_tables

        out["input_record_tables"] = (
            capo_glue.types.glue_tables.deserialize_aws_json_1_1(
                data["InputRecordTables"]
            )
        )
    if data.get("Parameters") is not None:
        import capo_glue.types.transform_parameters

        out["parameters"] = (
            capo_glue.types.transform_parameters.deserialize_aws_json_1_1(
                data["Parameters"]
            )
        )
    if data.get("EvaluationMetrics") is not None:
        import capo_glue.types.evaluation_metrics

        out["evaluation_metrics"] = (
            capo_glue.types.evaluation_metrics.deserialize_aws_json_1_1(
                data["EvaluationMetrics"]
            )
        )
    if data.get("LabelCount") is not None:
        out["label_count"] = data["LabelCount"]
    else:
        out["label_count"] = 0
    if data.get("Schema") is not None:
        import capo_glue.types.transform_schema

        out["schema"] = capo_glue.types.transform_schema.deserialize_aws_json_1_1(
            data["Schema"]
        )
    if data.get("Role") is not None:
        out["role"] = data["Role"]
    if data.get("GlueVersion") is not None:
        out["glue_version"] = data["GlueVersion"]
    if data.get("MaxCapacity") is not None:
        out["max_capacity"] = float(data["MaxCapacity"])
    if data.get("WorkerType") is not None:
        import capo_glue.types.worker_type

        out["worker_type"] = capo_glue.types.worker_type.deserialize_aws_json_1_1(
            data["WorkerType"]
        )
    if data.get("NumberOfWorkers") is not None:
        out["number_of_workers"] = data["NumberOfWorkers"]
    if data.get("Timeout") is not None:
        out["timeout"] = data["Timeout"]
    if data.get("MaxRetries") is not None:
        out["max_retries"] = data["MaxRetries"]
    if data.get("TransformEncryption") is not None:
        import capo_glue.types.transform_encryption

        out["transform_encryption"] = (
            capo_glue.types.transform_encryption.deserialize_aws_json_1_1(
                data["TransformEncryption"]
            )
        )
    return out
