"""Generated from Smithy shape ``com.amazonaws.databasemigrationservice#CreateEventSubscriptionMessage``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_database_migration_service.errors import DeserializationError

if TYPE_CHECKING:
    import capo_database_migration_service.types.boolean_optional
    import capo_database_migration_service.types.event_categories_list
    import capo_database_migration_service.types.source_ids_list
    import capo_database_migration_service.types.string
    import capo_database_migration_service.types.tag_list


class CreateEventSubscriptionMessage(TypedDict, closed=True):
    subscription_name: "capo_database_migration_service.types.string.String"
    """<p>The name of the DMS event notification subscription. This name must be less than 255 characters.</p>"""
    sns_topic_arn: "capo_database_migration_service.types.string.String"
    """<p> The Amazon Resource Name (ARN) of the Amazon SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it. </p>"""
    source_type: NotRequired["capo_database_migration_service.types.string.String"]
    """<p> The type of DMS resource that generates the events. For example, if you want to be notified of events generated by a replication instance, you set this parameter to <code>replication-instance</code>. If this value isn't specified, all events are returned. </p> <p>Valid values: <code>replication-instance</code> | <code>replication-task</code> </p>"""
    event_categories: NotRequired[
        "capo_database_migration_service.types.event_categories_list.EventCategoriesList"
    ]
    """<p>A list of event categories for a source type that you want to subscribe to. For more information, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Events.html">Working with Events and Notifications</a> in the <i>Database Migration Service User Guide.</i> </p>"""
    source_ids: NotRequired[
        "capo_database_migration_service.types.source_ids_list.SourceIdsList"
    ]
    """<p>A list of identifiers for which DMS provides notification events.</p> <p>If you don't specify a value, notifications are provided for all sources.</p> <p>If you specify multiple values, they must be of the same type. For example, if you specify a database instance ID, then all of the other values must be database instance IDs.</p>"""
    enabled: NotRequired[
        "capo_database_migration_service.types.boolean_optional.BooleanOptional"
    ]
    """<p> A Boolean value; set to <code>true</code> to activate the subscription, or set to <code>false</code> to create the subscription but not activate it. </p>"""
    tags: NotRequired["capo_database_migration_service.types.tag_list.TagList"]
    """<p>One or more tags to be assigned to the event subscription.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: CreateEventSubscriptionMessage) -> dict:
    out: dict = {}
    out["SubscriptionName"] = value["subscription_name"]
    out["SnsTopicArn"] = value["sns_topic_arn"]
    if "source_type" in value:
        out["SourceType"] = value["source_type"]
    if "event_categories" in value:
        import capo_database_migration_service.types.event_categories_list

        out["EventCategories"] = (
            capo_database_migration_service.types.event_categories_list.serialize_aws_json_1_1(
                value["event_categories"]
            )
        )
    if "source_ids" in value:
        import capo_database_migration_service.types.source_ids_list

        out["SourceIds"] = (
            capo_database_migration_service.types.source_ids_list.serialize_aws_json_1_1(
                value["source_ids"]
            )
        )
    if "enabled" in value:
        out["Enabled"] = value["enabled"]
    if "tags" in value:
        import capo_database_migration_service.types.tag_list

        out["Tags"] = (
            capo_database_migration_service.types.tag_list.serialize_aws_json_1_1(
                value["tags"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> CreateEventSubscriptionMessage:
    out: CreateEventSubscriptionMessage = {}  # type: ignore[typeddict-item]
    if data.get("SubscriptionName") is not None:
        out["subscription_name"] = data["SubscriptionName"]
    else:
        raise DeserializationError(
            "CreateEventSubscriptionMessage.subscription_name required"
        )
    if data.get("SnsTopicArn") is not None:
        out["sns_topic_arn"] = data["SnsTopicArn"]
    else:
        raise DeserializationError(
            "CreateEventSubscriptionMessage.sns_topic_arn required"
        )
    if data.get("SourceType") is not None:
        out["source_type"] = data["SourceType"]
    if data.get("EventCategories") is not None:
        import capo_database_migration_service.types.event_categories_list

        out["event_categories"] = (
            capo_database_migration_service.types.event_categories_list.deserialize_aws_json_1_1(
                data["EventCategories"]
            )
        )
    if data.get("SourceIds") is not None:
        import capo_database_migration_service.types.source_ids_list

        out["source_ids"] = (
            capo_database_migration_service.types.source_ids_list.deserialize_aws_json_1_1(
                data["SourceIds"]
            )
        )
    if data.get("Enabled") is not None:
        out["enabled"] = data["Enabled"]
    if data.get("Tags") is not None:
        import capo_database_migration_service.types.tag_list

        out["tags"] = (
            capo_database_migration_service.types.tag_list.deserialize_aws_json_1_1(
                data["Tags"]
            )
        )
    return out
