"""Generated from Smithy shape ``com.amazonaws.databasemigrationservice#PremigrationAssessmentStatus``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_database_migration_service.types.boolean
    import capo_database_migration_service.types.replication_task_assessment_run_progress
    import capo_database_migration_service.types.replication_task_assessment_run_result_statistic
    import capo_database_migration_service.types.string
    import capo_database_migration_service.types.t_stamp


class PremigrationAssessmentStatus(TypedDict, closed=True):
    premigration_assessment_run_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The Amazon Resource Name (ARN) of this assessment run.</p>"""
    fail_on_assessment_failure: "capo_database_migration_service.types.boolean.Boolean"
    """<p>A configurable setting you can set to <code>true</code> (the defualt setting) or <code>false</code>. Use this setting to to stop the replication from starting automatically if the assessment fails. This can help you evaluate the issue that is preventing the replication from running successfully.</p>"""
    status: NotRequired["capo_database_migration_service.types.string.String"]
    """<p>This describes the assessment run status. The status can be one of the following values:</p> <ul> <li> <p> <code>cancelling</code>: The assessment run was canceled.</p> </li> <li> <p> <code>deleting</code>: The assessment run was deleted.</p> </li> <li> <p> <code>failed</code>: At least one individual assessment completed with a failed status. </p> </li> <li> <p> <code>error-provisioning</code>: An internal error occurred while resources were provisioned (during the <code>provisioning</code> status).</p> </li> <li> <p> <code>error-executing</code> An internal error occurred while individual assessments ran (during the <code>running</code> status).</p> </li> <li> <p> <code>invalid state</code>: The assessment run is in an unknown state. </p> </li> <li> <p> <code>passed</code>: All individual assessments have completed and none have a failed status.</p> </li> <li> <p> <code>provisioning</code>: The resources required to run individual assessments are being provisioned. </p> </li> <li> <p> <code>running</code>: Individual assessments are being run. </p> </li> <li> <p> <code>starting</code>: The assessment run is starting, but resources are not yet being provisioned for individual assessments. </p> </li> <li> <p> <code>warning</code>: At least one individual assessment completed with a warning status. </p> </li> </ul>"""
    premigration_assessment_run_creation_date: NotRequired[
        "capo_database_migration_service.types.t_stamp.TStamp"
    ]
    """<p>The date which the assessment run was created.</p>"""
    assessment_progress: NotRequired[
        "capo_database_migration_service.types.replication_task_assessment_run_progress.ReplicationTaskAssessmentRunProgress"
    ]
    last_failure_message: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The last message generated by an individual assessment failure.</p>"""
    result_location_bucket: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The Amazon S3 bucket that Database Migration Service Serverless created to store the results of this assessment run.</p>"""
    result_location_folder: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The folder within an Amazon S3 bucket where you want Database Migration Service to store the results of this assessment run.</p>"""
    result_encryption_mode: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The supported values are <code>SSE_KMS</code> and <code>SSE_S3</code>. If these values are not provided, then the files are not encrypted at rest. For more information, see <a href="https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.S3.html#CHAP_Target.S3.KMSKeys">Creating Amazon Web Services KMS keys to encrypt Amazon S3 target objects</a>.</p>"""
    result_kms_key_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>The ARN of a custom KMS encryption key that you specify when you set <code>ResultEncryptionMode</code> to <code>SSE_KMS</code>.</p>"""
    result_statistic: NotRequired[
        "capo_database_migration_service.types.replication_task_assessment_run_result_statistic.ReplicationTaskAssessmentRunResultStatistic"
    ]


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: PremigrationAssessmentStatus) -> dict:
    out: dict = {}
    if "premigration_assessment_run_arn" in value:
        out["PremigrationAssessmentRunArn"] = value["premigration_assessment_run_arn"]
    out["FailOnAssessmentFailure"] = value.get("fail_on_assessment_failure", False)
    if "status" in value:
        out["Status"] = value["status"]
    if "premigration_assessment_run_creation_date" in value:
        import capo_database_migration_service.types.t_stamp

        out["PremigrationAssessmentRunCreationDate"] = (
            capo_database_migration_service.types.t_stamp.serialize_aws_json_1_1(
                value["premigration_assessment_run_creation_date"]
            )
        )
    if "assessment_progress" in value:
        import capo_database_migration_service.types.replication_task_assessment_run_progress

        out["AssessmentProgress"] = (
            capo_database_migration_service.types.replication_task_assessment_run_progress.serialize_aws_json_1_1(
                value["assessment_progress"]
            )
        )
    if "last_failure_message" in value:
        out["LastFailureMessage"] = value["last_failure_message"]
    if "result_location_bucket" in value:
        out["ResultLocationBucket"] = value["result_location_bucket"]
    if "result_location_folder" in value:
        out["ResultLocationFolder"] = value["result_location_folder"]
    if "result_encryption_mode" in value:
        out["ResultEncryptionMode"] = value["result_encryption_mode"]
    if "result_kms_key_arn" in value:
        out["ResultKmsKeyArn"] = value["result_kms_key_arn"]
    if "result_statistic" in value:
        import capo_database_migration_service.types.replication_task_assessment_run_result_statistic

        out["ResultStatistic"] = (
            capo_database_migration_service.types.replication_task_assessment_run_result_statistic.serialize_aws_json_1_1(
                value["result_statistic"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> PremigrationAssessmentStatus:
    out: PremigrationAssessmentStatus = {}  # type: ignore[typeddict-item]
    if data.get("PremigrationAssessmentRunArn") is not None:
        out["premigration_assessment_run_arn"] = data["PremigrationAssessmentRunArn"]
    if data.get("FailOnAssessmentFailure") is not None:
        out["fail_on_assessment_failure"] = data["FailOnAssessmentFailure"]
    else:
        out["fail_on_assessment_failure"] = False
    if data.get("Status") is not None:
        out["status"] = data["Status"]
    if data.get("PremigrationAssessmentRunCreationDate") is not None:
        import capo_database_migration_service.types.t_stamp

        out["premigration_assessment_run_creation_date"] = (
            capo_database_migration_service.types.t_stamp.deserialize_aws_json_1_1(
                data["PremigrationAssessmentRunCreationDate"]
            )
        )
    if data.get("AssessmentProgress") is not None:
        import capo_database_migration_service.types.replication_task_assessment_run_progress

        out["assessment_progress"] = (
            capo_database_migration_service.types.replication_task_assessment_run_progress.deserialize_aws_json_1_1(
                data["AssessmentProgress"]
            )
        )
    if data.get("LastFailureMessage") is not None:
        out["last_failure_message"] = data["LastFailureMessage"]
    if data.get("ResultLocationBucket") is not None:
        out["result_location_bucket"] = data["ResultLocationBucket"]
    if data.get("ResultLocationFolder") is not None:
        out["result_location_folder"] = data["ResultLocationFolder"]
    if data.get("ResultEncryptionMode") is not None:
        out["result_encryption_mode"] = data["ResultEncryptionMode"]
    if data.get("ResultKmsKeyArn") is not None:
        out["result_kms_key_arn"] = data["ResultKmsKeyArn"]
    if data.get("ResultStatistic") is not None:
        import capo_database_migration_service.types.replication_task_assessment_run_result_statistic

        out["result_statistic"] = (
            capo_database_migration_service.types.replication_task_assessment_run_result_statistic.deserialize_aws_json_1_1(
                data["ResultStatistic"]
            )
        )
    return out
