"""Generated from Smithy shape ``com.amazonaws.databasemigrationservice#ReplicationTaskAssessmentRun``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_database_migration_service.types.boolean
    import capo_database_migration_service.types.replication_task_assessment_run_progress
    import capo_database_migration_service.types.replication_task_assessment_run_result_statistic
    import capo_database_migration_service.types.string
    import capo_database_migration_service.types.t_stamp


class ReplicationTaskAssessmentRun(TypedDict, closed=True):
    replication_task_assessment_run_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Amazon Resource Name (ARN) of this assessment run.</p>"""
    replication_task_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>ARN of the migration task associated with this premigration assessment run.</p>"""
    status: NotRequired["capo_database_migration_service.types.string.String"]
    """<p>Assessment run status. </p> <p>This status can have one of the following values:</p> <ul> <li> <p> <code>"cancelling"</code> – The assessment run was canceled by the <code>CancelReplicationTaskAssessmentRun</code> operation.</p> </li> <li> <p> <code>"deleting"</code> – The assessment run was deleted by the <code>DeleteReplicationTaskAssessmentRun</code> operation.</p> </li> <li> <p> <code>"failed"</code> – At least one individual assessment completed with a <code>failed</code> status.</p> </li> <li> <p> <code>"error-provisioning"</code> – An internal error occurred while resources were provisioned (during <code>provisioning</code> status).</p> </li> <li> <p> <code>"error-executing"</code> – An internal error occurred while individual assessments ran (during <code>running</code> status).</p> </li> <li> <p> <code>"invalid state"</code> – The assessment run is in an unknown state.</p> </li> <li> <p> <code>"passed"</code> – All individual assessments have completed, and none has a <code>failed</code> status.</p> </li> <li> <p> <code>"provisioning"</code> – Resources required to run individual assessments are being provisioned.</p> </li> <li> <p> <code>"running"</code> – Individual assessments are being run.</p> </li> <li> <p> <code>"starting"</code> – The assessment run is starting, but resources are not yet being provisioned for individual assessments.</p> </li> <li> <p> <code>"warning"</code> – At least one individual assessment completed with a <code>warning</code> status or all individual assessments were skipped (completed with a <code>skipped</code> status).</p> </li> </ul>"""
    replication_task_assessment_run_creation_date: NotRequired[
        "capo_database_migration_service.types.t_stamp.TStamp"
    ]
    """<p>Date on which the assessment run was created using the <code>StartReplicationTaskAssessmentRun</code> operation.</p>"""
    assessment_progress: NotRequired[
        "capo_database_migration_service.types.replication_task_assessment_run_progress.ReplicationTaskAssessmentRunProgress"
    ]
    """<p>Indication of the completion progress for the individual assessments specified to run.</p>"""
    last_failure_message: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Last message generated by an individual assessment failure.</p>"""
    service_access_role_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>ARN of the service role used to start the assessment run using the <code>StartReplicationTaskAssessmentRun</code> operation. The role must allow the <code>iam:PassRole</code> action.</p>"""
    result_location_bucket: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Amazon S3 bucket where DMS stores the results of this assessment run.</p>"""
    result_location_folder: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Folder in an Amazon S3 bucket where DMS stores the results of this assessment run.</p>"""
    result_encryption_mode: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Encryption mode used to encrypt the assessment run results.</p>"""
    result_kms_key_arn: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>ARN of the KMS encryption key used to encrypt the assessment run results.</p>"""
    assessment_run_name: NotRequired[
        "capo_database_migration_service.types.string.String"
    ]
    """<p>Unique name of the assessment run.</p>"""
    is_latest_task_assessment_run: (
        "capo_database_migration_service.types.boolean.Boolean"
    )
    """<p>Indicates that the following PreflightAssessmentRun is the latest for the ReplicationTask. The status is either true or false.</p>"""
    result_statistic: NotRequired[
        "capo_database_migration_service.types.replication_task_assessment_run_result_statistic.ReplicationTaskAssessmentRunResultStatistic"
    ]
    """<p> Result statistics for a completed assessment run, showing aggregated statistics of IndividualAssessments for how many assessments were passed, failed, or encountered issues such as errors or warnings. </p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ReplicationTaskAssessmentRun) -> dict:
    out: dict = {}
    if "replication_task_assessment_run_arn" in value:
        out["ReplicationTaskAssessmentRunArn"] = value[
            "replication_task_assessment_run_arn"
        ]
    if "replication_task_arn" in value:
        out["ReplicationTaskArn"] = value["replication_task_arn"]
    if "status" in value:
        out["Status"] = value["status"]
    if "replication_task_assessment_run_creation_date" in value:
        import capo_database_migration_service.types.t_stamp

        out["ReplicationTaskAssessmentRunCreationDate"] = (
            capo_database_migration_service.types.t_stamp.serialize_aws_json_1_1(
                value["replication_task_assessment_run_creation_date"]
            )
        )
    if "assessment_progress" in value:
        import capo_database_migration_service.types.replication_task_assessment_run_progress

        out["AssessmentProgress"] = (
            capo_database_migration_service.types.replication_task_assessment_run_progress.serialize_aws_json_1_1(
                value["assessment_progress"]
            )
        )
    if "last_failure_message" in value:
        out["LastFailureMessage"] = value["last_failure_message"]
    if "service_access_role_arn" in value:
        out["ServiceAccessRoleArn"] = value["service_access_role_arn"]
    if "result_location_bucket" in value:
        out["ResultLocationBucket"] = value["result_location_bucket"]
    if "result_location_folder" in value:
        out["ResultLocationFolder"] = value["result_location_folder"]
    if "result_encryption_mode" in value:
        out["ResultEncryptionMode"] = value["result_encryption_mode"]
    if "result_kms_key_arn" in value:
        out["ResultKmsKeyArn"] = value["result_kms_key_arn"]
    if "assessment_run_name" in value:
        out["AssessmentRunName"] = value["assessment_run_name"]
    out["IsLatestTaskAssessmentRun"] = value.get("is_latest_task_assessment_run", False)
    if "result_statistic" in value:
        import capo_database_migration_service.types.replication_task_assessment_run_result_statistic

        out["ResultStatistic"] = (
            capo_database_migration_service.types.replication_task_assessment_run_result_statistic.serialize_aws_json_1_1(
                value["result_statistic"]
            )
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ReplicationTaskAssessmentRun:
    out: ReplicationTaskAssessmentRun = {}  # type: ignore[typeddict-item]
    if data.get("ReplicationTaskAssessmentRunArn") is not None:
        out["replication_task_assessment_run_arn"] = data[
            "ReplicationTaskAssessmentRunArn"
        ]
    if data.get("ReplicationTaskArn") is not None:
        out["replication_task_arn"] = data["ReplicationTaskArn"]
    if data.get("Status") is not None:
        out["status"] = data["Status"]
    if data.get("ReplicationTaskAssessmentRunCreationDate") is not None:
        import capo_database_migration_service.types.t_stamp

        out["replication_task_assessment_run_creation_date"] = (
            capo_database_migration_service.types.t_stamp.deserialize_aws_json_1_1(
                data["ReplicationTaskAssessmentRunCreationDate"]
            )
        )
    if data.get("AssessmentProgress") is not None:
        import capo_database_migration_service.types.replication_task_assessment_run_progress

        out["assessment_progress"] = (
            capo_database_migration_service.types.replication_task_assessment_run_progress.deserialize_aws_json_1_1(
                data["AssessmentProgress"]
            )
        )
    if data.get("LastFailureMessage") is not None:
        out["last_failure_message"] = data["LastFailureMessage"]
    if data.get("ServiceAccessRoleArn") is not None:
        out["service_access_role_arn"] = data["ServiceAccessRoleArn"]
    if data.get("ResultLocationBucket") is not None:
        out["result_location_bucket"] = data["ResultLocationBucket"]
    if data.get("ResultLocationFolder") is not None:
        out["result_location_folder"] = data["ResultLocationFolder"]
    if data.get("ResultEncryptionMode") is not None:
        out["result_encryption_mode"] = data["ResultEncryptionMode"]
    if data.get("ResultKmsKeyArn") is not None:
        out["result_kms_key_arn"] = data["ResultKmsKeyArn"]
    if data.get("AssessmentRunName") is not None:
        out["assessment_run_name"] = data["AssessmentRunName"]
    if data.get("IsLatestTaskAssessmentRun") is not None:
        out["is_latest_task_assessment_run"] = data["IsLatestTaskAssessmentRun"]
    else:
        out["is_latest_task_assessment_run"] = False
    if data.get("ResultStatistic") is not None:
        import capo_database_migration_service.types.replication_task_assessment_run_result_statistic

        out["result_statistic"] = (
            capo_database_migration_service.types.replication_task_assessment_run_result_statistic.deserialize_aws_json_1_1(
                data["ResultStatistic"]
            )
        )
    return out
