"""Generated from Smithy shape ``com.amazonaws.bedrockagentcorecontrol#EpisodicReflectionConfiguration``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_bedrock_agentcore_control.types.memory_record_schema
    import capo_bedrock_agentcore_control.types.namespaces_list


class EpisodicReflectionConfiguration(TypedDict, closed=True):
    namespaces: NotRequired[
        "capo_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>This is a legacy parameter, use <code>namespaceTemplates</code>. The namespaces for which to create reflections. Can be less nested than the episodic namespaces.</p>"""
    namespace_templates: NotRequired[
        "capo_bedrock_agentcore_control.types.namespaces_list.NamespacesList"
    ]
    """<p>The namespaceTemplates for which to create reflections. Can be less nested than the episodic namespaces.</p>"""
    memory_record_schema: NotRequired[
        "capo_bedrock_agentcore_control.types.memory_record_schema.MemoryRecordSchema"
    ]
    """<p>"Schema for metadata fields on records generated by reflections.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: EpisodicReflectionConfiguration) -> dict:
    out: dict = {}
    if "namespaces" in value:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespaces"]
            )
        )
    if "namespace_templates" in value:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaceTemplates"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.serialize_json(
                value["namespace_templates"]
            )
        )
    if "memory_record_schema" in value:
        import capo_bedrock_agentcore_control.types.memory_record_schema

        out["memoryRecordSchema"] = (
            capo_bedrock_agentcore_control.types.memory_record_schema.serialize_json(
                value["memory_record_schema"]
            )
        )
    return out


def deserialize_json(data: dict) -> EpisodicReflectionConfiguration:
    out: EpisodicReflectionConfiguration = {}  # type: ignore[typeddict-item]
    if data.get("namespaces") is not None:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespaces"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaces"]
            )
        )
    if data.get("namespaceTemplates") is not None:
        import capo_bedrock_agentcore_control.types.namespaces_list

        out["namespace_templates"] = (
            capo_bedrock_agentcore_control.types.namespaces_list.deserialize_json(
                data["namespaceTemplates"]
            )
        )
    if data.get("memoryRecordSchema") is not None:
        import capo_bedrock_agentcore_control.types.memory_record_schema

        out["memory_record_schema"] = (
            capo_bedrock_agentcore_control.types.memory_record_schema.deserialize_json(
                data["memoryRecordSchema"]
            )
        )
    return out
