"""Generated from Smithy shape ``com.amazonaws.identitystore#ListIdentityStoresResponse``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import DeserializationError

if TYPE_CHECKING:
    import capo_identitystore.types.identity_stores
    import capo_identitystore.types.next_token


class ListIdentityStoresResponse(TypedDict, closed=True):
    identity_stores: "capo_identitystore.types.identity_stores.IdentityStores"
    """<p>A list of <code>IdentityStore</code> objects, each of which contains the identifiers for an identity store that you have access to.</p>"""
    next_token: NotRequired["capo_identitystore.types.next_token.NextToken"]
    """<p>The pagination token used for the <code>ListIdentityStores</code> API operation. This value is generated by the identity store service. It is returned in the API response if the total results are more than the size of one page. This token is also returned when it is used in the API request to retrieve the next page of results.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListIdentityStoresResponse) -> dict:
    out: dict = {}
    import capo_identitystore.types.identity_stores

    out["IdentityStores"] = (
        capo_identitystore.types.identity_stores.serialize_aws_json_1_1(
            value["identity_stores"]
        )
    )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListIdentityStoresResponse:
    out: ListIdentityStoresResponse = {}  # type: ignore[typeddict-item]
    if data.get("IdentityStores") is not None:
        import capo_identitystore.types.identity_stores

        out["identity_stores"] = (
            capo_identitystore.types.identity_stores.deserialize_aws_json_1_1(
                data["IdentityStores"]
            )
        )
    else:
        raise DeserializationError(
            "ListIdentityStoresResponse.identity_stores required"
        )
    if data.get("NextToken") is not None:
        out["next_token"] = data["NextToken"]
    return out
