"""Generated from Smithy shape ``com.amazonaws.identitystore#ListUsersRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import DeserializationError

if TYPE_CHECKING:
    import capo_identitystore.types.extension_names
    import capo_identitystore.types.filters
    import capo_identitystore.types.identity_store_id
    import capo_identitystore.types.max_results
    import capo_identitystore.types.next_token


class ListUsersRequest(TypedDict, closed=True):
    identity_store_id: "capo_identitystore.types.identity_store_id.IdentityStoreId"
    """<p>The globally unique identifier for the identity store, such as <code>d-1234567890</code>. In this example, <code>d-</code> is a fixed prefix, and <code>1234567890</code> is a randomly generated string that contains numbers and lower case letters. This value is generated at the time that a new identity store is created.</p> <p>You can specify the identity store by ID or by Amazon Resource Name (ARN). For example, identity store ID <code>d-1234567890</code> or identity store ARN <code>arn:aws:identitystore::111122223333:identitystore/d-1234567890</code>.</p>"""
    extensions: NotRequired["capo_identitystore.types.extension_names.ExtensionNames"]
    """<p>A collection of extension names indicating what extensions the service should retrieve alongside other user attributes. <code>aws:identitystore:enterprise</code> is the only supported extension name.</p>"""
    max_results: NotRequired["capo_identitystore.types.max_results.MaxResults"]
    """<p>The maximum number of results to be returned per request. This parameter is used in all <code>List</code> requests to specify how many results to return in one page.</p>"""
    next_token: NotRequired["capo_identitystore.types.next_token.NextToken"]
    """<p>The pagination token used for the <code>ListUsers</code> and <code>ListGroups</code> API operations. This value is generated by the identity store service. It is returned in the API response if the total results are more than the size of one page. This token is also returned when it is used in the API request to retrieve the next page of results.</p>"""
    filters: NotRequired["capo_identitystore.types.filters.Filters"]
    """<p>A list of <code>Filter</code> objects, which is used in the <code>ListUsers</code> and <code> ListGroups</code> requests. </p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListUsersRequest) -> dict:
    out: dict = {}
    out["IdentityStoreId"] = value["identity_store_id"]
    if "extensions" in value:
        import capo_identitystore.types.extension_names

        out["Extensions"] = (
            capo_identitystore.types.extension_names.serialize_aws_json_1_1(
                value["extensions"]
            )
        )
    out["MaxResults"] = value.get("max_results", 100)
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "filters" in value:
        import capo_identitystore.types.filters

        out["Filters"] = capo_identitystore.types.filters.serialize_aws_json_1_1(
            value["filters"]
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> ListUsersRequest:
    out: ListUsersRequest = {}  # type: ignore[typeddict-item]
    if data.get("IdentityStoreId") is not None:
        out["identity_store_id"] = data["IdentityStoreId"]
    else:
        raise DeserializationError("ListUsersRequest.identity_store_id required")
    if data.get("Extensions") is not None:
        import capo_identitystore.types.extension_names

        out["extensions"] = (
            capo_identitystore.types.extension_names.deserialize_aws_json_1_1(
                data["Extensions"]
            )
        )
    if data.get("MaxResults") is not None:
        out["max_results"] = data["MaxResults"]
    else:
        out["max_results"] = 100
    if data.get("NextToken") is not None:
        out["next_token"] = data["NextToken"]
    if data.get("Filters") is not None:
        import capo_identitystore.types.filters

        out["filters"] = capo_identitystore.types.filters.deserialize_aws_json_1_1(
            data["Filters"]
        )
    return out
