"""Generated from Smithy shape ``com.amazonaws.identitystore#ListGroupMembershipsForMemberRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_identitystore.errors import DeserializationError

if TYPE_CHECKING:
    import capo_identitystore.types.identity_store_id
    import capo_identitystore.types.max_results
    import capo_identitystore.types.member_id
    import capo_identitystore.types.next_token


class ListGroupMembershipsForMemberRequest(TypedDict, closed=True):
    identity_store_id: "capo_identitystore.types.identity_store_id.IdentityStoreId"
    """<p>The globally unique identifier for the identity store.</p> <p>You can specify the identity store by ID or by Amazon Resource Name (ARN). For example, identity store ID <code>d-1234567890</code> or identity store ARN <code>arn:aws:identitystore::111122223333:identitystore/d-1234567890</code>.</p>"""
    member_id: "capo_identitystore.types.member_id.MemberId"
    """<p>An object that contains the identifier of a group member. Setting the <code>UserID</code> field to the specific identifier for a user indicates that the user is a member of the group.</p>"""
    max_results: NotRequired["capo_identitystore.types.max_results.MaxResults"]
    """<p>The maximum number of results to be returned per request. This parameter is used in all <code>List</code> requests to specify how many results to return in one page.</p>"""
    next_token: NotRequired["capo_identitystore.types.next_token.NextToken"]
    """<p>The pagination token used for the <code>ListUsers</code>, <code>ListGroups</code>, and <code> ListGroupMemberships</code> API operations. This value is generated by the identity store service. It is returned in the API response if the total results are more than the size of one page. This token is also returned when it is used in the API request to retrieve the next page of results.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ListGroupMembershipsForMemberRequest) -> dict:
    out: dict = {}
    out["IdentityStoreId"] = value["identity_store_id"]
    import capo_identitystore.types.member_id

    out["MemberId"] = capo_identitystore.types.member_id.serialize_aws_json_1_1(
        value["member_id"]
    )
    out["MaxResults"] = value.get("max_results", 100)
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ListGroupMembershipsForMemberRequest:
    out: ListGroupMembershipsForMemberRequest = {}  # type: ignore[typeddict-item]
    if data.get("IdentityStoreId") is not None:
        out["identity_store_id"] = data["IdentityStoreId"]
    else:
        raise DeserializationError(
            "ListGroupMembershipsForMemberRequest.identity_store_id required"
        )
    if data.get("MemberId") is not None:
        import capo_identitystore.types.member_id

        out["member_id"] = capo_identitystore.types.member_id.deserialize_aws_json_1_1(
            data["MemberId"]
        )
    else:
        raise DeserializationError(
            "ListGroupMembershipsForMemberRequest.member_id required"
        )
    if data.get("MaxResults") is not None:
        out["max_results"] = data["MaxResults"]
    else:
        out["max_results"] = 100
    if data.get("NextToken") is not None:
        out["next_token"] = data["NextToken"]
    return out
