"""Generated from Smithy shape ``com.amazonaws.ssoadmin#PermissionSetProvisioningStatus``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_sso_admin.types.account_id
    import capo_sso_admin.types.date
    import capo_sso_admin.types.permission_set_arn
    import capo_sso_admin.types.reason
    import capo_sso_admin.types.status_values
    import capo_sso_admin.types.uu_id


class PermissionSetProvisioningStatus(TypedDict, closed=True):
    status: NotRequired["capo_sso_admin.types.status_values.StatusValues"]
    """<p>The status of the permission set provisioning process.</p>"""
    request_id: NotRequired["capo_sso_admin.types.uu_id.UUId"]
    """<p>The identifier for tracking the request operation that is generated by the universally unique identifier (UUID) workflow.</p>"""
    account_id: NotRequired["capo_sso_admin.types.account_id.AccountId"]
    """<p>The identifier of the Amazon Web Services account from which to list the assignments.</p>"""
    permission_set_arn: NotRequired[
        "capo_sso_admin.types.permission_set_arn.PermissionSetArn"
    ]
    """<p>The ARN of the permission set that is being provisioned. For more information about ARNs, see <a href="/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs) and Amazon Web Services Service Namespaces</a> in the <i>Amazon Web Services General Reference</i>.</p>"""
    failure_reason: NotRequired["capo_sso_admin.types.reason.Reason"]
    """<p>The message that contains an error or exception in case of an operation failure.</p>"""
    created_date: NotRequired["capo_sso_admin.types.date.Date"]
    """<p>The date that the permission set was created.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: PermissionSetProvisioningStatus) -> dict:
    out: dict = {}
    if "status" in value:
        import capo_sso_admin.types.status_values

        out["Status"] = capo_sso_admin.types.status_values.serialize_aws_json_1_1(
            value["status"]
        )
    if "request_id" in value:
        out["RequestId"] = value["request_id"]
    if "account_id" in value:
        out["AccountId"] = value["account_id"]
    if "permission_set_arn" in value:
        out["PermissionSetArn"] = value["permission_set_arn"]
    if "failure_reason" in value:
        out["FailureReason"] = value["failure_reason"]
    if "created_date" in value:
        import capo_sso_admin.types.date

        out["CreatedDate"] = capo_sso_admin.types.date.serialize_aws_json_1_1(
            value["created_date"]
        )
    return out


def deserialize_aws_json_1_1(data: dict) -> PermissionSetProvisioningStatus:
    out: PermissionSetProvisioningStatus = {}  # type: ignore[typeddict-item]
    if data.get("Status") is not None:
        import capo_sso_admin.types.status_values

        out["status"] = capo_sso_admin.types.status_values.deserialize_aws_json_1_1(
            data["Status"]
        )
    if data.get("RequestId") is not None:
        out["request_id"] = data["RequestId"]
    if data.get("AccountId") is not None:
        out["account_id"] = data["AccountId"]
    if data.get("PermissionSetArn") is not None:
        out["permission_set_arn"] = data["PermissionSetArn"]
    if data.get("FailureReason") is not None:
        out["failure_reason"] = data["FailureReason"]
    if data.get("CreatedDate") is not None:
        import capo_sso_admin.types.date

        out["created_date"] = capo_sso_admin.types.date.deserialize_aws_json_1_1(
            data["CreatedDate"]
        )
    return out
