"""Generated from Smithy shape ``com.amazonaws.mediaconnect#GatewayInstance``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_mediaconnect.types.__list_of_message_detail
    import capo_mediaconnect.types.bridge_placement
    import capo_mediaconnect.types.connection_status
    import capo_mediaconnect.types.instance_state


class GatewayInstance(TypedDict, closed=True):
    bridge_placement: NotRequired[
        "capo_mediaconnect.types.bridge_placement.BridgePlacement"
    ]
    """<p>The availability of the instance to host new bridges. The bridgePlacement property can be LOCKED or AVAILABLE. If it is LOCKED, no new bridges can be deployed to this instance. If it is AVAILABLE, new bridges can be deployed to this instance. </p>"""
    connection_status: NotRequired[
        "capo_mediaconnect.types.connection_status.ConnectionStatus"
    ]
    """<p>The connection state of the instance. </p>"""
    gateway_arn: NotRequired["str"]
    """<p>The Amazon Resource Name (ARN) of the instance. </p>"""
    gateway_instance_arn: NotRequired["str"]
    """<p>The ARN of the gateway. </p>"""
    instance_id: NotRequired["str"]
    """<p>The instance ID generated by the SSM install. This will begin with "mi-". </p>"""
    instance_messages: NotRequired[
        "capo_mediaconnect.types.__list_of_message_detail.__listOfMessageDetail"
    ]
    """<p> Messages with information about the gateway. </p>"""
    instance_state: NotRequired["capo_mediaconnect.types.instance_state.InstanceState"]
    """<p>The status of the instance. </p>"""
    running_bridge_count: NotRequired["int"]
    """<p> The running bridge count. </p>"""


# --- restJson1 ser/de ---
def serialize_json(value: GatewayInstance) -> dict:
    out: dict = {}
    if "bridge_placement" in value:
        import capo_mediaconnect.types.bridge_placement

        out["bridgePlacement"] = (
            capo_mediaconnect.types.bridge_placement.serialize_json(
                value["bridge_placement"]
            )
        )
    if "connection_status" in value:
        import capo_mediaconnect.types.connection_status

        out["connectionStatus"] = (
            capo_mediaconnect.types.connection_status.serialize_json(
                value["connection_status"]
            )
        )
    if "gateway_arn" in value:
        out["gatewayArn"] = value["gateway_arn"]
    if "gateway_instance_arn" in value:
        out["gatewayInstanceArn"] = value["gateway_instance_arn"]
    if "instance_id" in value:
        out["instanceId"] = value["instance_id"]
    if "instance_messages" in value:
        import capo_mediaconnect.types.__list_of_message_detail

        out["instanceMessages"] = (
            capo_mediaconnect.types.__list_of_message_detail.serialize_json(
                value["instance_messages"]
            )
        )
    if "instance_state" in value:
        import capo_mediaconnect.types.instance_state

        out["instanceState"] = capo_mediaconnect.types.instance_state.serialize_json(
            value["instance_state"]
        )
    if "running_bridge_count" in value:
        out["runningBridgeCount"] = value["running_bridge_count"]
    return out


def deserialize_json(data: dict) -> GatewayInstance:
    out: GatewayInstance = {}  # type: ignore[typeddict-item]
    if data.get("bridgePlacement") is not None:
        import capo_mediaconnect.types.bridge_placement

        out["bridge_placement"] = (
            capo_mediaconnect.types.bridge_placement.deserialize_json(
                data["bridgePlacement"]
            )
        )
    if data.get("connectionStatus") is not None:
        import capo_mediaconnect.types.connection_status

        out["connection_status"] = (
            capo_mediaconnect.types.connection_status.deserialize_json(
                data["connectionStatus"]
            )
        )
    if data.get("gatewayArn") is not None:
        out["gateway_arn"] = data["gatewayArn"]
    if data.get("gatewayInstanceArn") is not None:
        out["gateway_instance_arn"] = data["gatewayInstanceArn"]
    if data.get("instanceId") is not None:
        out["instance_id"] = data["instanceId"]
    if data.get("instanceMessages") is not None:
        import capo_mediaconnect.types.__list_of_message_detail

        out["instance_messages"] = (
            capo_mediaconnect.types.__list_of_message_detail.deserialize_json(
                data["instanceMessages"]
            )
        )
    if data.get("instanceState") is not None:
        import capo_mediaconnect.types.instance_state

        out["instance_state"] = capo_mediaconnect.types.instance_state.deserialize_json(
            data["instanceState"]
        )
    if data.get("runningBridgeCount") is not None:
        out["running_bridge_count"] = data["runningBridgeCount"]
    return out
