"""Generated from Smithy shape ``com.amazonaws.mediaconnect#ListedGatewayInstance``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_mediaconnect.types.instance_state


class ListedGatewayInstance(TypedDict, closed=True):
    gateway_arn: NotRequired["str"]
    """<p> The Amazon Resource Name (ARN) of the gateway.</p>"""
    gateway_instance_arn: NotRequired["str"]
    """<p> The Amazon Resource Name (ARN) of the instance.</p>"""
    instance_id: NotRequired["str"]
    """<p> The managed instance ID generated by the SSM install. This will begin with "mi-".</p>"""
    instance_state: NotRequired["capo_mediaconnect.types.instance_state.InstanceState"]
    """<p> The status of the instance.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListedGatewayInstance) -> dict:
    out: dict = {}
    if "gateway_arn" in value:
        out["gatewayArn"] = value["gateway_arn"]
    if "gateway_instance_arn" in value:
        out["gatewayInstanceArn"] = value["gateway_instance_arn"]
    if "instance_id" in value:
        out["instanceId"] = value["instance_id"]
    if "instance_state" in value:
        import capo_mediaconnect.types.instance_state

        out["instanceState"] = capo_mediaconnect.types.instance_state.serialize_json(
            value["instance_state"]
        )
    return out


def deserialize_json(data: dict) -> ListedGatewayInstance:
    out: ListedGatewayInstance = {}  # type: ignore[typeddict-item]
    if data.get("gatewayArn") is not None:
        out["gateway_arn"] = data["gatewayArn"]
    if data.get("gatewayInstanceArn") is not None:
        out["gateway_instance_arn"] = data["gatewayInstanceArn"]
    if data.get("instanceId") is not None:
        out["instance_id"] = data["instanceId"]
    if data.get("instanceState") is not None:
        import capo_mediaconnect.types.instance_state

        out["instance_state"] = capo_mediaconnect.types.instance_state.deserialize_json(
            data["instanceState"]
        )
    return out
