"""Generated from Smithy shape ``com.amazonaws.customerprofiles#ListProfileObjectsItem``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_customer_profiles.types.string1_to255
    import capo_customer_profiles.types.stringified_json
    import capo_customer_profiles.types.type_name


class ListProfileObjectsItem(TypedDict, closed=True):
    object_type_name: NotRequired["capo_customer_profiles.types.type_name.typeName"]
    """<p>Specifies the kind of object being added to a profile, such as "Salesforce-Account."</p>"""
    profile_object_unique_key: NotRequired[
        "capo_customer_profiles.types.string1_to255.string1To255"
    ]
    """<p>The unique identifier of the ProfileObject generated by the service.</p>"""
    object: NotRequired["capo_customer_profiles.types.stringified_json.stringifiedJson"]
    """<p>A JSON representation of a ProfileObject that belongs to a profile.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListProfileObjectsItem) -> dict:
    out: dict = {}
    if "object_type_name" in value:
        out["ObjectTypeName"] = value["object_type_name"]
    if "profile_object_unique_key" in value:
        out["ProfileObjectUniqueKey"] = value["profile_object_unique_key"]
    if "object" in value:
        out["Object"] = value["object"]
    return out


def deserialize_json(data: dict) -> ListProfileObjectsItem:
    out: ListProfileObjectsItem = {}  # type: ignore[typeddict-item]
    if data.get("ObjectTypeName") is not None:
        out["object_type_name"] = data["ObjectTypeName"]
    if data.get("ProfileObjectUniqueKey") is not None:
        out["profile_object_unique_key"] = data["ProfileObjectUniqueKey"]
    if data.get("Object") is not None:
        out["object"] = data["Object"]
    return out
