"""Generated from Smithy shape ``com.amazonaws.kendra#ServiceNowKnowledgeArticleConfiguration``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_kendra.errors import DeserializationError

if TYPE_CHECKING:
    import capo_kendra.types.boolean
    import capo_kendra.types.data_source_field_name
    import capo_kendra.types.data_source_inclusions_exclusions_strings
    import capo_kendra.types.data_source_to_index_field_mapping_list
    import capo_kendra.types.service_now_knowledge_article_filter_query


class ServiceNowKnowledgeArticleConfiguration(TypedDict, closed=True):
    crawl_attachments: "capo_kendra.types.boolean.Boolean"
    """<p> <code>TRUE</code> to index attachments to knowledge articles.</p>"""
    include_attachment_file_patterns: NotRequired[
        "capo_kendra.types.data_source_inclusions_exclusions_strings.DataSourceInclusionsExclusionsStrings"
    ]
    """<p>A list of regular expression patterns applied to include knowledge article attachments. Attachments that match the patterns are included in the index. Items that don't match the patterns are excluded from the index. If an item matches both an inclusion and exclusion pattern, the exclusion pattern takes precedence and the item isn't included in the index.</p>"""
    exclude_attachment_file_patterns: NotRequired[
        "capo_kendra.types.data_source_inclusions_exclusions_strings.DataSourceInclusionsExclusionsStrings"
    ]
    """<p>A list of regular expression patterns applied to exclude certain knowledge article attachments. Attachments that match the patterns are excluded from the index. Items that don't match the patterns are included in the index. If an item matches both an inclusion and exclusion pattern, the exclusion pattern takes precedence and the item isn't included in the index.</p>"""
    document_data_field_name: (
        "capo_kendra.types.data_source_field_name.DataSourceFieldName"
    )
    """<p>The name of the ServiceNow field that is mapped to the index document contents field in the Amazon Kendra index.</p>"""
    document_title_field_name: NotRequired[
        "capo_kendra.types.data_source_field_name.DataSourceFieldName"
    ]
    """<p>The name of the ServiceNow field that is mapped to the index document title field.</p>"""
    field_mappings: NotRequired[
        "capo_kendra.types.data_source_to_index_field_mapping_list.DataSourceToIndexFieldMappingList"
    ]
    """<p>Maps attributes or field names of knoweldge articles to Amazon Kendra index field names. To create custom fields, use the <code>UpdateIndex</code> API before you map to ServiceNow fields. For more information, see <a href="https://docs.aws.amazon.com/kendra/latest/dg/field-mapping.html">Mapping data source fields</a>. The ServiceNow data source field names must exist in your ServiceNow custom metadata.</p>"""
    filter_query: NotRequired[
        "capo_kendra.types.service_now_knowledge_article_filter_query.ServiceNowKnowledgeArticleFilterQuery"
    ]
    """<p>A query that selects the knowledge articles to index. The query can return articles from multiple knowledge bases, and the knowledge bases can be public or private.</p> <p>The query string must be one generated by the ServiceNow console. For more information, see <a href="https://docs.aws.amazon.com/kendra/latest/dg/servicenow-query.html">Specifying documents to index with a query</a>. </p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: ServiceNowKnowledgeArticleConfiguration) -> dict:
    out: dict = {}
    out["CrawlAttachments"] = value.get("crawl_attachments", False)
    if "include_attachment_file_patterns" in value:
        import capo_kendra.types.data_source_inclusions_exclusions_strings

        out["IncludeAttachmentFilePatterns"] = (
            capo_kendra.types.data_source_inclusions_exclusions_strings.serialize_aws_json_1_1(
                value["include_attachment_file_patterns"]
            )
        )
    if "exclude_attachment_file_patterns" in value:
        import capo_kendra.types.data_source_inclusions_exclusions_strings

        out["ExcludeAttachmentFilePatterns"] = (
            capo_kendra.types.data_source_inclusions_exclusions_strings.serialize_aws_json_1_1(
                value["exclude_attachment_file_patterns"]
            )
        )
    out["DocumentDataFieldName"] = value["document_data_field_name"]
    if "document_title_field_name" in value:
        out["DocumentTitleFieldName"] = value["document_title_field_name"]
    if "field_mappings" in value:
        import capo_kendra.types.data_source_to_index_field_mapping_list

        out["FieldMappings"] = (
            capo_kendra.types.data_source_to_index_field_mapping_list.serialize_aws_json_1_1(
                value["field_mappings"]
            )
        )
    if "filter_query" in value:
        out["FilterQuery"] = value["filter_query"]
    return out


def deserialize_aws_json_1_1(data: dict) -> ServiceNowKnowledgeArticleConfiguration:
    out: ServiceNowKnowledgeArticleConfiguration = {}  # type: ignore[typeddict-item]
    if data.get("CrawlAttachments") is not None:
        out["crawl_attachments"] = data["CrawlAttachments"]
    else:
        out["crawl_attachments"] = False
    if data.get("IncludeAttachmentFilePatterns") is not None:
        import capo_kendra.types.data_source_inclusions_exclusions_strings

        out["include_attachment_file_patterns"] = (
            capo_kendra.types.data_source_inclusions_exclusions_strings.deserialize_aws_json_1_1(
                data["IncludeAttachmentFilePatterns"]
            )
        )
    if data.get("ExcludeAttachmentFilePatterns") is not None:
        import capo_kendra.types.data_source_inclusions_exclusions_strings

        out["exclude_attachment_file_patterns"] = (
            capo_kendra.types.data_source_inclusions_exclusions_strings.deserialize_aws_json_1_1(
                data["ExcludeAttachmentFilePatterns"]
            )
        )
    if data.get("DocumentDataFieldName") is not None:
        out["document_data_field_name"] = data["DocumentDataFieldName"]
    else:
        raise DeserializationError(
            "ServiceNowKnowledgeArticleConfiguration.document_data_field_name required"
        )
    if data.get("DocumentTitleFieldName") is not None:
        out["document_title_field_name"] = data["DocumentTitleFieldName"]
    if data.get("FieldMappings") is not None:
        import capo_kendra.types.data_source_to_index_field_mapping_list

        out["field_mappings"] = (
            capo_kendra.types.data_source_to_index_field_mapping_list.deserialize_aws_json_1_1(
                data["FieldMappings"]
            )
        )
    if data.get("FilterQuery") is not None:
        out["filter_query"] = data["FilterQuery"]
    return out
