"""Generated from Smithy shape ``com.amazonaws.securityhub#AwsSecurityFinding``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_securityhub.types.action
    import capo_securityhub.types.boolean
    import capo_securityhub.types.compliance
    import capo_securityhub.types.detection
    import capo_securityhub.types.field_map
    import capo_securityhub.types.finding_provider_fields
    import capo_securityhub.types.generator_details
    import capo_securityhub.types.integer
    import capo_securityhub.types.malware_list
    import capo_securityhub.types.network
    import capo_securityhub.types.network_path_list
    import capo_securityhub.types.non_empty_string
    import capo_securityhub.types.note
    import capo_securityhub.types.patch_summary
    import capo_securityhub.types.process_details
    import capo_securityhub.types.record_state
    import capo_securityhub.types.related_finding_list
    import capo_securityhub.types.remediation
    import capo_securityhub.types.resource_list
    import capo_securityhub.types.severity
    import capo_securityhub.types.threat_intel_indicator_list
    import capo_securityhub.types.threat_list
    import capo_securityhub.types.type_list
    import capo_securityhub.types.verification_state
    import capo_securityhub.types.vulnerability_list
    import capo_securityhub.types.workflow
    import capo_securityhub.types.workflow_state


class AwsSecurityFinding(TypedDict, closed=True):
    schema_version: NotRequired[
        "capo_securityhub.types.non_empty_string.NonEmptyString"
    ]
    """<p>The schema version that a finding is formatted for. The value is <code>2018-10-08</code>.</p>"""
    id: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The security findings provider-specific identifier for a finding.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 512.</p>"""
    product_arn: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The ARN generated by Security Hub CSPM that uniquely identifies a product that generates findings. This can be the ARN for a third-party product that is integrated with Security Hub CSPM, or the ARN for a custom integration.</p> <p>Length Constraints: Minimum length of 12. Maximum length of 2048.</p>"""
    product_name: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The name of the product that generated the finding.</p> <p>Security Hub CSPM populates this attribute automatically for each finding. You cannot update this attribute with <code>BatchImportFindings</code> or <code>BatchUpdateFindings</code>. The exception to this is a custom integration.</p> <p>When you use the Security Hub CSPM console or API to filter findings by product name, you use this attribute.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 128.</p>"""
    company_name: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The name of the company for the product that generated the finding.</p> <p>Security Hub CSPM populates this attribute automatically for each finding. You cannot update this attribute with <code>BatchImportFindings</code> or <code>BatchUpdateFindings</code>. The exception to this is a custom integration.</p> <p>When you use the Security Hub CSPM console or API to filter findings by company name, you use this attribute.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 128. </p>"""
    region: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The Region from which the finding was generated.</p> <p>Security Hub CSPM populates this attribute automatically for each finding. You cannot update it using <code>BatchImportFindings</code> or <code>BatchUpdateFindings</code>.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 16. </p>"""
    generator_id: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>The identifier for the solution-specific component (a discrete unit of logic) that generated a finding. In various security findings providers' solutions, this generator can be called a rule, a check, a detector, a plugin, or something else.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 512.</p>"""
    aws_account_id: NotRequired[
        "capo_securityhub.types.non_empty_string.NonEmptyString"
    ]
    """<p>The Amazon Web Services account ID that a finding is generated in.</p> <p>Length Constraints: 12.</p>"""
    types: NotRequired["capo_securityhub.types.type_list.TypeList"]
    """<p>One or more finding types in the format of <code>namespace/category/classifier</code> that classify a finding.</p> <p>Valid namespace values are: Software and Configuration Checks | TTPs | Effects | Unusual Behaviors | Sensitive Data Identifications</p> <p>Array Members: Maximum number of 50 items.</p>"""
    first_observed_at: NotRequired[
        "capo_securityhub.types.non_empty_string.NonEmptyString"
    ]
    """<p>Indicates when the security findings provider first observed the potential security issue that a finding captured.</p> <p>For more information about the validation and formatting of timestamp fields in Security Hub CSPM, see <a href="https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html#timestamps">Timestamps</a>.</p>"""
    last_observed_at: NotRequired[
        "capo_securityhub.types.non_empty_string.NonEmptyString"
    ]
    """<p>Indicates when the security findings provider most recently observed a change in the resource that is involved in the finding.</p> <p>For more information about the validation and formatting of timestamp fields in Security Hub CSPM, see <a href="https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html#timestamps">Timestamps</a>.</p>"""
    created_at: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>Indicates when the security findings provider created the potential security issue that a finding captured.</p> <p>For more information about the validation and formatting of timestamp fields in Security Hub CSPM, see <a href="https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html#timestamps">Timestamps</a>.</p>"""
    updated_at: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>Indicates when the security findings provider last updated the finding record.</p> <p>For more information about the validation and formatting of timestamp fields in Security Hub CSPM, see <a href="https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html#timestamps">Timestamps</a>.</p>"""
    severity: NotRequired["capo_securityhub.types.severity.Severity"]
    """<p>A finding's severity.</p>"""
    confidence: NotRequired["capo_securityhub.types.integer.Integer"]
    """<p>A finding's confidence. Confidence is defined as the likelihood that a finding accurately identifies the behavior or issue that it was intended to identify.</p> <p>Confidence is scored on a 0-100 basis using a ratio scale, where 0 means zero percent confidence and 100 means 100 percent confidence.</p>"""
    criticality: NotRequired["capo_securityhub.types.integer.Integer"]
    """<p>The level of importance assigned to the resources associated with the finding.</p> <p>A score of 0 means that the underlying resources have no criticality, and a score of 100 is reserved for the most critical resources.</p>"""
    title: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>A finding's title. <code>Title</code> is a required property.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 256.</p>"""
    description: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>A finding's description. <code>Description</code> is a required property.</p> <p>Length Constraints: Minimum length of 1. Maximum length of 1024.</p>"""
    remediation: NotRequired["capo_securityhub.types.remediation.Remediation"]
    """<p>A data type that describes the remediation options for a finding.</p>"""
    source_url: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>A URL that links to a page about the current finding in the security findings provider's solution.</p>"""
    product_fields: NotRequired["capo_securityhub.types.field_map.FieldMap"]
    """<p>A data type where security findings providers can include additional solution-specific details that aren't part of the defined <code>AwsSecurityFinding</code> format.</p> <p>Can contain up to 50 key-value pairs. For each key-value pair, the key can contain up to 128 characters, and the value can contain up to 2048 characters.</p>"""
    user_defined_fields: NotRequired["capo_securityhub.types.field_map.FieldMap"]
    """<p>A list of name/value string pairs associated with the finding. These are custom, user-defined fields added to a finding.</p> <p>Can contain up to 50 key-value pairs. For each key-value pair, the key can contain up to 128 characters, and the value can contain up to 1024 characters.</p>"""
    malware: NotRequired["capo_securityhub.types.malware_list.MalwareList"]
    """<p>A list of malware related to a finding.</p> <p>Array Members: Maximum number of 5 items.</p>"""
    network: NotRequired["capo_securityhub.types.network.Network"]
    """<p>The details of network-related information about a finding.</p>"""
    network_path: NotRequired[
        "capo_securityhub.types.network_path_list.NetworkPathList"
    ]
    """<p>Provides information about a network path that is relevant to a finding. Each entry under <code>NetworkPath</code> represents a component of that path.</p>"""
    process: NotRequired["capo_securityhub.types.process_details.ProcessDetails"]
    """<p>The details of process-related information about a finding.</p>"""
    threats: NotRequired["capo_securityhub.types.threat_list.ThreatList"]
    """<p>Details about the threat detected in a security finding and the file paths that were affected by the threat. </p> <p>Array Members: Minimum number of 1 item. Maximum number of 32 items.</p>"""
    threat_intel_indicators: NotRequired[
        "capo_securityhub.types.threat_intel_indicator_list.ThreatIntelIndicatorList"
    ]
    """<p>Threat intelligence details related to a finding.</p> <p>Array Members: Minimum number of 1 item. Maximum number of 5 items.</p>"""
    resources: NotRequired["capo_securityhub.types.resource_list.ResourceList"]
    """<p>A set of resource data types that describe the resources that the finding refers to.</p> <p>Array Members: Minimum number of 1 item. Maximum number of 32 items.</p>"""
    compliance: NotRequired["capo_securityhub.types.compliance.Compliance"]
    """<p>This data type is exclusive to findings that are generated as the result of a check run against a specific rule in a supported security standard, such as CIS Amazon Web Services Foundations. Contains security standard-related finding details.</p>"""
    verification_state: NotRequired[
        "capo_securityhub.types.verification_state.VerificationState"
    ]
    """<p>Indicates the veracity of a finding. </p>"""
    workflow_state: NotRequired["capo_securityhub.types.workflow_state.WorkflowState"]
    """<p>The workflow state of a finding. </p>"""
    workflow: NotRequired["capo_securityhub.types.workflow.Workflow"]
    """<p>Provides information about the status of the investigation into a finding.</p>"""
    record_state: NotRequired["capo_securityhub.types.record_state.RecordState"]
    """<p>The record state of a finding.</p>"""
    related_findings: NotRequired[
        "capo_securityhub.types.related_finding_list.RelatedFindingList"
    ]
    """<p>A list of related findings.</p> <p>Array Members: Minimum number of 1 item. Maximum number of 10 items.</p>"""
    note: NotRequired["capo_securityhub.types.note.Note"]
    """<p>A user-defined note added to a finding.</p>"""
    vulnerabilities: NotRequired[
        "capo_securityhub.types.vulnerability_list.VulnerabilityList"
    ]
    """<p>Provides a list of vulnerabilities associated with the findings.</p>"""
    patch_summary: NotRequired["capo_securityhub.types.patch_summary.PatchSummary"]
    """<p>Provides an overview of the patch compliance status for an instance against a selected compliance standard.</p>"""
    action: NotRequired["capo_securityhub.types.action.Action"]
    """<p>Provides details about an action that affects or that was taken on a resource.</p>"""
    finding_provider_fields: NotRequired[
        "capo_securityhub.types.finding_provider_fields.FindingProviderFields"
    ]
    """<p>In a <code>BatchImportFindings</code> request, finding providers use <code>FindingProviderFields</code> to provide and update their own values for confidence, criticality, related findings, severity, and types.</p>"""
    sample: NotRequired["capo_securityhub.types.boolean.Boolean"]
    """<p>Indicates whether the finding is a sample finding.</p>"""
    generator_details: NotRequired[
        "capo_securityhub.types.generator_details.GeneratorDetails"
    ]
    """<p>Provides metadata for the Amazon CodeGuru detector associated with a finding. This field pertains to findings that relate to Lambda functions. Amazon Inspector identifies policy violations and vulnerabilities in Lambda function code based on internal detectors developed in collaboration with Amazon CodeGuru. Security Hub CSPM receives those findings. </p>"""
    processed_at: NotRequired["capo_securityhub.types.non_empty_string.NonEmptyString"]
    """<p>A timestamp that indicates when Security Hub CSPM received a finding and begins to process it.</p> <p>For more information about the validation and formatting of timestamp fields in Security Hub CSPM, see <a href="https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html#timestamps">Timestamps</a>.</p>"""
    aws_account_name: NotRequired[
        "capo_securityhub.types.non_empty_string.NonEmptyString"
    ]
    """<p>The name of the Amazon Web Services account from which a finding was generated. </p> <p>Length Constraints: Minimum length of 1. Maximum length of 50. </p>"""
    detection: NotRequired["capo_securityhub.types.detection.Detection"]
    """<p> Provides details about an Amazon GuardDuty Extended Threat Detection attack sequence. GuardDuty generates an attack sequence finding when multiple events align to a potentially suspicious activity. To receive GuardDuty attack sequence findings in Security Hub CSPM, you must have GuardDuty enabled. For more information, see <a href="https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-extended-threat-detection.html">GuardDuty Extended Threat Detection </a> in the <i>Amazon GuardDuty User Guide</i>. </p>"""


# --- restJson1 ser/de ---
def serialize_json(value: AwsSecurityFinding) -> dict:
    out: dict = {}
    if "schema_version" in value:
        out["SchemaVersion"] = value["schema_version"]
    if "id" in value:
        out["Id"] = value["id"]
    if "product_arn" in value:
        out["ProductArn"] = value["product_arn"]
    if "product_name" in value:
        out["ProductName"] = value["product_name"]
    if "company_name" in value:
        out["CompanyName"] = value["company_name"]
    if "region" in value:
        out["Region"] = value["region"]
    if "generator_id" in value:
        out["GeneratorId"] = value["generator_id"]
    if "aws_account_id" in value:
        out["AwsAccountId"] = value["aws_account_id"]
    if "types" in value:
        import capo_securityhub.types.type_list

        out["Types"] = capo_securityhub.types.type_list.serialize_json(value["types"])
    if "first_observed_at" in value:
        out["FirstObservedAt"] = value["first_observed_at"]
    if "last_observed_at" in value:
        out["LastObservedAt"] = value["last_observed_at"]
    if "created_at" in value:
        out["CreatedAt"] = value["created_at"]
    if "updated_at" in value:
        out["UpdatedAt"] = value["updated_at"]
    if "severity" in value:
        import capo_securityhub.types.severity

        out["Severity"] = capo_securityhub.types.severity.serialize_json(
            value["severity"]
        )
    if "confidence" in value:
        out["Confidence"] = value["confidence"]
    if "criticality" in value:
        out["Criticality"] = value["criticality"]
    if "title" in value:
        out["Title"] = value["title"]
    if "description" in value:
        out["Description"] = value["description"]
    if "remediation" in value:
        import capo_securityhub.types.remediation

        out["Remediation"] = capo_securityhub.types.remediation.serialize_json(
            value["remediation"]
        )
    if "source_url" in value:
        out["SourceUrl"] = value["source_url"]
    if "product_fields" in value:
        import capo_securityhub.types.field_map

        out["ProductFields"] = capo_securityhub.types.field_map.serialize_json(
            value["product_fields"]
        )
    if "user_defined_fields" in value:
        import capo_securityhub.types.field_map

        out["UserDefinedFields"] = capo_securityhub.types.field_map.serialize_json(
            value["user_defined_fields"]
        )
    if "malware" in value:
        import capo_securityhub.types.malware_list

        out["Malware"] = capo_securityhub.types.malware_list.serialize_json(
            value["malware"]
        )
    if "network" in value:
        import capo_securityhub.types.network

        out["Network"] = capo_securityhub.types.network.serialize_json(value["network"])
    if "network_path" in value:
        import capo_securityhub.types.network_path_list

        out["NetworkPath"] = capo_securityhub.types.network_path_list.serialize_json(
            value["network_path"]
        )
    if "process" in value:
        import capo_securityhub.types.process_details

        out["Process"] = capo_securityhub.types.process_details.serialize_json(
            value["process"]
        )
    if "threats" in value:
        import capo_securityhub.types.threat_list

        out["Threats"] = capo_securityhub.types.threat_list.serialize_json(
            value["threats"]
        )
    if "threat_intel_indicators" in value:
        import capo_securityhub.types.threat_intel_indicator_list

        out["ThreatIntelIndicators"] = (
            capo_securityhub.types.threat_intel_indicator_list.serialize_json(
                value["threat_intel_indicators"]
            )
        )
    if "resources" in value:
        import capo_securityhub.types.resource_list

        out["Resources"] = capo_securityhub.types.resource_list.serialize_json(
            value["resources"]
        )
    if "compliance" in value:
        import capo_securityhub.types.compliance

        out["Compliance"] = capo_securityhub.types.compliance.serialize_json(
            value["compliance"]
        )
    if "verification_state" in value:
        import capo_securityhub.types.verification_state

        out["VerificationState"] = (
            capo_securityhub.types.verification_state.serialize_json(
                value["verification_state"]
            )
        )
    if "workflow_state" in value:
        import capo_securityhub.types.workflow_state

        out["WorkflowState"] = capo_securityhub.types.workflow_state.serialize_json(
            value["workflow_state"]
        )
    if "workflow" in value:
        import capo_securityhub.types.workflow

        out["Workflow"] = capo_securityhub.types.workflow.serialize_json(
            value["workflow"]
        )
    if "record_state" in value:
        import capo_securityhub.types.record_state

        out["RecordState"] = capo_securityhub.types.record_state.serialize_json(
            value["record_state"]
        )
    if "related_findings" in value:
        import capo_securityhub.types.related_finding_list

        out["RelatedFindings"] = (
            capo_securityhub.types.related_finding_list.serialize_json(
                value["related_findings"]
            )
        )
    if "note" in value:
        import capo_securityhub.types.note

        out["Note"] = capo_securityhub.types.note.serialize_json(value["note"])
    if "vulnerabilities" in value:
        import capo_securityhub.types.vulnerability_list

        out["Vulnerabilities"] = (
            capo_securityhub.types.vulnerability_list.serialize_json(
                value["vulnerabilities"]
            )
        )
    if "patch_summary" in value:
        import capo_securityhub.types.patch_summary

        out["PatchSummary"] = capo_securityhub.types.patch_summary.serialize_json(
            value["patch_summary"]
        )
    if "action" in value:
        import capo_securityhub.types.action

        out["Action"] = capo_securityhub.types.action.serialize_json(value["action"])
    if "finding_provider_fields" in value:
        import capo_securityhub.types.finding_provider_fields

        out["FindingProviderFields"] = (
            capo_securityhub.types.finding_provider_fields.serialize_json(
                value["finding_provider_fields"]
            )
        )
    if "sample" in value:
        out["Sample"] = value["sample"]
    if "generator_details" in value:
        import capo_securityhub.types.generator_details

        out["GeneratorDetails"] = (
            capo_securityhub.types.generator_details.serialize_json(
                value["generator_details"]
            )
        )
    if "processed_at" in value:
        out["ProcessedAt"] = value["processed_at"]
    if "aws_account_name" in value:
        out["AwsAccountName"] = value["aws_account_name"]
    if "detection" in value:
        import capo_securityhub.types.detection

        out["Detection"] = capo_securityhub.types.detection.serialize_json(
            value["detection"]
        )
    return out


def deserialize_json(data: dict) -> AwsSecurityFinding:
    out: AwsSecurityFinding = {}  # type: ignore[typeddict-item]
    if data.get("SchemaVersion") is not None:
        out["schema_version"] = data["SchemaVersion"]
    if data.get("Id") is not None:
        out["id"] = data["Id"]
    if data.get("ProductArn") is not None:
        out["product_arn"] = data["ProductArn"]
    if data.get("ProductName") is not None:
        out["product_name"] = data["ProductName"]
    if data.get("CompanyName") is not None:
        out["company_name"] = data["CompanyName"]
    if data.get("Region") is not None:
        out["region"] = data["Region"]
    if data.get("GeneratorId") is not None:
        out["generator_id"] = data["GeneratorId"]
    if data.get("AwsAccountId") is not None:
        out["aws_account_id"] = data["AwsAccountId"]
    if data.get("Types") is not None:
        import capo_securityhub.types.type_list

        out["types"] = capo_securityhub.types.type_list.deserialize_json(data["Types"])
    if data.get("FirstObservedAt") is not None:
        out["first_observed_at"] = data["FirstObservedAt"]
    if data.get("LastObservedAt") is not None:
        out["last_observed_at"] = data["LastObservedAt"]
    if data.get("CreatedAt") is not None:
        out["created_at"] = data["CreatedAt"]
    if data.get("UpdatedAt") is not None:
        out["updated_at"] = data["UpdatedAt"]
    if data.get("Severity") is not None:
        import capo_securityhub.types.severity

        out["severity"] = capo_securityhub.types.severity.deserialize_json(
            data["Severity"]
        )
    if data.get("Confidence") is not None:
        out["confidence"] = data["Confidence"]
    if data.get("Criticality") is not None:
        out["criticality"] = data["Criticality"]
    if data.get("Title") is not None:
        out["title"] = data["Title"]
    if data.get("Description") is not None:
        out["description"] = data["Description"]
    if data.get("Remediation") is not None:
        import capo_securityhub.types.remediation

        out["remediation"] = capo_securityhub.types.remediation.deserialize_json(
            data["Remediation"]
        )
    if data.get("SourceUrl") is not None:
        out["source_url"] = data["SourceUrl"]
    if data.get("ProductFields") is not None:
        import capo_securityhub.types.field_map

        out["product_fields"] = capo_securityhub.types.field_map.deserialize_json(
            data["ProductFields"]
        )
    if data.get("UserDefinedFields") is not None:
        import capo_securityhub.types.field_map

        out["user_defined_fields"] = capo_securityhub.types.field_map.deserialize_json(
            data["UserDefinedFields"]
        )
    if data.get("Malware") is not None:
        import capo_securityhub.types.malware_list

        out["malware"] = capo_securityhub.types.malware_list.deserialize_json(
            data["Malware"]
        )
    if data.get("Network") is not None:
        import capo_securityhub.types.network

        out["network"] = capo_securityhub.types.network.deserialize_json(
            data["Network"]
        )
    if data.get("NetworkPath") is not None:
        import capo_securityhub.types.network_path_list

        out["network_path"] = capo_securityhub.types.network_path_list.deserialize_json(
            data["NetworkPath"]
        )
    if data.get("Process") is not None:
        import capo_securityhub.types.process_details

        out["process"] = capo_securityhub.types.process_details.deserialize_json(
            data["Process"]
        )
    if data.get("Threats") is not None:
        import capo_securityhub.types.threat_list

        out["threats"] = capo_securityhub.types.threat_list.deserialize_json(
            data["Threats"]
        )
    if data.get("ThreatIntelIndicators") is not None:
        import capo_securityhub.types.threat_intel_indicator_list

        out["threat_intel_indicators"] = (
            capo_securityhub.types.threat_intel_indicator_list.deserialize_json(
                data["ThreatIntelIndicators"]
            )
        )
    if data.get("Resources") is not None:
        import capo_securityhub.types.resource_list

        out["resources"] = capo_securityhub.types.resource_list.deserialize_json(
            data["Resources"]
        )
    if data.get("Compliance") is not None:
        import capo_securityhub.types.compliance

        out["compliance"] = capo_securityhub.types.compliance.deserialize_json(
            data["Compliance"]
        )
    if data.get("VerificationState") is not None:
        import capo_securityhub.types.verification_state

        out["verification_state"] = (
            capo_securityhub.types.verification_state.deserialize_json(
                data["VerificationState"]
            )
        )
    if data.get("WorkflowState") is not None:
        import capo_securityhub.types.workflow_state

        out["workflow_state"] = capo_securityhub.types.workflow_state.deserialize_json(
            data["WorkflowState"]
        )
    if data.get("Workflow") is not None:
        import capo_securityhub.types.workflow

        out["workflow"] = capo_securityhub.types.workflow.deserialize_json(
            data["Workflow"]
        )
    if data.get("RecordState") is not None:
        import capo_securityhub.types.record_state

        out["record_state"] = capo_securityhub.types.record_state.deserialize_json(
            data["RecordState"]
        )
    if data.get("RelatedFindings") is not None:
        import capo_securityhub.types.related_finding_list

        out["related_findings"] = (
            capo_securityhub.types.related_finding_list.deserialize_json(
                data["RelatedFindings"]
            )
        )
    if data.get("Note") is not None:
        import capo_securityhub.types.note

        out["note"] = capo_securityhub.types.note.deserialize_json(data["Note"])
    if data.get("Vulnerabilities") is not None:
        import capo_securityhub.types.vulnerability_list

        out["vulnerabilities"] = (
            capo_securityhub.types.vulnerability_list.deserialize_json(
                data["Vulnerabilities"]
            )
        )
    if data.get("PatchSummary") is not None:
        import capo_securityhub.types.patch_summary

        out["patch_summary"] = capo_securityhub.types.patch_summary.deserialize_json(
            data["PatchSummary"]
        )
    if data.get("Action") is not None:
        import capo_securityhub.types.action

        out["action"] = capo_securityhub.types.action.deserialize_json(data["Action"])
    if data.get("FindingProviderFields") is not None:
        import capo_securityhub.types.finding_provider_fields

        out["finding_provider_fields"] = (
            capo_securityhub.types.finding_provider_fields.deserialize_json(
                data["FindingProviderFields"]
            )
        )
    if data.get("Sample") is not None:
        out["sample"] = data["Sample"]
    if data.get("GeneratorDetails") is not None:
        import capo_securityhub.types.generator_details

        out["generator_details"] = (
            capo_securityhub.types.generator_details.deserialize_json(
                data["GeneratorDetails"]
            )
        )
    if data.get("ProcessedAt") is not None:
        out["processed_at"] = data["ProcessedAt"]
    if data.get("AwsAccountName") is not None:
        out["aws_account_name"] = data["AwsAccountName"]
    if data.get("Detection") is not None:
        import capo_securityhub.types.detection

        out["detection"] = capo_securityhub.types.detection.deserialize_json(
            data["Detection"]
        )
    return out
