"""Generated from Smithy shape ``com.amazonaws.apigateway#DocumentationPart``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_api_gateway.types.documentation_part_location
    import capo_api_gateway.types.string


class DocumentationPart(TypedDict, closed=True):
    id: NotRequired["capo_api_gateway.types.string.String"]
    """<p>The DocumentationPart identifier, generated by API Gateway when the <code>DocumentationPart</code> is created.</p>"""
    location: NotRequired[
        "capo_api_gateway.types.documentation_part_location.DocumentationPartLocation"
    ]
    """<p>The location of the API entity to which the documentation applies. Valid fields depend on the targeted API entity type. All the valid location fields are not required. If not explicitly specified, a valid location field is treated as a wildcard and associated documentation content may be inherited by matching entities, unless overridden.</p>"""
    properties: NotRequired["capo_api_gateway.types.string.String"]
    r"""<p>A content map of API-specific key-value pairs describing the targeted API entity. The map must be encoded as a JSON string, e.g., <code>"{ \"description\": \"The API does ...\" }"</code>. Only OpenAPI-compliant documentation-related fields from the properties map are exported and, hence, published as part of the API entity definitions, while the original documentation parts are exported in a OpenAPI extension of <code>x-amazon-apigateway-documentation</code>.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: DocumentationPart) -> dict:
    out: dict = {}
    if "id" in value:
        out["id"] = value["id"]
    if "location" in value:
        import capo_api_gateway.types.documentation_part_location

        out["location"] = (
            capo_api_gateway.types.documentation_part_location.serialize_json(
                value["location"]
            )
        )
    if "properties" in value:
        out["properties"] = value["properties"]
    return out


def deserialize_json(data: dict) -> DocumentationPart:
    out: DocumentationPart = {}  # type: ignore[typeddict-item]
    if data.get("id") is not None:
        out["id"] = data["id"]
    if data.get("location") is not None:
        import capo_api_gateway.types.documentation_part_location

        out["location"] = (
            capo_api_gateway.types.documentation_part_location.deserialize_json(
                data["location"]
            )
        )
    if data.get("properties") is not None:
        out["properties"] = data["properties"]
    return out
