"""Generated from Smithy shape ``com.amazonaws.sfn#SendTaskFailureInput``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_sfn.errors import DeserializationError

if TYPE_CHECKING:
    import capo_sfn.types.sensitive_cause
    import capo_sfn.types.sensitive_error
    import capo_sfn.types.task_token


class SendTaskFailureInput(TypedDict, closed=True):
    task_token: "capo_sfn.types.task_token.TaskToken"
    """<p>The token that represents this task. Task tokens are generated by Step Functions when tasks are assigned to a worker, or in the <a href="https://docs.aws.amazon.com/step-functions/latest/dg/input-output-contextobject.html">context object</a> when a workflow enters a task state. See <a>GetActivityTaskOutput$taskToken</a>.</p>"""
    error: NotRequired["capo_sfn.types.sensitive_error.SensitiveError"]
    """<p>The error code of the failure.</p>"""
    cause: NotRequired["capo_sfn.types.sensitive_cause.SensitiveCause"]
    """<p>A more detailed explanation of the cause of the failure.</p>"""


# --- awsJson1_0 ser/de ---
def serialize_aws_json_1_0(value: SendTaskFailureInput) -> dict:
    out: dict = {}
    out["taskToken"] = value["task_token"]
    if "error" in value:
        out["error"] = value["error"]
    if "cause" in value:
        out["cause"] = value["cause"]
    return out


def deserialize_aws_json_1_0(data: dict) -> SendTaskFailureInput:
    out: SendTaskFailureInput = {}  # type: ignore[typeddict-item]
    if data.get("taskToken") is not None:
        out["task_token"] = data["taskToken"]
    else:
        raise DeserializationError("SendTaskFailureInput.task_token required")
    if data.get("error") is not None:
        out["error"] = data["error"]
    if data.get("cause") is not None:
        out["cause"] = data["cause"]
    return out
