"""Generated from Smithy shape ``com.amazonaws.kms#VerifyMacRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_kms.errors import DeserializationError

if TYPE_CHECKING:
    import capo_kms.types.ciphertext_type
    import capo_kms.types.grant_token_list
    import capo_kms.types.key_id_type
    import capo_kms.types.mac_algorithm_spec
    import capo_kms.types.nullable_boolean_type
    import capo_kms.types.plaintext_type


class VerifyMacRequest(TypedDict, closed=True):
    message: "capo_kms.types.plaintext_type.PlaintextType"
    """<p>The message that will be used in the verification. Enter the same message that was used to generate the HMAC.</p> <p> <a>GenerateMac</a> and <code>VerifyMac</code> do not provide special handling for message digests. If you generated an HMAC for a hash digest of a message, you must verify the HMAC for the same hash digest.</p>"""
    key_id: "capo_kms.types.key_id_type.KeyIdType"
    """<p>The KMS key that will be used in the verification.</p> <p>Enter a key ID of the KMS key that was used to generate the HMAC. If you identify a different KMS key, the <code>VerifyMac</code> operation fails.</p>"""
    mac_algorithm: "capo_kms.types.mac_algorithm_spec.MacAlgorithmSpec"
    """<p>The MAC algorithm that will be used in the verification. Enter the same MAC algorithm that was used to compute the HMAC. This algorithm must be supported by the HMAC KMS key identified by the <code>KeyId</code> parameter.</p>"""
    mac: "capo_kms.types.ciphertext_type.CiphertextType"
    """<p>The HMAC to verify. Enter the HMAC that was generated by the <a>GenerateMac</a> operation when you specified the same message, HMAC KMS key, and MAC algorithm as the values specified in this request.</p>"""
    grant_tokens: NotRequired["capo_kms.types.grant_token_list.GrantTokenList"]
    """<p>A list of grant tokens.</p> <p>Use a grant token when your permission to call this operation comes from a new grant that has not yet achieved <i>eventual consistency</i>. For more information, see <a href="https://docs.aws.amazon.com/kms/latest/developerguide/grants.html#grant_token">Grant token</a> and <a href="https://docs.aws.amazon.com/kms/latest/developerguide/using-grant-token.html">Using a grant token</a> in the <i>Key Management Service Developer Guide</i>.</p>"""
    dry_run: NotRequired["capo_kms.types.nullable_boolean_type.NullableBooleanType"]
    """<p>Checks if your request will succeed. <code>DryRun</code> is an optional parameter. </p> <p>To learn more about how to use this parameter, see <a href="https://docs.aws.amazon.com/kms/latest/developerguide/testing-permissions.html">Testing your permissions</a> in the <i>Key Management Service Developer Guide</i>.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: VerifyMacRequest) -> dict:
    out: dict = {}
    import capo_kms.types.plaintext_type

    out["Message"] = capo_kms.types.plaintext_type.serialize_aws_json_1_1(
        value["message"]
    )
    out["KeyId"] = value["key_id"]
    import capo_kms.types.mac_algorithm_spec

    out["MacAlgorithm"] = capo_kms.types.mac_algorithm_spec.serialize_aws_json_1_1(
        value["mac_algorithm"]
    )
    import capo_kms.types.ciphertext_type

    out["Mac"] = capo_kms.types.ciphertext_type.serialize_aws_json_1_1(value["mac"])
    if "grant_tokens" in value:
        import capo_kms.types.grant_token_list

        out["GrantTokens"] = capo_kms.types.grant_token_list.serialize_aws_json_1_1(
            value["grant_tokens"]
        )
    if "dry_run" in value:
        out["DryRun"] = value["dry_run"]
    return out


def deserialize_aws_json_1_1(data: dict) -> VerifyMacRequest:
    out: VerifyMacRequest = {}  # type: ignore[typeddict-item]
    if data.get("Message") is not None:
        import capo_kms.types.plaintext_type

        out["message"] = capo_kms.types.plaintext_type.deserialize_aws_json_1_1(
            data["Message"]
        )
    else:
        raise DeserializationError("VerifyMacRequest.message required")
    if data.get("KeyId") is not None:
        out["key_id"] = data["KeyId"]
    else:
        raise DeserializationError("VerifyMacRequest.key_id required")
    if data.get("MacAlgorithm") is not None:
        import capo_kms.types.mac_algorithm_spec

        out["mac_algorithm"] = (
            capo_kms.types.mac_algorithm_spec.deserialize_aws_json_1_1(
                data["MacAlgorithm"]
            )
        )
    else:
        raise DeserializationError("VerifyMacRequest.mac_algorithm required")
    if data.get("Mac") is not None:
        import capo_kms.types.ciphertext_type

        out["mac"] = capo_kms.types.ciphertext_type.deserialize_aws_json_1_1(
            data["Mac"]
        )
    else:
        raise DeserializationError("VerifyMacRequest.mac required")
    if data.get("GrantTokens") is not None:
        import capo_kms.types.grant_token_list

        out["grant_tokens"] = capo_kms.types.grant_token_list.deserialize_aws_json_1_1(
            data["GrantTokens"]
        )
    if data.get("DryRun") is not None:
        out["dry_run"] = data["DryRun"]
    return out
