"""Generated from Smithy shape ``com.amazonaws.notificationscontacts#ActivateEmailContactRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import TypedDict

if TYPE_CHECKING:
    import capo_notificationscontacts.types.email_contact_arn
    import capo_notificationscontacts.types.token


class ActivateEmailContactRequest(TypedDict, closed=True):
    arn: "capo_notificationscontacts.types.email_contact_arn.EmailContactArn"
    """<p>The Amazon Resource Name (ARN) of the resource.</p>"""
    code: "capo_notificationscontacts.types.token.Token"
    """<p>The activation code for this email contact.</p> <p>An email contact has a maximum of five activation attempts. Activation codes expire after 12 hours and are generated by the <a href="https://docs.aws.amazon.com/notificationscontacts/latest/APIReference/API_SendActivationCode.html">SendActivationCode</a> API action.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ActivateEmailContactRequest) -> dict:
    out: dict = {}
    return out


def deserialize_json(data: dict) -> ActivateEmailContactRequest:
    out: ActivateEmailContactRequest = {}  # type: ignore[typeddict-item]
    return out
