"""Generated from Smithy shape ``com.amazonaws.cloudwatchlogs#Anomaly``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_cloudwatch_logs.errors import DeserializationError

if TYPE_CHECKING:
    import capo_cloudwatch_logs.types.anomaly_detector_arn
    import capo_cloudwatch_logs.types.anomaly_id
    import capo_cloudwatch_logs.types.boolean
    import capo_cloudwatch_logs.types.description
    import capo_cloudwatch_logs.types.epoch_millis
    import capo_cloudwatch_logs.types.histogram
    import capo_cloudwatch_logs.types.log_group_arn_list
    import capo_cloudwatch_logs.types.log_samples
    import capo_cloudwatch_logs.types.pattern_id
    import capo_cloudwatch_logs.types.pattern_regex
    import capo_cloudwatch_logs.types.pattern_string
    import capo_cloudwatch_logs.types.pattern_tokens
    import capo_cloudwatch_logs.types.priority
    import capo_cloudwatch_logs.types.state


class Anomaly(TypedDict, closed=True):
    anomaly_id: "capo_cloudwatch_logs.types.anomaly_id.AnomalyId"
    """<p>The unique ID that CloudWatch Logs assigned to this anomaly.</p>"""
    pattern_id: "capo_cloudwatch_logs.types.pattern_id.PatternId"
    """<p>The ID of the pattern used to help identify this anomaly.</p>"""
    anomaly_detector_arn: (
        "capo_cloudwatch_logs.types.anomaly_detector_arn.AnomalyDetectorArn"
    )
    """<p>The ARN of the anomaly detector that identified this anomaly.</p>"""
    pattern_string: "capo_cloudwatch_logs.types.pattern_string.PatternString"
    """<p>The pattern used to help identify this anomaly, in string format.</p>"""
    pattern_regex: NotRequired["capo_cloudwatch_logs.types.pattern_regex.PatternRegex"]
    """<p>The pattern used to help identify this anomaly, in regular expression format.</p>"""
    priority: NotRequired["capo_cloudwatch_logs.types.priority.Priority"]
    """<p>The priority level of this anomaly, as determined by CloudWatch Logs. Priority is computed based on log severity labels such as <code>FATAL</code> and <code>ERROR</code> and the amount of deviation from the baseline. Possible values are <code>HIGH</code>, <code>MEDIUM</code>, and <code>LOW</code>.</p>"""
    first_seen: "capo_cloudwatch_logs.types.epoch_millis.EpochMillis"
    """<p>The date and time when the anomaly detector first saw this anomaly. It is specified as epoch time, which is the number of seconds since <code>January 1, 1970, 00:00:00 UTC</code>.</p>"""
    last_seen: "capo_cloudwatch_logs.types.epoch_millis.EpochMillis"
    """<p>The date and time when the anomaly detector most recently saw this anomaly. It is specified as epoch time, which is the number of seconds since <code>January 1, 1970, 00:00:00 UTC</code>.</p>"""
    description: "capo_cloudwatch_logs.types.description.Description"
    """<p>A human-readable description of the anomaly. This description is generated by CloudWatch Logs.</p>"""
    active: "capo_cloudwatch_logs.types.boolean.Boolean"
    """<p>Specifies whether this anomaly is still ongoing.</p>"""
    state: "capo_cloudwatch_logs.types.state.State"
    """<p>Indicates the current state of this anomaly. If it is still being treated as an anomaly, the value is <code>Active</code>. If you have suppressed this anomaly by using the <a href="https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_UpdateAnomaly.html">UpdateAnomaly</a> operation, the value is <code>Suppressed</code>. If this behavior is now considered to be normal, the value is <code>Baseline</code>.</p>"""
    histogram: "capo_cloudwatch_logs.types.histogram.Histogram"
    """<p>A map showing times when the anomaly detector ran, and the number of occurrences of this anomaly that were detected at each of those runs. The times are specified in epoch time, which is the number of seconds since <code>January 1, 1970, 00:00:00 UTC</code>.</p>"""
    log_samples: "capo_cloudwatch_logs.types.log_samples.LogSamples"
    """<p>An array of sample log event messages that are considered to be part of this anomaly.</p>"""
    pattern_tokens: "capo_cloudwatch_logs.types.pattern_tokens.PatternTokens"
    """<p>An array of structures where each structure contains information about one token that makes up the pattern.</p>"""
    log_group_arn_list: "capo_cloudwatch_logs.types.log_group_arn_list.LogGroupArnList"
    """<p>An array of ARNS of the log groups that contained log events considered to be part of this anomaly.</p>"""
    suppressed: NotRequired["capo_cloudwatch_logs.types.boolean.Boolean"]
    """<p>Indicates whether this anomaly is currently suppressed. To suppress an anomaly, use <a href="https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_UpdateAnomaly.html">UpdateAnomaly</a>.</p>"""
    suppressed_date: "capo_cloudwatch_logs.types.epoch_millis.EpochMillis"
    """<p>If the anomaly is suppressed, this indicates when it was suppressed.</p>"""
    suppressed_until: "capo_cloudwatch_logs.types.epoch_millis.EpochMillis"
    """<p>If the anomaly is suppressed, this indicates when the suppression will end. If this value is <code>0</code>, the anomaly was suppressed with no expiration, with the <code>INFINITE</code> value.</p>"""
    is_pattern_level_suppression: NotRequired[
        "capo_cloudwatch_logs.types.boolean.Boolean"
    ]
    """<p>If this anomaly is suppressed, this field is <code>true</code> if the suppression is because the pattern is suppressed. If <code>false</code>, then only this particular anomaly is suppressed.</p>"""


# --- awsJson1_1 ser/de ---
def serialize_aws_json_1_1(value: Anomaly) -> dict:
    out: dict = {}
    out["anomalyId"] = value["anomaly_id"]
    out["patternId"] = value["pattern_id"]
    out["anomalyDetectorArn"] = value["anomaly_detector_arn"]
    out["patternString"] = value["pattern_string"]
    if "pattern_regex" in value:
        out["patternRegex"] = value["pattern_regex"]
    if "priority" in value:
        out["priority"] = value["priority"]
    out["firstSeen"] = value.get("first_seen", 0)
    out["lastSeen"] = value.get("last_seen", 0)
    out["description"] = value["description"]
    out["active"] = value["active"]
    import capo_cloudwatch_logs.types.state

    out["state"] = capo_cloudwatch_logs.types.state.serialize_aws_json_1_1(
        value["state"]
    )
    import capo_cloudwatch_logs.types.histogram

    out["histogram"] = capo_cloudwatch_logs.types.histogram.serialize_aws_json_1_1(
        value["histogram"]
    )
    import capo_cloudwatch_logs.types.log_samples

    out["logSamples"] = capo_cloudwatch_logs.types.log_samples.serialize_aws_json_1_1(
        value["log_samples"]
    )
    import capo_cloudwatch_logs.types.pattern_tokens

    out["patternTokens"] = (
        capo_cloudwatch_logs.types.pattern_tokens.serialize_aws_json_1_1(
            value["pattern_tokens"]
        )
    )
    import capo_cloudwatch_logs.types.log_group_arn_list

    out["logGroupArnList"] = (
        capo_cloudwatch_logs.types.log_group_arn_list.serialize_aws_json_1_1(
            value["log_group_arn_list"]
        )
    )
    if "suppressed" in value:
        out["suppressed"] = value["suppressed"]
    out["suppressedDate"] = value.get("suppressed_date", 0)
    out["suppressedUntil"] = value.get("suppressed_until", 0)
    if "is_pattern_level_suppression" in value:
        out["isPatternLevelSuppression"] = value["is_pattern_level_suppression"]
    return out


def deserialize_aws_json_1_1(data: dict) -> Anomaly:
    out: Anomaly = {}  # type: ignore[typeddict-item]
    if data.get("anomalyId") is not None:
        out["anomaly_id"] = data["anomalyId"]
    else:
        raise DeserializationError("Anomaly.anomaly_id required")
    if data.get("patternId") is not None:
        out["pattern_id"] = data["patternId"]
    else:
        raise DeserializationError("Anomaly.pattern_id required")
    if data.get("anomalyDetectorArn") is not None:
        out["anomaly_detector_arn"] = data["anomalyDetectorArn"]
    else:
        raise DeserializationError("Anomaly.anomaly_detector_arn required")
    if data.get("patternString") is not None:
        out["pattern_string"] = data["patternString"]
    else:
        raise DeserializationError("Anomaly.pattern_string required")
    if data.get("patternRegex") is not None:
        out["pattern_regex"] = data["patternRegex"]
    if data.get("priority") is not None:
        out["priority"] = data["priority"]
    if data.get("firstSeen") is not None:
        out["first_seen"] = data["firstSeen"]
    else:
        out["first_seen"] = 0
    if data.get("lastSeen") is not None:
        out["last_seen"] = data["lastSeen"]
    else:
        out["last_seen"] = 0
    if data.get("description") is not None:
        out["description"] = data["description"]
    else:
        raise DeserializationError("Anomaly.description required")
    if data.get("active") is not None:
        out["active"] = data["active"]
    else:
        raise DeserializationError("Anomaly.active required")
    if data.get("state") is not None:
        import capo_cloudwatch_logs.types.state

        out["state"] = capo_cloudwatch_logs.types.state.deserialize_aws_json_1_1(
            data["state"]
        )
    else:
        raise DeserializationError("Anomaly.state required")
    if data.get("histogram") is not None:
        import capo_cloudwatch_logs.types.histogram

        out["histogram"] = (
            capo_cloudwatch_logs.types.histogram.deserialize_aws_json_1_1(
                data["histogram"]
            )
        )
    else:
        raise DeserializationError("Anomaly.histogram required")
    if data.get("logSamples") is not None:
        import capo_cloudwatch_logs.types.log_samples

        out["log_samples"] = (
            capo_cloudwatch_logs.types.log_samples.deserialize_aws_json_1_1(
                data["logSamples"]
            )
        )
    else:
        raise DeserializationError("Anomaly.log_samples required")
    if data.get("patternTokens") is not None:
        import capo_cloudwatch_logs.types.pattern_tokens

        out["pattern_tokens"] = (
            capo_cloudwatch_logs.types.pattern_tokens.deserialize_aws_json_1_1(
                data["patternTokens"]
            )
        )
    else:
        raise DeserializationError("Anomaly.pattern_tokens required")
    if data.get("logGroupArnList") is not None:
        import capo_cloudwatch_logs.types.log_group_arn_list

        out["log_group_arn_list"] = (
            capo_cloudwatch_logs.types.log_group_arn_list.deserialize_aws_json_1_1(
                data["logGroupArnList"]
            )
        )
    else:
        raise DeserializationError("Anomaly.log_group_arn_list required")
    if data.get("suppressed") is not None:
        out["suppressed"] = data["suppressed"]
    if data.get("suppressedDate") is not None:
        out["suppressed_date"] = data["suppressedDate"]
    else:
        out["suppressed_date"] = 0
    if data.get("suppressedUntil") is not None:
        out["suppressed_until"] = data["suppressedUntil"]
    else:
        out["suppressed_until"] = 0
    if data.get("isPatternLevelSuppression") is not None:
        out["is_pattern_level_suppression"] = data["isPatternLevelSuppression"]
    return out
