"""Generated from Smithy shape ``com.amazonaws.detective#ListIndicatorsRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_detective.errors import DeserializationError

if TYPE_CHECKING:
    import capo_detective.types.ai_pagination_token
    import capo_detective.types.graph_arn
    import capo_detective.types.indicator_type
    import capo_detective.types.investigation_id
    import capo_detective.types.max_results


class ListIndicatorsRequest(TypedDict, closed=True):
    graph_arn: "capo_detective.types.graph_arn.GraphArn"
    """<p>The Amazon Resource Name (ARN) of the behavior graph.</p>"""
    investigation_id: "capo_detective.types.investigation_id.InvestigationId"
    """<p>The investigation ID of the investigation report.</p>"""
    indicator_type: NotRequired["capo_detective.types.indicator_type.IndicatorType"]
    """<p>For the list of indicators of compromise that are generated by Detective investigations, see <a href="https://docs.aws.amazon.com/detective/latest/userguide/detective-investigation-about.html">Detective investigations</a>.</p>"""
    next_token: NotRequired[
        "capo_detective.types.ai_pagination_token.AiPaginationToken"
    ]
    """<p>Lists if there are more results available. The value of nextToken is a unique pagination token for each page. Repeat the call using the returned token to retrieve the next page. Keep all other arguments unchanged.</p> <p>Each pagination token expires after 24 hours. Using an expired pagination token will return a Validation Exception error.</p>"""
    max_results: NotRequired["capo_detective.types.max_results.MaxResults"]
    """<p>Lists the maximum number of indicators in a page.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: ListIndicatorsRequest) -> dict:
    out: dict = {}
    out["GraphArn"] = value["graph_arn"]
    out["InvestigationId"] = value["investigation_id"]
    if "indicator_type" in value:
        import capo_detective.types.indicator_type

        out["IndicatorType"] = capo_detective.types.indicator_type.serialize_json(
            value["indicator_type"]
        )
    if "next_token" in value:
        out["NextToken"] = value["next_token"]
    if "max_results" in value:
        out["MaxResults"] = value["max_results"]
    return out


def deserialize_json(data: dict) -> ListIndicatorsRequest:
    out: ListIndicatorsRequest = {}  # type: ignore[typeddict-item]
    if data.get("GraphArn") is not None:
        out["graph_arn"] = data["GraphArn"]
    else:
        raise DeserializationError("ListIndicatorsRequest.graph_arn required")
    if data.get("InvestigationId") is not None:
        out["investigation_id"] = data["InvestigationId"]
    else:
        raise DeserializationError("ListIndicatorsRequest.investigation_id required")
    if data.get("IndicatorType") is not None:
        import capo_detective.types.indicator_type

        out["indicator_type"] = capo_detective.types.indicator_type.deserialize_json(
            data["IndicatorType"]
        )
    if data.get("NextToken") is not None:
        out["next_token"] = data["NextToken"]
    if data.get("MaxResults") is not None:
        out["max_results"] = data["MaxResults"]
    return out
