"""Generated from Smithy shape ``com.amazonaws.rds#CreateEventSubscriptionMessage``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_rds._protocol.xml import Element

if TYPE_CHECKING:
    import capo_rds.types.boolean_optional
    import capo_rds.types.event_categories_list
    import capo_rds.types.source_ids_list
    import capo_rds.types.string
    import capo_rds.types.tag_list


class CreateEventSubscriptionMessage(TypedDict, closed=True):
    subscription_name: NotRequired["capo_rds.types.string.String"]
    """<p>The name of the subscription.</p> <p>Constraints: The name must be less than 255 characters.</p>"""
    sns_topic_arn: NotRequired["capo_rds.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the SNS topic created for event notification. SNS automatically creates the ARN when you create a topic and subscribe to it.</p> <note> <p>RDS doesn't support FIFO (first in, first out) topics. For more information, see <a href="https://docs.aws.amazon.com/sns/latest/dg/sns-fifo-topics.html">Message ordering and deduplication (FIFO topics)</a> in the <i>Amazon Simple Notification Service Developer Guide</i>.</p> </note>"""
    source_type: NotRequired["capo_rds.types.string.String"]
    """<p>The type of source that is generating the events. For example, if you want to be notified of events generated by a DB instance, you set this parameter to <code>db-instance</code>. For RDS Proxy events, specify <code>db-proxy</code>. If this value isn't specified, all events are returned.</p> <p>Valid Values:<code> db-instance | db-cluster | db-parameter-group | db-security-group | db-snapshot | db-cluster-snapshot | db-proxy | zero-etl | custom-engine-version | blue-green-deployment </code> </p>"""
    event_categories: NotRequired[
        "capo_rds.types.event_categories_list.EventCategoriesList"
    ]
    """<p>A list of event categories for a particular source type (<code>SourceType</code>) that you want to subscribe to. You can see a list of the categories for a given source type in the "Amazon RDS event categories and event messages" section of the <a href="https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.Messages.html"> <i>Amazon RDS User Guide</i> </a> or the <a href="https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_Events.Messages.html"> <i>Amazon Aurora User Guide</i> </a>. You can also see this list by using the <code>DescribeEventCategories</code> operation.</p>"""
    source_ids: NotRequired["capo_rds.types.source_ids_list.SourceIdsList"]
    """<p>The list of identifiers of the event sources for which events are returned. If not specified, then all sources are included in the response. An identifier must begin with a letter and must contain only ASCII letters, digits, and hyphens. It can't end with a hyphen or contain two consecutive hyphens.</p> <p>Constraints:</p> <ul> <li> <p>If <code>SourceIds</code> are supplied, <code>SourceType</code> must also be provided.</p> </li> <li> <p>If the source type is a DB instance, a <code>DBInstanceIdentifier</code> value must be supplied.</p> </li> <li> <p>If the source type is a DB cluster, a <code>DBClusterIdentifier</code> value must be supplied.</p> </li> <li> <p>If the source type is a DB parameter group, a <code>DBParameterGroupName</code> value must be supplied.</p> </li> <li> <p>If the source type is a DB security group, a <code>DBSecurityGroupName</code> value must be supplied.</p> </li> <li> <p>If the source type is a DB snapshot, a <code>DBSnapshotIdentifier</code> value must be supplied.</p> </li> <li> <p>If the source type is a DB cluster snapshot, a <code>DBClusterSnapshotIdentifier</code> value must be supplied.</p> </li> <li> <p>If the source type is an RDS Proxy, a <code>DBProxyName</code> value must be supplied.</p> </li> </ul>"""
    enabled: NotRequired["capo_rds.types.boolean_optional.BooleanOptional"]
    """<p>Specifies whether to activate the subscription. If the event notification subscription isn't activated, the subscription is created but not active.</p>"""
    tags: NotRequired["capo_rds.types.tag_list.TagList"]


# --- awsQuery ser/de ---
def serialize_query(
    value: CreateEventSubscriptionMessage, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    if "subscription_name" in value:
        pairs.append((f"{key_prefix}SubscriptionName", str(value["subscription_name"])))
    if "sns_topic_arn" in value:
        pairs.append((f"{key_prefix}SnsTopicArn", str(value["sns_topic_arn"])))
    if "source_type" in value:
        pairs.append((f"{key_prefix}SourceType", str(value["source_type"])))
    if "event_categories" in value:
        import capo_rds.types.event_categories_list

        capo_rds.types.event_categories_list.serialize_query(
            value["event_categories"], pairs, f"{key_prefix}EventCategories"
        )
    if "source_ids" in value:
        import capo_rds.types.source_ids_list

        capo_rds.types.source_ids_list.serialize_query(
            value["source_ids"], pairs, f"{key_prefix}SourceIds"
        )
    if "enabled" in value:
        pairs.append((f"{key_prefix}Enabled", "true" if value["enabled"] else "false"))
    if "tags" in value:
        import capo_rds.types.tag_list

        capo_rds.types.tag_list.serialize_query(
            value["tags"], pairs, f"{key_prefix}Tags"
        )


def deserialize_query(el: Element) -> CreateEventSubscriptionMessage:
    out: CreateEventSubscriptionMessage = {}  # type: ignore[typeddict-item]
    child_subscription_name = el.find("SubscriptionName")
    if child_subscription_name is not None:
        out["subscription_name"] = str(child_subscription_name.text or "")
    child_sns_topic_arn = el.find("SnsTopicArn")
    if child_sns_topic_arn is not None:
        out["sns_topic_arn"] = str(child_sns_topic_arn.text or "")
    child_source_type = el.find("SourceType")
    if child_source_type is not None:
        out["source_type"] = str(child_source_type.text or "")
    child_event_categories = el.find("EventCategories")
    if child_event_categories is not None:
        import capo_rds.types.event_categories_list

        out["event_categories"] = (
            capo_rds.types.event_categories_list.deserialize_query(
                child_event_categories
            )
        )
    child_source_ids = el.find("SourceIds")
    if child_source_ids is not None:
        import capo_rds.types.source_ids_list

        out["source_ids"] = capo_rds.types.source_ids_list.deserialize_query(
            child_source_ids
        )
    child_enabled = el.find("Enabled")
    if child_enabled is not None:
        out["enabled"] = (child_enabled.text or "").lower() == "true"
    child_tags = el.find("Tags")
    if child_tags is not None:
        import capo_rds.types.tag_list

        out["tags"] = capo_rds.types.tag_list.deserialize_query(child_tags)
    return out
