"""Generated from Smithy shape ``com.amazonaws.rds#ModifyEventSubscriptionMessage``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_rds._protocol.xml import Element

if TYPE_CHECKING:
    import capo_rds.types.boolean_optional
    import capo_rds.types.event_categories_list
    import capo_rds.types.string


class ModifyEventSubscriptionMessage(TypedDict, closed=True):
    subscription_name: NotRequired["capo_rds.types.string.String"]
    """<p>The name of the RDS event notification subscription.</p>"""
    sns_topic_arn: NotRequired["capo_rds.types.string.String"]
    """<p>The Amazon Resource Name (ARN) of the SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it.</p>"""
    source_type: NotRequired["capo_rds.types.string.String"]
    """<p>The type of source that is generating the events. For example, if you want to be notified of events generated by a DB instance, you would set this parameter to db-instance. For RDS Proxy events, specify <code>db-proxy</code>. If this value isn't specified, all events are returned.</p> <p>Valid Values:<code> db-instance | db-cluster | db-parameter-group | db-security-group | db-snapshot | db-cluster-snapshot | db-proxy | zero-etl | custom-engine-version | blue-green-deployment </code> </p>"""
    event_categories: NotRequired[
        "capo_rds.types.event_categories_list.EventCategoriesList"
    ]
    """<p>A list of event categories for a source type (<code>SourceType</code>) that you want to subscribe to. You can see a list of the categories for a given source type in <a href="https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.html">Events</a> in the <i>Amazon RDS User Guide</i> or by using the <code>DescribeEventCategories</code> operation.</p>"""
    enabled: NotRequired["capo_rds.types.boolean_optional.BooleanOptional"]
    """<p>Specifies whether to activate the subscription.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: ModifyEventSubscriptionMessage, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    if "subscription_name" in value:
        pairs.append((f"{key_prefix}SubscriptionName", str(value["subscription_name"])))
    if "sns_topic_arn" in value:
        pairs.append((f"{key_prefix}SnsTopicArn", str(value["sns_topic_arn"])))
    if "source_type" in value:
        pairs.append((f"{key_prefix}SourceType", str(value["source_type"])))
    if "event_categories" in value:
        import capo_rds.types.event_categories_list

        capo_rds.types.event_categories_list.serialize_query(
            value["event_categories"], pairs, f"{key_prefix}EventCategories"
        )
    if "enabled" in value:
        pairs.append((f"{key_prefix}Enabled", "true" if value["enabled"] else "false"))


def deserialize_query(el: Element) -> ModifyEventSubscriptionMessage:
    out: ModifyEventSubscriptionMessage = {}  # type: ignore[typeddict-item]
    child_subscription_name = el.find("SubscriptionName")
    if child_subscription_name is not None:
        out["subscription_name"] = str(child_subscription_name.text or "")
    child_sns_topic_arn = el.find("SnsTopicArn")
    if child_sns_topic_arn is not None:
        out["sns_topic_arn"] = str(child_sns_topic_arn.text or "")
    child_source_type = el.find("SourceType")
    if child_source_type is not None:
        out["source_type"] = str(child_source_type.text or "")
    child_event_categories = el.find("EventCategories")
    if child_event_categories is not None:
        import capo_rds.types.event_categories_list

        out["event_categories"] = (
            capo_rds.types.event_categories_list.deserialize_query(
                child_event_categories
            )
        )
    child_enabled = el.find("Enabled")
    if child_enabled is not None:
        out["enabled"] = (child_enabled.text or "").lower() == "true"
    return out
