"""Generated from Smithy shape ``com.amazonaws.ebs#PutSnapshotBlockRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_ebs.types.block_data
    import capo_ebs.types.block_index
    import capo_ebs.types.checksum
    import capo_ebs.types.checksum_algorithm
    import capo_ebs.types.data_length
    import capo_ebs.types.progress
    import capo_ebs.types.snapshot_id


class PutSnapshotBlockRequest(TypedDict, closed=True):
    snapshot_id: "capo_ebs.types.snapshot_id.SnapshotId"
    """<p>The ID of the snapshot.</p> <important> <p>If the specified snapshot is encrypted, you must have permission to use the KMS key that was used to encrypt the snapshot. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebsapis-using-encryption.html"> Using encryption</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>..</p> </important>"""
    block_index: "capo_ebs.types.block_index.BlockIndex"
    """<p>The block index of the block in which to write the data. A block index is a logical index in units of <code>512</code> KiB blocks. To identify the block index, divide the logical offset of the data in the logical volume by the block size (logical offset of data/<code>524288</code>). The logical offset of the data must be <code>512</code> KiB aligned.</p>"""
    block_data: "capo_ebs.types.block_data.BlockData"
    """<p>The data to write to the block.</p> <p>The block data is not signed as part of the Signature Version 4 signing process. As a result, you must generate and provide a Base64-encoded SHA256 checksum for the block data using the <b>x-amz-Checksum</b> header. Also, you must specify the checksum algorithm using the <b>x-amz-Checksum-Algorithm</b> header. The checksum that you provide is part of the Signature Version 4 signing process. It is validated against a checksum generated by Amazon EBS to ensure the validity and authenticity of the data. If the checksums do not correspond, the request fails. For more information, see <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-accessing-snapshot.html#ebsapis-using-checksums"> Using checksums with the EBS direct APIs</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>"""
    data_length: "capo_ebs.types.data_length.DataLength"
    """<p>The size of the data to write to the block, in bytes. Currently, the only supported size is <code>524288</code> bytes.</p> <p>Valid values: <code>524288</code> </p>"""
    progress: NotRequired["capo_ebs.types.progress.Progress"]
    """<p>The progress of the write process, as a percentage.</p>"""
    checksum: "capo_ebs.types.checksum.Checksum"
    """<p>A Base64-encoded SHA256 checksum of the data. Only SHA256 checksums are supported.</p>"""
    checksum_algorithm: "capo_ebs.types.checksum_algorithm.ChecksumAlgorithm"
    """<p>The algorithm used to generate the checksum. Currently, the only supported algorithm is <code>SHA256</code>.</p>"""
