"""Generated from Smithy shape ``com.amazonaws.iam#CreateSAMLProviderRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_iam._protocol.xml import Element
from capo_iam.errors import DeserializationError

if TYPE_CHECKING:
    import capo_iam.types.assertion_encryption_mode_type
    import capo_iam.types.private_key_type
    import capo_iam.types.saml_metadata_document_type
    import capo_iam.types.saml_provider_name_type
    import capo_iam.types.tag_list_type


class CreateSAMLProviderRequest(TypedDict, closed=True):
    saml_metadata_document: (
        "capo_iam.types.saml_metadata_document_type.SAMLMetadataDocumentType"
    )
    """<p>An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document includes the issuer's name, expiration information, and keys that can be used to validate the SAML authentication response (assertions) that are received from the IdP. You must generate the metadata document using the identity management software that is used as your organization's IdP.</p> <p>For more information, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html">About SAML 2.0-based federation</a> in the <i>IAM User Guide</i> </p>"""
    name: "capo_iam.types.saml_provider_name_type.SAMLProviderNameType"
    """<p>The name of the provider to create.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>"""
    tags: NotRequired["capo_iam.types.tag_list_type.tagListType"]
    """<p>A list of tags that you want to attach to the new IAM SAML provider. Each tag consists of a key name and an associated value. For more information about tagging, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html">Tagging IAM resources</a> in the <i>IAM User Guide</i>.</p> <note> <p>If any one of the tags is invalid or if you exceed the allowed maximum number of tags, then the entire request fails and the resource is not created.</p> </note>"""
    assertion_encryption_mode: NotRequired[
        "capo_iam.types.assertion_encryption_mode_type.assertionEncryptionModeType"
    ]
    """<p>Specifies the encryption setting for the SAML provider.</p>"""
    add_private_key: NotRequired["capo_iam.types.private_key_type.privateKeyType"]
    """<p>The private key generated from your external identity provider. The private key must be a .pem file that uses AES-GCM or AES-CBC encryption algorithm to decrypt SAML assertions.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: CreateSAMLProviderRequest, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    pairs.append(
        (f"{key_prefix}SAMLMetadataDocument", str(value["saml_metadata_document"]))
    )
    pairs.append((f"{key_prefix}Name", str(value["name"])))
    if "tags" in value:
        import capo_iam.types.tag_list_type

        capo_iam.types.tag_list_type.serialize_query(
            value["tags"], pairs, f"{key_prefix}Tags"
        )
    if "assertion_encryption_mode" in value:
        import capo_iam.types.assertion_encryption_mode_type

        capo_iam.types.assertion_encryption_mode_type.serialize_query(
            value["assertion_encryption_mode"],
            pairs,
            f"{key_prefix}AssertionEncryptionMode",
        )
    if "add_private_key" in value:
        pairs.append((f"{key_prefix}AddPrivateKey", str(value["add_private_key"])))


def deserialize_query(el: Element) -> CreateSAMLProviderRequest:
    out: CreateSAMLProviderRequest = {}  # type: ignore[typeddict-item]
    child_saml_metadata_document = el.find("SAMLMetadataDocument")
    if child_saml_metadata_document is not None:
        out["saml_metadata_document"] = str(child_saml_metadata_document.text or "")
    else:
        raise DeserializationError(
            "CreateSAMLProviderRequest.saml_metadata_document required"
        )
    child_name = el.find("Name")
    if child_name is not None:
        out["name"] = str(child_name.text or "")
    else:
        raise DeserializationError("CreateSAMLProviderRequest.name required")
    child_tags = el.find("Tags")
    if child_tags is not None:
        import capo_iam.types.tag_list_type

        out["tags"] = capo_iam.types.tag_list_type.deserialize_query(child_tags)
    child_assertion_encryption_mode = el.find("AssertionEncryptionMode")
    if child_assertion_encryption_mode is not None:
        import capo_iam.types.assertion_encryption_mode_type

        out["assertion_encryption_mode"] = (
            capo_iam.types.assertion_encryption_mode_type.deserialize_query(
                child_assertion_encryption_mode
            )
        )
    child_add_private_key = el.find("AddPrivateKey")
    if child_add_private_key is not None:
        out["add_private_key"] = str(child_add_private_key.text or "")
    return out
