"""Generated from Smithy shape ``com.amazonaws.iam#GetServiceLastAccessedDetailsWithEntitiesRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_iam._protocol.xml import Element
from capo_iam.errors import DeserializationError

if TYPE_CHECKING:
    import capo_iam.types.job_id_type
    import capo_iam.types.marker_type
    import capo_iam.types.max_items_type
    import capo_iam.types.service_namespace_type


class GetServiceLastAccessedDetailsWithEntitiesRequest(TypedDict, closed=True):
    job_id: "capo_iam.types.job_id_type.jobIDType"
    """<p>The ID of the request generated by the <code>GenerateServiceLastAccessedDetails</code> operation.</p>"""
    service_namespace: "capo_iam.types.service_namespace_type.serviceNamespaceType"
    """<p>The service namespace for an Amazon Web Services service. Provide the service namespace to learn when the IAM entity last attempted to access the specified service.</p> <p>To learn the service namespace for a service, see <a href="https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html">Actions, resources, and condition keys for Amazon Web Services services</a> in the <i>IAM User Guide</i>. Choose the name of the service to view details for that service. In the first paragraph, find the service prefix. For example, <code>(service prefix: a4b)</code>. For more information about service namespaces, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-aws-service-namespaces">Amazon Web Services service namespaces</a> in the <i>Amazon Web Services General Reference</i>.</p>"""
    max_items: NotRequired["capo_iam.types.max_items_type.maxItemsType"]
    """<p>Use this only when paginating results to indicate the maximum number of items you want in the response. If additional items exist beyond the maximum you specify, the <code>IsTruncated</code> response element is <code>true</code>.</p> <p>If you do not include this parameter, the number of items defaults to 100. Note that IAM might return fewer results, even when there are more results available. In that case, the <code>IsTruncated</code> response element returns <code>true</code>, and <code>Marker</code> contains a value to include in the subsequent call that tells the service where to continue from.</p>"""
    marker: NotRequired["capo_iam.types.marker_type.markerType"]
    """<p>Use this parameter only when paginating results and only after you receive a response indicating that the results are truncated. Set it to the value of the <code>Marker</code> element in the response that you received to indicate where the next call should start.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: GetServiceLastAccessedDetailsWithEntitiesRequest,
    pairs: list[tuple[str, str]],
    prefix: str,
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    pairs.append((f"{key_prefix}JobId", str(value["job_id"])))
    pairs.append((f"{key_prefix}ServiceNamespace", str(value["service_namespace"])))
    if "max_items" in value:
        pairs.append((f"{key_prefix}MaxItems", str(value["max_items"])))
    if "marker" in value:
        pairs.append((f"{key_prefix}Marker", str(value["marker"])))


def deserialize_query(el: Element) -> GetServiceLastAccessedDetailsWithEntitiesRequest:
    out: GetServiceLastAccessedDetailsWithEntitiesRequest = {}  # type: ignore[typeddict-item]
    child_job_id = el.find("JobId")
    if child_job_id is not None:
        out["job_id"] = str(child_job_id.text or "")
    else:
        raise DeserializationError(
            "GetServiceLastAccessedDetailsWithEntitiesRequest.job_id required"
        )
    child_service_namespace = el.find("ServiceNamespace")
    if child_service_namespace is not None:
        out["service_namespace"] = str(child_service_namespace.text or "")
    else:
        raise DeserializationError(
            "GetServiceLastAccessedDetailsWithEntitiesRequest.service_namespace required"
        )
    child_max_items = el.find("MaxItems")
    if child_max_items is not None:
        out["max_items"] = int(child_max_items.text or "")
    child_marker = el.find("Marker")
    if child_marker is not None:
        out["marker"] = str(child_marker.text or "")
    return out
