"""Generated from Smithy shape ``com.amazonaws.iam#GetOrganizationsAccessReportRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_iam._protocol.xml import Element
from capo_iam.errors import DeserializationError

if TYPE_CHECKING:
    import capo_iam.types.job_id_type
    import capo_iam.types.marker_type
    import capo_iam.types.max_items_type
    import capo_iam.types.sort_key_type


class GetOrganizationsAccessReportRequest(TypedDict, closed=True):
    job_id: "capo_iam.types.job_id_type.jobIDType"
    """<p>The identifier of the request generated by the <a href="https://docs.aws.amazon.com/IAM/latest/APIReference/API_GenerateOrganizationsAccessReport.html">GenerateOrganizationsAccessReport</a> operation.</p>"""
    max_items: NotRequired["capo_iam.types.max_items_type.maxItemsType"]
    """<p>Use this only when paginating results to indicate the maximum number of items you want in the response. If additional items exist beyond the maximum you specify, the <code>IsTruncated</code> response element is <code>true</code>.</p> <p>If you do not include this parameter, the number of items defaults to 100. Note that IAM might return fewer results, even when there are more results available. In that case, the <code>IsTruncated</code> response element returns <code>true</code>, and <code>Marker</code> contains a value to include in the subsequent call that tells the service where to continue from.</p>"""
    marker: NotRequired["capo_iam.types.marker_type.markerType"]
    """<p>Use this parameter only when paginating results and only after you receive a response indicating that the results are truncated. Set it to the value of the <code>Marker</code> element in the response that you received to indicate where the next call should start.</p>"""
    sort_key: NotRequired["capo_iam.types.sort_key_type.sortKeyType"]
    """<p>The key that is used to sort the results. If you choose the namespace key, the results are returned in alphabetical order. If you choose the time key, the results are sorted numerically by the date and time.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: GetOrganizationsAccessReportRequest,
    pairs: list[tuple[str, str]],
    prefix: str,
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    pairs.append((f"{key_prefix}JobId", str(value["job_id"])))
    if "max_items" in value:
        pairs.append((f"{key_prefix}MaxItems", str(value["max_items"])))
    if "marker" in value:
        pairs.append((f"{key_prefix}Marker", str(value["marker"])))
    if "sort_key" in value:
        import capo_iam.types.sort_key_type

        capo_iam.types.sort_key_type.serialize_query(
            value["sort_key"], pairs, f"{key_prefix}SortKey"
        )


def deserialize_query(el: Element) -> GetOrganizationsAccessReportRequest:
    out: GetOrganizationsAccessReportRequest = {}  # type: ignore[typeddict-item]
    child_job_id = el.find("JobId")
    if child_job_id is not None:
        out["job_id"] = str(child_job_id.text or "")
    else:
        raise DeserializationError(
            "GetOrganizationsAccessReportRequest.job_id required"
        )
    child_max_items = el.find("MaxItems")
    if child_max_items is not None:
        out["max_items"] = int(child_max_items.text or "")
    child_marker = el.find("Marker")
    if child_marker is not None:
        out["marker"] = str(child_marker.text or "")
    child_sort_key = el.find("SortKey")
    if child_sort_key is not None:
        import capo_iam.types.sort_key_type

        out["sort_key"] = capo_iam.types.sort_key_type.deserialize_query(child_sort_key)
    return out
