"""Generated from Smithy shape ``com.amazonaws.iam#UpdateSAMLProviderRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_iam._protocol.xml import Element
from capo_iam.errors import DeserializationError

if TYPE_CHECKING:
    import capo_iam.types.arn_type
    import capo_iam.types.assertion_encryption_mode_type
    import capo_iam.types.private_key_id_type
    import capo_iam.types.private_key_type
    import capo_iam.types.saml_metadata_document_type


class UpdateSAMLProviderRequest(TypedDict, closed=True):
    saml_metadata_document: NotRequired[
        "capo_iam.types.saml_metadata_document_type.SAMLMetadataDocumentType"
    ]
    """<p>An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document includes the issuer's name, expiration information, and keys that can be used to validate the SAML authentication response (assertions) that are received from the IdP. You must generate the metadata document using the identity management software that is used as your IdP.</p>"""
    saml_provider_arn: "capo_iam.types.arn_type.arnType"
    """<p>The Amazon Resource Name (ARN) of the SAML provider to update.</p> <p>For more information about ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>.</p>"""
    assertion_encryption_mode: NotRequired[
        "capo_iam.types.assertion_encryption_mode_type.assertionEncryptionModeType"
    ]
    """<p>Specifies the encryption setting for the SAML provider.</p>"""
    add_private_key: NotRequired["capo_iam.types.private_key_type.privateKeyType"]
    """<p>Specifies the new private key from your external identity provider. The private key must be a .pem file that uses AES-GCM or AES-CBC encryption algorithm to decrypt SAML assertions.</p>"""
    remove_private_key: NotRequired[
        "capo_iam.types.private_key_id_type.privateKeyIdType"
    ]
    """<p>The Key ID of the private key to remove.</p>"""


# --- awsQuery ser/de ---
def serialize_query(
    value: UpdateSAMLProviderRequest, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    if "saml_metadata_document" in value:
        pairs.append(
            (f"{key_prefix}SAMLMetadataDocument", str(value["saml_metadata_document"]))
        )
    pairs.append((f"{key_prefix}SAMLProviderArn", str(value["saml_provider_arn"])))
    if "assertion_encryption_mode" in value:
        import capo_iam.types.assertion_encryption_mode_type

        capo_iam.types.assertion_encryption_mode_type.serialize_query(
            value["assertion_encryption_mode"],
            pairs,
            f"{key_prefix}AssertionEncryptionMode",
        )
    if "add_private_key" in value:
        pairs.append((f"{key_prefix}AddPrivateKey", str(value["add_private_key"])))
    if "remove_private_key" in value:
        pairs.append(
            (f"{key_prefix}RemovePrivateKey", str(value["remove_private_key"]))
        )


def deserialize_query(el: Element) -> UpdateSAMLProviderRequest:
    out: UpdateSAMLProviderRequest = {}  # type: ignore[typeddict-item]
    child_saml_metadata_document = el.find("SAMLMetadataDocument")
    if child_saml_metadata_document is not None:
        out["saml_metadata_document"] = str(child_saml_metadata_document.text or "")
    child_saml_provider_arn = el.find("SAMLProviderArn")
    if child_saml_provider_arn is not None:
        out["saml_provider_arn"] = str(child_saml_provider_arn.text or "")
    else:
        raise DeserializationError(
            "UpdateSAMLProviderRequest.saml_provider_arn required"
        )
    child_assertion_encryption_mode = el.find("AssertionEncryptionMode")
    if child_assertion_encryption_mode is not None:
        import capo_iam.types.assertion_encryption_mode_type

        out["assertion_encryption_mode"] = (
            capo_iam.types.assertion_encryption_mode_type.deserialize_query(
                child_assertion_encryption_mode
            )
        )
    child_add_private_key = el.find("AddPrivateKey")
    if child_add_private_key is not None:
        out["add_private_key"] = str(child_add_private_key.text or "")
    child_remove_private_key = el.find("RemovePrivateKey")
    if child_remove_private_key is not None:
        out["remove_private_key"] = str(child_remove_private_key.text or "")
    return out
