"""Generated from Smithy shape ``com.amazonaws.ec2#CreateVpcEndpointRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

from capo_ec2._protocol.xml import Element

if TYPE_CHECKING:
    import capo_ec2.types.boolean
    import capo_ec2.types.dns_options_specification
    import capo_ec2.types.ip_address_type
    import capo_ec2.types.resource_configuration_arn
    import capo_ec2.types.service_network_arn
    import capo_ec2.types.string
    import capo_ec2.types.subnet_configurations_list
    import capo_ec2.types.tag_specification_list
    import capo_ec2.types.vpc_endpoint_route_table_id_list
    import capo_ec2.types.vpc_endpoint_security_group_id_list
    import capo_ec2.types.vpc_endpoint_subnet_id_list
    import capo_ec2.types.vpc_endpoint_type
    import capo_ec2.types.vpc_id


class CreateVpcEndpointRequest(TypedDict, closed=True):
    dry_run: NotRequired["capo_ec2.types.boolean.Boolean"]
    """<p>Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is <code>DryRunOperation</code>. Otherwise, it is <code>UnauthorizedOperation</code>.</p>"""
    vpc_endpoint_type: NotRequired["capo_ec2.types.vpc_endpoint_type.VpcEndpointType"]
    """<p>The type of endpoint.</p> <p>For more information about the types of VPC endpoints, see <a href="https://docs.aws.amazon.com/vpc/latest/privatelink/concepts.html#concepts-vpc-endpoints">VPC endpoints</a> in the <i>Amazon Web Services PrivateLink User Guide</i>.</p> <p>Default: Gateway</p>"""
    vpc_id: NotRequired["capo_ec2.types.vpc_id.VpcId"]
    """<p>The ID of the VPC.</p>"""
    service_name: NotRequired["capo_ec2.types.string.String"]
    """<p>The name of the endpoint service.</p>"""
    policy_document: NotRequired["capo_ec2.types.string.String"]
    """<p>(Interface and gateway endpoints) A policy to attach to the endpoint that controls access to the service. The policy must be in valid JSON format. If this parameter is not specified, we attach a default policy that allows full access to the service.</p>"""
    route_table_ids: NotRequired[
        "capo_ec2.types.vpc_endpoint_route_table_id_list.VpcEndpointRouteTableIdList"
    ]
    """<p>(Gateway endpoint) The route table IDs.</p>"""
    subnet_ids: NotRequired[
        "capo_ec2.types.vpc_endpoint_subnet_id_list.VpcEndpointSubnetIdList"
    ]
    """<p>(Interface, Gateway Load Balancer endpoints, Resource, ServiceNetwork, and Tunnel endpoints only) The IDs of the subnets in which to create endpoint network interfaces. For a Gateway Load Balancer endpoint, you can specify only one subnet. For a <code>Tunnel</code> endpoint, the subnets must be in the Availability Zones of the resource gateway associated with the shared resource configuration. An endpoint network interface is created only in an Availability Zone that the resource gateway is also in.</p>"""
    security_group_ids: NotRequired[
        "capo_ec2.types.vpc_endpoint_security_group_id_list.VpcEndpointSecurityGroupIdList"
    ]
    """<p>(Interface, Resource, ServiceNetwork, and Tunnel endpoints only) The IDs of the security groups to associate with the endpoint network interfaces. If this parameter is not specified, we use the default security group for the VPC.</p>"""
    ip_address_type: NotRequired["capo_ec2.types.ip_address_type.IpAddressType"]
    """<p>The IP address type for the endpoint.</p>"""
    dns_options: NotRequired[
        "capo_ec2.types.dns_options_specification.DnsOptionsSpecification"
    ]
    """<p>The DNS options for the endpoint.</p>"""
    client_token: NotRequired["capo_ec2.types.string.String"]
    """<p>Unique, case-sensitive identifier that you provide to ensure the idempotency of the request. For more information, see <a href="https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-idempotency.html">How to ensure idempotency</a>.</p>"""
    private_dns_enabled: NotRequired["capo_ec2.types.boolean.Boolean"]
    """<p>(Interface endpoint) Indicates whether to associate a private hosted zone with the specified VPC. The private hosted zone contains a record set for the default public DNS name for the service for the Region (for example, <code>kinesis.us-east-1.amazonaws.com</code>), which resolves to the private IP addresses of the endpoint network interfaces in the VPC. This enables you to make requests to the default public DNS name for the service instead of the public DNS names that are automatically generated by the VPC endpoint service.</p> <p>To use a private hosted zone, you must set the following VPC attributes to <code>true</code>: <code>enableDnsHostnames</code> and <code>enableDnsSupport</code>. Use <a>ModifyVpcAttribute</a> to set the VPC attributes.</p>"""
    tag_specifications: NotRequired[
        "capo_ec2.types.tag_specification_list.TagSpecificationList"
    ]
    """<p>The tags to associate with the endpoint.</p>"""
    subnet_configurations: NotRequired[
        "capo_ec2.types.subnet_configurations_list.SubnetConfigurationsList"
    ]
    """<p>The subnet configurations for the endpoint.</p>"""
    service_network_arn: NotRequired[
        "capo_ec2.types.service_network_arn.ServiceNetworkArn"
    ]
    """<p>The Amazon Resource Name (ARN) of a service network that will be associated with the VPC endpoint of type service-network.</p>"""
    resource_configuration_arn: NotRequired[
        "capo_ec2.types.resource_configuration_arn.ResourceConfigurationArn"
    ]
    """<p>(Resource and Tunnel endpoints only) The Amazon Resource Name (ARN) of a resource configuration associated with the VPC endpoint. The type of resource configuration depends on the endpoint type:</p> <ul> <li> <p>For a Resource endpoint, you can specify a resource configuration that is of type <code>SINGLE</code>, <code>GROUP</code>, or <code>ARN</code>. To reach a resource that belongs to a group, specify the parent <code>GROUP</code> resource configuration.</p> </li> <li> <p>For a Tunnel endpoint, you can specify a resource configuration that is of type <code>CIDR</code>.</p> </li> </ul> <p>For more information about the types of resource configurations, see <a href="https://docs.aws.amazon.com/vpc/latest/privatelink/resource-configuration.html">Types of resource configurations</a> in the <i>Amazon Web Services PrivateLink User Guide</i>.</p> <p>This request fails if a VPC endpoint owned by a different Amazon Web Services account already exists on a resource gateway that is enabled for <code>ResourceGatewayCharges</code> payer responsibility.</p>"""
    service_region: NotRequired["capo_ec2.types.string.String"]
    """<p>The Region where the service is hosted. The default is the current Region.</p>"""


# --- ec2Query ser/de ---
def serialize_ec2_query(
    value: CreateVpcEndpointRequest, pairs: list[tuple[str, str]], prefix: str
) -> None:
    key_prefix = f"{prefix}." if prefix else ""
    if "dry_run" in value:
        pairs.append((f"{key_prefix}DryRun", "true" if value["dry_run"] else "false"))
    if "vpc_endpoint_type" in value:
        import capo_ec2.types.vpc_endpoint_type

        capo_ec2.types.vpc_endpoint_type.serialize_ec2_query(
            value["vpc_endpoint_type"], pairs, f"{key_prefix}VpcEndpointType"
        )
    if "vpc_id" in value:
        pairs.append((f"{key_prefix}VpcId", str(value["vpc_id"])))
    if "service_name" in value:
        pairs.append((f"{key_prefix}ServiceName", str(value["service_name"])))
    if "policy_document" in value:
        pairs.append((f"{key_prefix}PolicyDocument", str(value["policy_document"])))
    if "route_table_ids" in value:
        import capo_ec2.types.vpc_endpoint_route_table_id_list

        capo_ec2.types.vpc_endpoint_route_table_id_list.serialize_ec2_query(
            value["route_table_ids"], pairs, f"{key_prefix}RouteTableId"
        )
    if "subnet_ids" in value:
        import capo_ec2.types.vpc_endpoint_subnet_id_list

        capo_ec2.types.vpc_endpoint_subnet_id_list.serialize_ec2_query(
            value["subnet_ids"], pairs, f"{key_prefix}SubnetId"
        )
    if "security_group_ids" in value:
        import capo_ec2.types.vpc_endpoint_security_group_id_list

        capo_ec2.types.vpc_endpoint_security_group_id_list.serialize_ec2_query(
            value["security_group_ids"], pairs, f"{key_prefix}SecurityGroupId"
        )
    if "ip_address_type" in value:
        import capo_ec2.types.ip_address_type

        capo_ec2.types.ip_address_type.serialize_ec2_query(
            value["ip_address_type"], pairs, f"{key_prefix}IpAddressType"
        )
    if "dns_options" in value:
        import capo_ec2.types.dns_options_specification

        capo_ec2.types.dns_options_specification.serialize_ec2_query(
            value["dns_options"], pairs, f"{key_prefix}DnsOptions"
        )
    if "client_token" in value:
        pairs.append((f"{key_prefix}ClientToken", str(value["client_token"])))
    if "private_dns_enabled" in value:
        pairs.append(
            (
                f"{key_prefix}PrivateDnsEnabled",
                "true" if value["private_dns_enabled"] else "false",
            )
        )
    if "tag_specifications" in value:
        import capo_ec2.types.tag_specification_list

        capo_ec2.types.tag_specification_list.serialize_ec2_query(
            value["tag_specifications"], pairs, f"{key_prefix}TagSpecification"
        )
    if "subnet_configurations" in value:
        import capo_ec2.types.subnet_configurations_list

        capo_ec2.types.subnet_configurations_list.serialize_ec2_query(
            value["subnet_configurations"], pairs, f"{key_prefix}SubnetConfiguration"
        )
    if "service_network_arn" in value:
        pairs.append(
            (f"{key_prefix}ServiceNetworkArn", str(value["service_network_arn"]))
        )
    if "resource_configuration_arn" in value:
        pairs.append(
            (
                f"{key_prefix}ResourceConfigurationArn",
                str(value["resource_configuration_arn"]),
            )
        )
    if "service_region" in value:
        pairs.append((f"{key_prefix}ServiceRegion", str(value["service_region"])))


def deserialize_ec2_query(el: Element) -> CreateVpcEndpointRequest:
    out: CreateVpcEndpointRequest = {}  # type: ignore[typeddict-item]
    child_dry_run = el.find("DryRun")
    if child_dry_run is not None:
        out["dry_run"] = (child_dry_run.text or "").lower() == "true"
    child_vpc_endpoint_type = el.find("VpcEndpointType")
    if child_vpc_endpoint_type is not None:
        import capo_ec2.types.vpc_endpoint_type

        out["vpc_endpoint_type"] = (
            capo_ec2.types.vpc_endpoint_type.deserialize_ec2_query(
                child_vpc_endpoint_type
            )
        )
    child_vpc_id = el.find("VpcId")
    if child_vpc_id is not None:
        out["vpc_id"] = str(child_vpc_id.text or "")
    child_service_name = el.find("ServiceName")
    if child_service_name is not None:
        out["service_name"] = str(child_service_name.text or "")
    child_policy_document = el.find("PolicyDocument")
    if child_policy_document is not None:
        out["policy_document"] = str(child_policy_document.text or "")
    child_route_table_ids = el.find("RouteTableId")
    if child_route_table_ids is not None:
        import capo_ec2.types.vpc_endpoint_route_table_id_list

        out["route_table_ids"] = (
            capo_ec2.types.vpc_endpoint_route_table_id_list.deserialize_ec2_query(
                child_route_table_ids
            )
        )
    child_subnet_ids = el.find("SubnetId")
    if child_subnet_ids is not None:
        import capo_ec2.types.vpc_endpoint_subnet_id_list

        out["subnet_ids"] = (
            capo_ec2.types.vpc_endpoint_subnet_id_list.deserialize_ec2_query(
                child_subnet_ids
            )
        )
    child_security_group_ids = el.find("SecurityGroupId")
    if child_security_group_ids is not None:
        import capo_ec2.types.vpc_endpoint_security_group_id_list

        out["security_group_ids"] = (
            capo_ec2.types.vpc_endpoint_security_group_id_list.deserialize_ec2_query(
                child_security_group_ids
            )
        )
    child_ip_address_type = el.find("IpAddressType")
    if child_ip_address_type is not None:
        import capo_ec2.types.ip_address_type

        out["ip_address_type"] = capo_ec2.types.ip_address_type.deserialize_ec2_query(
            child_ip_address_type
        )
    child_dns_options = el.find("DnsOptions")
    if child_dns_options is not None:
        import capo_ec2.types.dns_options_specification

        out["dns_options"] = (
            capo_ec2.types.dns_options_specification.deserialize_ec2_query(
                child_dns_options
            )
        )
    child_client_token = el.find("ClientToken")
    if child_client_token is not None:
        out["client_token"] = str(child_client_token.text or "")
    child_private_dns_enabled = el.find("PrivateDnsEnabled")
    if child_private_dns_enabled is not None:
        out["private_dns_enabled"] = (
            child_private_dns_enabled.text or ""
        ).lower() == "true"
    child_tag_specifications = el.find("TagSpecification")
    if child_tag_specifications is not None:
        import capo_ec2.types.tag_specification_list

        out["tag_specifications"] = (
            capo_ec2.types.tag_specification_list.deserialize_ec2_query(
                child_tag_specifications
            )
        )
    child_subnet_configurations = el.find("SubnetConfiguration")
    if child_subnet_configurations is not None:
        import capo_ec2.types.subnet_configurations_list

        out["subnet_configurations"] = (
            capo_ec2.types.subnet_configurations_list.deserialize_ec2_query(
                child_subnet_configurations
            )
        )
    child_service_network_arn = el.find("ServiceNetworkArn")
    if child_service_network_arn is not None:
        out["service_network_arn"] = str(child_service_network_arn.text or "")
    child_resource_configuration_arn = el.find("ResourceConfigurationArn")
    if child_resource_configuration_arn is not None:
        out["resource_configuration_arn"] = str(
            child_resource_configuration_arn.text or ""
        )
    child_service_region = el.find("ServiceRegion")
    if child_service_region is not None:
        out["service_region"] = str(child_service_region.text or "")
    return out
