"""Generated from Smithy shape ``com.amazonaws.guardduty#CreateThreatIntelSetRequest``."""

from typing import TYPE_CHECKING

from typing_extensions import NotRequired, TypedDict

if TYPE_CHECKING:
    import capo_guardduty.types.account_id
    import capo_guardduty.types.boolean
    import capo_guardduty.types.client_token
    import capo_guardduty.types.detector_id
    import capo_guardduty.types.location
    import capo_guardduty.types.name
    import capo_guardduty.types.tag_map
    import capo_guardduty.types.threat_intel_set_format


class CreateThreatIntelSetRequest(TypedDict, closed=True):
    detector_id: "capo_guardduty.types.detector_id.DetectorId"
    """<p>The unique ID of the detector of the GuardDuty account for which you want to create a <code>threatIntelSet</code>.</p> <p>To find the <code>detectorId</code> in the current Region, see the Settings page in the GuardDuty console, or run the <a href="https://docs.aws.amazon.com/guardduty/latest/APIReference/API_ListDetectors.html">ListDetectors</a> API.</p>"""
    name: NotRequired["capo_guardduty.types.name.Name"]
    """<p>A user-friendly ThreatIntelSet name displayed in all findings that are generated by activity that involves IP addresses included in this ThreatIntelSet.</p>"""
    format: NotRequired[
        "capo_guardduty.types.threat_intel_set_format.ThreatIntelSetFormat"
    ]
    """<p>The format of the file that contains the ThreatIntelSet.</p>"""
    location: NotRequired["capo_guardduty.types.location.Location"]
    """<p>The URI of the file that contains the ThreatIntelSet. </p>"""
    activate: NotRequired["capo_guardduty.types.boolean.Boolean"]
    """<p>A Boolean value that indicates whether GuardDuty is to start using the uploaded ThreatIntelSet.</p>"""
    client_token: NotRequired["capo_guardduty.types.client_token.ClientToken"]
    """<p>The idempotency token for the create request.</p>"""
    tags: NotRequired["capo_guardduty.types.tag_map.TagMap"]
    """<p>The tags to be added to a new threat list resource.</p>"""
    expected_bucket_owner: NotRequired["capo_guardduty.types.account_id.AccountId"]
    """<p>The Amazon Web Services account ID that owns the Amazon S3 bucket specified in the <b>location</b> parameter.</p>"""


# --- restJson1 ser/de ---
def serialize_json(value: CreateThreatIntelSetRequest) -> dict:
    out: dict = {}
    if "name" in value:
        out["name"] = value["name"]
    if "format" in value:
        import capo_guardduty.types.threat_intel_set_format

        out["format"] = capo_guardduty.types.threat_intel_set_format.serialize_json(
            value["format"]
        )
    if "location" in value:
        out["location"] = value["location"]
    if "activate" in value:
        out["activate"] = value["activate"]
    if "client_token" in value:
        out["clientToken"] = value["client_token"]
    if "tags" in value:
        import capo_guardduty.types.tag_map

        out["tags"] = capo_guardduty.types.tag_map.serialize_json(value["tags"])
    if "expected_bucket_owner" in value:
        out["expectedBucketOwner"] = value["expected_bucket_owner"]
    return out


def deserialize_json(data: dict) -> CreateThreatIntelSetRequest:
    out: CreateThreatIntelSetRequest = {}  # type: ignore[typeddict-item]
    if data.get("name") is not None:
        out["name"] = data["name"]
    if data.get("format") is not None:
        import capo_guardduty.types.threat_intel_set_format

        out["format"] = capo_guardduty.types.threat_intel_set_format.deserialize_json(
            data["format"]
        )
    if data.get("location") is not None:
        out["location"] = data["location"]
    if data.get("activate") is not None:
        out["activate"] = data["activate"]
    if data.get("clientToken") is not None:
        out["client_token"] = data["clientToken"]
    if data.get("tags") is not None:
        import capo_guardduty.types.tag_map

        out["tags"] = capo_guardduty.types.tag_map.deserialize_json(data["tags"])
    if data.get("expectedBucketOwner") is not None:
        out["expected_bucket_owner"] = data["expectedBucketOwner"]
    return out
